### ISSUE TITLE
lb-ng fails in windows xp

### ISSUE THREAD

**Issue by solenovex** [strongloop/loopback#1147]
In the tutorial  LoopBack/Getting started part II http://docs.strongloop.com/display/public/LB/Create+AngularJS+client, When I try to execute command: lb-ng server/server.js client/js/services/lb-services.js.
It failed:
C:\learn\loopbackLearn>lb-ng server/server.js client/js/services/lb-services.js
Loading LoopBack app "C:\\learn\\loopbackLearn\\server\\server.js"
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
module.js:338
    throw err;
    ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\learn\loopbackLearn\server\boot\create-sample-mode
ls.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by solenovex** [comment]
sorry, my bad, mongodb doesn't support windows xp anymore.
