### ISSUE TITLE
Require Fails Silently in Boot Script

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback#1170]
If I have this in a boot script:

``` javascript
var foo = require('foo');

module.exports = function(server) {
  console.log('in foo!');
};
```

The script will silently fail to load (console.log never prints).  There's no error message, and the server apparently starts as normal.  I also tried `throw new Error('oops')` in place of the require and this is silently caught.

I would expect the server to crash and an error to print.

I'm on `loopback@2.7.0`.

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by bajtos** [comment]
@superkhau this bug report is clear enough, there's no need for a full test project.

@bitmage @clarkbw The pull request #115 will modify loopback-boot to print an error message instead of swallowing the error silently. I feel that if we start throwing an error, then that would be a breaking change. However, I am ok to ad a flag to the options object that will control the handling of `require` errors.

```js
// example usage
boot(app, {
  appRootDir: __dirname,
  abortOnScriptErrors: true
});
```

Thoughts?

**Comment by bajtos** [comment]
I did a quick check how different versions of loopback-boot handle this problem

 - the latest 1.x crashes the process via unhandled error
 - 2.0.0 - 2.6.1 report the error message via `debug`
 - 2.6.2 and newer crashes the process via unhandled error

**Comment by clarkbw** [comment]
> I feel that if we start throwing an error, then that would be a breaking change. However, I am ok to ad a flag to the options object that will control the handling of require errors.

Agreed, I'll update the PR so we print an error message.  The option to crash makes sense to me, but I'm not sure that I would personally find it useful, I'll let someone else take that effort over.  At least in my setup I'd rather the production servers are up and connected to the database than to crash because a boot script broke.

FYI the suggested changes from @bajtos will give a useful error message like this:
```
Failed loading boot script: /Users/clarkbw/src/pi/loopback-boot/test/sandbox/9ec895eefb/boot/badScript.js
Error: Cannot find module 'doesnt-exist'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/clarkbw/src/pi/loopback-boot/test/sandbox/9ec895eefb/boot/badScript.js:1:63)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/clarkbw/src/pi/loopback-boot/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /Users/clarkbw/src/pi/loopback-boot/lib/executor.js:235:21
  at Array.forEach (native)
  at runScripts (/Users/clarkbw/src/pi/loopback-boot/lib/executor.js:232:8)
  at runBootScripts (/Users/clarkbw/src/pi/loopback-boot/lib/executor.js:306:3)
  at /Users/clarkbw/src/pi/loopback-boot/lib/executor.js:41:7
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:610:21
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:249:17
  at iterate (/Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:149:13)
  at async.eachSeries (/Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:165:9)
  at _asyncMap (/Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:248:13)
  at Object.mapSeries (/Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:231:23)
  at Object.async.series (/Users/clarkbw/src/pi/loopback-boot/node_modules/async/lib/async.js:608:19)
  at Function.execute (/Users/clarkbw/src/pi/loopback-boot/lib/executor.js:39:9)
  at doBoot (/Users/clarkbw/src/pi/loopback-boot/test/executor.test.js:205:12)
  at Assertion.assertThrows (/Users/clarkbw/src/pi/loopback-boot/node_modules/chai/lib/chai/core/assertions.js:1097:7)
  at Assertion.ctx.(anonymous function) [as throw] (/Users/clarkbw/src/pi/loopback-boot/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
  at Context.<anonymous> (/Users/clarkbw/src/pi/loopback-boot/test/executor.test.js:208:28)
  at callFn (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:250:21)
  at Test.Runnable.run (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:243:7)
  at Runner.runTest (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:373:10)
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:451:12
  at next (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:298:14)
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:308:7
  at next (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:246:23)
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:270:7
  at done (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:206:5)
  at callFn (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:261:7)
  at Hook.Runnable.run (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:243:7)
  at next (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:258:10)
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runner.js:270:7
  at done (/Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:206:5)
  at /Users/clarkbw/src/pi/loopback-boot/node_modules/mocha/lib/runnable.js:226:9
  at Object.ondone (/Users/clarkbw/src/pi/loopback-boot/test/helpers/appdir.js:18:5)
```

**Comment by bitmage** [comment]
I'd rather it just crash.  If something didn't boot properly then the system is in an inconsistent/unknown state and should not proceed.

**Comment by raymondfeng** [comment]
Letting it crash sounds reasonable to me.

**Comment by bajtos** [comment]
:+1: for crashing.

Users can always modify their boot script to ignore unhandled errors if they wish so.

```js
module.exports = function(app) {
  try {
    // do some work
  } catch(err) {
    // report and discard err
  }
};
```

**Comment by clarkbw** [comment]
I just reviewed the code again to check but we didn't stop throwing the error so the server _does still crash_ on a bad require.  I was unclear above about the option.

A bad require like this:
```javascript
var stuff = require('stuff');

module.exports = function enableAuthentication(server) {
  // enable authentication
  server.enableAuth();
};
```

Will generate an error message like this: 

```
Failed loading boot script: /Users/clarkbw/src/pi/tmp/server/boot/authentication.js
Error: Cannot find module 'stuff'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at Module.module.__proto__.require (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/agent.js:237:42)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/clarkbw/src/pi/tmp/server/boot/authentication.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
/Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/lib/executor.js:250
      throw err;
            ^
Error: Cannot find module 'stuff'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at Module.module.__proto__.require (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/agent.js:237:42)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/clarkbw/src/pi/tmp/server/boot/authentication.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
And now that I'm testing it all again I can see that we probably shouldn't have included that stack trace since it is duplicated from the throw.  :facepunch:

But we get the file responsible instead of just line in the executor code where it threw.

For the record bad code looks like this:

```javascript
module.exports = function enableAuthentication(server) {
  // enable authentication
  throw new Error('do we crash on code?');
  server.enableAuth();
};
```
And creates an easy error message like this:
```
/Users/clarkbw/src/pi/tmp/server/boot/authentication.js:5
  throw new Error('do we crash on code?');
        ^
Error: do we crash on code?
    at Object.enableAuthentication [as func] (/Users/clarkbw/src/pi/tmp/server/boot/authentication.js:5:9)
    at /Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/lib/executor.js:264:9
    at iterate (/Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/node_modules/async/lib/async.js:165:9)
    at runScripts (/Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/lib/executor.js:254:9)
    at runBootScripts (/Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/lib/executor.js:311:3)
    at /Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/lib/executor.js:40:7
    at /Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/node_modules/async/lib/async.js:610:21
    at /Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/node_modules/async/lib/async.js:249:17
    at iterate (/Users/clarkbw/src/pi/tmp/node_modules/loopback-boot/node_modules/async/lib/async.js:149:13)
```
