### ISSUE TITLE
Failed Login Attempt Response is 500 Error

### ISSUE THREAD

**Issue by arlaneenalra** [strongloop/loopback#118]
Shouldn't this be something in the 400 series (i.e. bad request?) rather than a 500 (Internal Server Error?)

```
csalch@Chriss-MacBook-Air ~/bug-test $ curl -X POST -d '{"email":"garbage", "password":"bad" }' http://localhost:3000/api/users/login
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "must provide username or email",
    "stack": "Error: must provide username or email\n    at Function.User.login (/Users/csalch/bug-test/node_modules/loopback/lib/models/user.js:138:15)\n    at SharedMethod.invoke (/Users/csalch/bug-test/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:131:17)\n    at HttpContext.invoke (/Users/csalch/bug-test/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:221:12)\n    at /Users/csalch/bug-test/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:416:9\n    at execStack (/Users/csalch/bug-test/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:287:7)\n    at /Users/csalch/bug-test/node_modules/loopback/lib/application.js:177:13\n    at /Users/csalch/bug-test/node_modules/loopback/lib/models/acl.js:445:17\n    at /Users/csalch/bug-test/node_modules/loopback/lib/models/acl.js:408:19\n    at /Users/csalch/bug-test/node_modules/loopback/node_modules/async/lib/async.js:229:13\n    at /Users/csalch/bug-test/node_modules/loopback/node_modules/async/lib/async.js:116:25"
  }
}
```

**Comment by rkmax** [comment]
I have the same problem. I'm using version 2.14.0. I have a Model without properties using `User` as base.

When I do a POST to /api/Model/login
```
{"email": "me@example.com", "password": "password", "ttl": 1209600000}
```
I get

```
{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "login failed",
    "statusCode": 401,
    "code": "LOGIN_FAILED",
    "stack": "Error: login failed\n    at /home/julian/Development/example/node_modules/loopback/common/models/user.js:204:26\n    at /home/julian/Development/example/node_modules/loopback-datasource-juggler/lib/dao.js:1352:5\n    at allCb (/home/julian/Development/example/node_modules/loopback-datasource-juggler/lib/dao.js:1291:7)\n    at PostgreSQL.<anonymous> (/home/julian/Development/example/node_modules/loopback-connector-postgresql/lib/postgresql.js:741:7)\n    at null.<anonymous> (/home/julian/Development/example/node_modules/loopback-connector-postgresql/lib/postgresql.js:133:7)\n    at null.<anonymous> (/home/julian/Development/example/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)\n    at bound (domain.js:254:14)\n    at runBound (domain.js:267:12)\n    at Query.handleReadyForQuery (/home/julian/Development/example/node_modules/loopback-connector-postgresql/node_modules/pg/lib/query.js:80:10)\n    at null.<anonymous> (/home/julian/Development/example/node_modules/loopback-connector-postgresql/node_modules/pg/lib/client.js:158:19)"
  }
}
```

**Comment by Amir-61** [comment]
I believe this has been solved in the newer version; I just tried on version 2.22.0 when I use bad email/password, I get the right HTTP status code which is 401.
```
{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "login failed",
    "statusCode": 401,
    "code": "LOGIN_FAILED"
  }
}
```

Since this has already been solved I will be closing this ticket.

Thanks!

**Comment by Amir-61** [comment]
Since this issue seems has been resolved in the newer versions and no activity for a long time, I'm closing this ticket now.

Thanks!
