### ISSUE TITLE
Error: Can't set headers after they are sent. calling confirm user

### ISSUE THREAD

**Issue by AaronBedward** [strongloop/loopback#1204]
Hey guys,

I'm using mocha and supertest to create functional tests. Below is a copy of the test.

	it("should verify user POST /api/User/confirm", function (done) {
		app.models.Users.findById(userId, function (err, usr) {
			json('get', '/api/user/confirm?uid=' + userId + '&token=' + usr.verificationToken)
			.expect(204,done);
		});
	});

However this test returns : 

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/node_modules/loopback-explorer/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.header (/node_modules/loopback/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/node_modules/loopback/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/node_modules/loopback/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/node_modules/loopback/node_modules/express/lib/response.js:142:21)
    at defaultHandler (/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:379:11)
    at restErrorHandler (/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:348:14)
    at Layer.handle_error (/node_modules/loopback/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/node_modules/loopback/node_modules/express/lib/router/index.js:300:13)
    at /node_modules/loopback/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/node_modules/loopback/node_modules/express/lib/router/index.js:321:12)
    at next (/node_modules/loopback/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle_error (/node_modules/loopback/node_modules/express/lib/router/layer.js:54:12)
    at trim_prefix (/node_modules/loopback/node_modules/express/lib/router/index.js:300:13)
    at /node_modules/loopback/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/node_modules/loopback/node_modules/express/lib/router/index.js:321:12)
    at Object.next (/node_modules/loopback/node_modules/express/lib/router/index.js:261:10)
    at Object. (/node_modules/loopback/node_modules/express/lib/router/index.js:603:15)
    at Object. (/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
    at Object.immediate._onImmediate (timers.js:363:16)
    at processImmediate as _immediateCallback

I'm using the latest version of loopback at this point.  Can anybody point me in the right direction?

**Comment by superkhau** [comment]
@AaronBedward Are you still running into this issue?

**Comment by loay** [comment]
Hi @AaronBedward ,

Still running into the same issue? If so, please make sure you are using the most recent version of loopback and if issue is still persisting, please feel free to leave a comment with a repo to reproduce the issue. Thanks.
