### ISSUE TITLE
Cannot use falsy passwords

### ISSUE THREAD

**Issue by mirow** [strongloop/loopback#1210]
I created a new user without a password, and it was stored in the database without problems (the password field was null in the database). Trying to read the user from the database proved to be impossible in some cases, as ModelConstructor calls UserModel.setter.password which throws an error when there is a falsy password.
Here's the offending line:
https://github.com/strongloop/loopback/blob/master/common/models/user.js#L500

Also, I think a user cannot login with a falsy password:
https://github.com/strongloop/loopback/blob/master/common/models/user.js#L291

Stack trace:

Error: Invalid password: null
    at Function.User.validatePassword (/node_modules/loopback/common/models/user.js:474:16)
    at Function.User.hashPassword (/node_modules/loopback/common/models/user.js:465:10)
    at ModelConstructor.UserModel.setter.password (/node_modules/loopback/common/models/user.js:493:41)
    at ModelConstructor.Object.defineProperty.set [as password] (/node_modules/loopback-datasource-juggler/lib/model-builder.js:411:43)
    at ModelConstructor.ModelBaseClass._initProperties (/node_modules/loopback-datasource-juggler/lib/model.js:156:17)
    at ModelConstructor.ModelBaseClass (/node_modules/loopback-datasource-juggler/lib/model.js:44:8)
    at ModelConstructor (/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)
    at ModelConstructor (/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)
    at ModelConstructor (/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)
    at new ModelConstructor (/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)

**Comment by ritch** [comment]
We don't support this yet. I'm not sure how you were able to create a user without a password. IMO this is the main issue:

> I created a new user without a password, and it was stored in the database without problems

You should get a validation error.

Being able to create users without passwords is a feature you would like? Perhaps you could start a discussion (or chime in on an existing discussion) in a separate issue and we can use this to track fixing the first part (being able to create a user without a password).

**Comment by mirow** [comment]
Ah, I've extended the built-in User model, and made the password not required. So that isn't supported?

```
{
  "name": "Person",
  "base": "User",
  "idInjection": false,
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "generated": true
    },
    "password": {
      "type": "string",
      "required": false,
      "postgresql": {
        "dataType": "text"
      }
    },
    ...
```

I understand it's a bit unorthodox to have an optional password...

**Comment by superkhau** [comment]
@mirow Is this still an issue for you?

**Comment by mirow** [comment]
We circumvented the problem by implementing our own hashPassword() and validatePassword() functions, so it's not a problem for us.

**Comment by superkhau** [comment]
The latest loopback returns 404 when you create a user with out a password. Closing.
