### ISSUE TITLE
MySQL-connector throwing "ECONNREFUSED"

### ISSUE THREAD

**Issue by Jondeen** [strongloop/loopback#1281]
Running arc on a fresh setup and adding a mysql datasource causes the following error stack to emerge:

```
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
    --------------------
    at Protocol._enqueue (~/nt/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (~/nt/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (~/nt/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:109:18)
    at Pool.getConnection (~/nt/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:45:23)
    at MySQL.query (~/nt/node_modules/loopback-connector-mysql/lib/mysql.js:167:10)
    at MySQL.<anonymous> (~/nt/node_modules/loopback-connector-mysql/lib/mysql.js:134:12)
    at DataSource.g (events.js:180:16)
    at DataSource.emit (events.js:92:17)
    at DataSource.postInit (~/nt/node_modules/loopback-datasource-juggler/lib/datasource.js:310:14)
    at ~/nt/node_modules/loopback-connector-mysql/lib/mysql.js:89:17
```

The server is accessible with other sql-clients.
Please let me know if other details are required. I'm fairly new to loopback, however the same error appears on fresh installs, regardless of globally vs. locally installed packages, node- and npm versions...

```
loopback-connector-mysql@1.7.0 node_modules/loopback-connector-mysql
├── sl-blip@1.0.0
├── loopback-connector@1.2.1
├── async@0.9.0
├── debug@2.1.3 (ms@0.7.0)
└── mysql@2.6.1 (require-all@1.0.0, bignumber.js@2.0.5, readable-stream@1.1.13)

loopback@2.15.0 node_modules/loopback
├── sl-blip@1.0.0
├── uid2@0.0.3
├── nodemailer-stub-transport@0.1.5
├── stable@0.1.5
├── canonical-json@0.0.4
├── depd@1.0.0
├── inflection@1.7.0
├── async@0.9.0
├── debug@2.1.3 (ms@0.7.0)
├── loopback-phase@1.2.0
├── loopback-connector-remote@1.0.3
├── bcryptjs@2.1.0
├── ejs@2.3.1
├── underscore.string@3.0.3
├── continuation-local-storage@3.1.4 (emitter-listener@1.0.1, async-listener@0.5.1)
├── body-parser@1.12.2 (content-type@1.0.1, bytes@1.0.0, raw-body@1.3.3, qs@2.4.1, on-finished@2.2.0, type-is@1.6.1, iconv-lite@0.4.7)
├── express@4.12.3 (merge-descriptors@1.0.0, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, cookie@0.1.2, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.2, content-type@1.0.1, vary@1.0.0, parseurl@1.3.0, finalhandler@0.3.4, content-disposition@0.5.0, serve-static@1.9.2, path-to-regexp@0.1.3, on-finished@2.2.0, qs@2.4.1, proxy-addr@1.0.7, etag@1.5.1, send@0.12.2, accepts@1.2.5, type-is@1.6.1)
├── nodemailer@1.3.2 (nodemailer-direct-transport@1.0.2, nodemailer-smtp-transport@1.0.2, buildmail@1.2.2, hyperquest@1.0.1, libmime@0.1.7)
└── strong-remoting@2.15.0 (eventemitter2@0.4.14, qs@2.4.1, js2xmlparser@0.1.9, traverse@0.6.6, request@2.55.0, jayson@1.2.0, xml2js@0.4.6)

loopback-datasource-juggler@2.23.0 node_modules/loopback-datasource-juggler
├── depd@1.0.0
├── inflection@1.7.0
├── node-uuid@1.4.3
├── qs@2.4.1
├── async@0.9.0
├── debug@2.1.3 (ms@0.7.0)
├── loopback-connector@1.2.1
└── traverse@0.6.6

strongloop@3.0.4 /usr/local/lib/node_modules/strongloop
├── sl-blip@1.0.0
├── which@1.0.9
├── ini@1.3.3
├── async@0.9.0
├── read@1.0.5 (mute-stream@0.0.4)
├── nopt@3.0.1 (abbrev@1.0.5)
├── debug@2.1.3 (ms@0.7.0)
├── colors@1.0.3
├── is2@0.0.13 (deep-is@0.1.2)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── fs.extra@1.2.1 (mkdirp@0.3.5, fs-extra@0.6.4, walk@2.2.1)
├── json-file-plus@2.0.0 (is@2.0.2, node.extend@1.1.3, promiseback@2.0.1)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, utile@0.2.1, winston@0.8.3)
├── strong-agent@1.3.2 (strong-license@1.0.2, semver@2.2.1)
├── strong-deploy@1.1.6 (strong-url-defaults@1.0.0, posix-getopt@1.1.0, shelljs@0.3.0, concat-stream@1.4.8, strong-tunnel@1.1.1)
├── strong-registry@1.1.4 (osenv@0.0.3, commander@2.7.1, semver@2.3.2, rimraf@2.3.2, bluebird@1.2.4, inquirer@0.4.1)
├── strong-supervisor@1.4.1 (dotenv@0.2.8, posix-getopt@1.1.0, strong-control-channel@1.1.2, strong-statsd@2.0.2, heapdump@0.2.10, strong-fork-syslog@1.2.3, strong-npm-ls@1.0.5, strong-cluster-control@2.0.1, strong-log-transformer@1.0.1)
├── strong-build@1.0.3 (posix-getopt@1.1.0, shelljs@0.3.0, json-file-plus@1.0.7, vasync@1.6.3, lodash@2.4.1)
├── strong-start@1.0.3 (osenv@0.1.0, posix-getopt@1.1.0, lodash@3.6.0)
├── node-inspector@0.7.4 (opener@1.3.0, debug@0.8.1, async@0.8.0, rc@0.3.5, strong-data-uri@0.1.1, yargs@1.2.6, glob@3.2.11, express@4.0.0, ws@0.4.32)
├── strong-pm@3.1.9 (uid-number@0.0.5, chownr@0.0.1, osenv@0.1.0, npm-path@1.0.1, strong-url-defaults@1.0.0, extsprintf@1.3.0, posix-getopt@1.1.0, passwd-user@1.1.1, serve-favicon@2.2.0, mkdirp@0.5.0, bl@0.9.4, concat-stream@1.4.8, strong-service-install@1.1.2, strong-fork-cicada@1.1.2, errorhandler@1.3.5, compression@1.4.3, strong-control-channel@1.1.2, express@4.12.3, lodash@2.4.1, tar@1.0.3, strong-npm-ls@1.0.5, strong-tunnel@1.1.1, http-auth@2.2.5, strong-mesh-models@5.0.1)
├── generator-loopback@1.9.0 (inflection@1.7.0, chalk@0.5.1, yosay@1.0.3, request@2.55.0, loopback-swagger@2.0.0, yeoman-generator@0.18.10, loopback-workspace@3.10.1)
├── loopback-sdk-angular-cli@1.1.4 (semver@2.3.2, loopback-sdk-angular@1.3.7, express@3.20.2, docular@0.6.6)
└── strong-arc@1.1.0 (opener@1.4.1, cookie-parser@1.3.4, split@0.3.3, http-proxy@1.10.1, serve-favicon@2.2.0, errorhandler@1.2.4, ws@0.4.32, express@4.8.8, fs-extra@0.14.0, request@2.55.0, loopback-boot@2.6.5, loopback-datasource-juggler@2.23.0, express-jsxtransform@1.1.0, loopback@2.15.0, loopback-workspace@3.10.1, strong-mesh-client@1.4.0, strong-pm@1.7.3)
```

**Comment by Jondeen** [comment]
Turns out there was a mixup of IPs and an old hosts file making my Easter miserable. Sorry for bothering!
