### ISSUE TITLE
Cannot install strongloop with npm without errors thrown during intallation

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#1297]
When I try to install Strongloop on Windows 8.1  many errors are thrown. Eventually it is installed and "slc loopback" works. But what do all those errors mean? Why it happens? Do they lead to errors someday in my app?

Here is the result of `$ npm install -g strongloop`:
```
C:\Users\user>npm install -g strongloop
npm WARN optional dep failed, continuing strong-fork-syslog@1.2.3
\

> heapdump@0.2.10 install C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-supervisor\node_modules\heapdu
mp
> node-gyp rebuild

|
C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-supervisor\node_modules\heapdump>node "C:\Program Files\
nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-supervisor\node_modules\heapdump
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing heapdump@0.2.10
\

> strong-agent@1.4.0 install C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent
> node-gyp rebuild || exit 0

C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent>node "C:\Program Files\nodejs\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
/


> ws@0.4.32 install C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\node-inspector\node_modules\ws>node "C:\Program Files\nodejs\no
de_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
\


> ws@0.4.32 install C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\ws>node "C:\Program Files\nodejs\node_m
odules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
\



> ws@0.5.0 install C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\n
ode_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\node_modules\engine.
io\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild


C:\Users\user\AppData\Roaming\npm\slc -> C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\bin\slc
C:\Users\user\AppData\Roaming\npm\lb-ng -> C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angul
ar-cli\bin\lb-ng
C:\Users\user\AppData\Roaming\npm\lb-ng-doc -> C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-a
ngular-cli\bin\lb-ng-doc
strongloop@3.0.5 C:\Users\user\AppData\Roaming\npm\node_modules\strongloop
├── sl-blip@1.0.0
├── which@1.0.9
├── ini@1.3.3
├── async@0.9.0
├── read@1.0.5 (mute-stream@0.0.4)
├── nopt@3.0.1 (abbrev@1.0.5)
├── colors@1.0.3
├── debug@2.1.3 (ms@0.7.0)
├── is2@0.0.13 (deep-is@0.1.2)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── fs.extra@1.2.1 (mkdirp@0.3.5, walk@2.2.1, fs-extra@0.6.4)
├── json-file-plus@2.0.0 (is@2.0.2, node.extend@1.1.3, promiseback@2.0.1)
├── strong-agent@1.4.0 (strong-license@1.0.2, semver@2.2.1)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, winston@0.8.3, utile@0.2.1)
├── strong-build@1.0.3 (posix-getopt@1.1.0, shelljs@0.3.0, json-file-plus@1.0.7, vasync@1.6.3, lodash@2.4.1)
├── strong-deploy@1.1.6 (strong-url-defaults@1.0.0, posix-getopt@1.1.0, shelljs@0.3.0, concat-stream@1.4.8, strong-tunnel@1.1.1)
├── strong-registry@1.1.4 (osenv@0.0.3, semver@2.3.2, commander@2.7.1, bluebird@1.2.4, rimraf@2.3.2, inquirer@0.4.1)
├── strong-pm@3.1.9 (uid-number@0.0.5, chownr@0.0.1, osenv@0.1.0, npm-path@1.0.1, strong-url-defaults@1.0.0, extsprintf@1.3.0, posix-get
opt@1.1.0, passwd-user@1.1.1, mkdirp@0.5.0, serve-favicon@2.2.0, bl@0.9.4, strong-service-install@1.1.2, concat-stream@1.4.8, errorhandl
er@1.3.5, strong-fork-cicada@1.1.2, compression@1.4.3, strong-control-channel@1.1.2, express@4.12.3, lodash@2.4.1, tar@1.0.3, strong-npm
-ls@1.0.5, strong-tunnel@1.1.1, http-auth@2.2.5)
├── strong-start@1.0.3 (osenv@0.1.0, posix-getopt@1.1.0, lodash@3.6.0)
├── nodefly-register@0.3.3
├── strong-supervisor@1.4.1 (dotenv@0.2.8, posix-getopt@1.1.0, strong-control-channel@1.1.2, strong-statsd@2.0.2, strong-npm-ls@1.0.5, s
trong-cluster-control@2.0.1, strong-log-transformer@1.0.1)
├── node-inspector@0.7.4 (opener@1.3.0, debug@0.8.1, async@0.8.0, rc@0.3.5, strong-data-uri@0.1.1, yargs@1.2.6, glob@3.2.11, ws@0.4.32,
express@4.0.0)
├── strong-mesh-models@5.0.1 (user-home@1.1.1, osenv@0.1.0, sprintf@0.1.5, strong-url-defaults@1.0.0, posix-getopt@1.1.0, serve-favicon@
2.2.0, concat-stream@1.4.8, errorhandler@1.3.5, compression@1.4.3, strong-npm-ls@1.0.5, strong-tunnel@1.1.1, request@2.55.0, loopback-bo
ot@2.6.5, loopback-datasource-juggler@2.23.0, lodash@3.6.0, loopback@2.15.0, loopback-explorer@1.7.2)
├── generator-loopback@1.9.0 (inflection@1.7.0, chalk@0.5.1, yosay@1.0.3, request@2.55.0, loopback-swagger@2.0.0, yeoman-generator@0.18.
10, loopback-workspace@3.10.1)
├── loopback-sdk-angular-cli@1.1.4 (semver@2.3.2, loopback-sdk-angular@1.3.7, express@3.20.2, docular@0.6.6)
└── strong-arc@1.1.0 (opener@1.4.1, split@0.3.3, cookie-parser@1.3.4, http-proxy@1.10.1, serve-favicon@2.2.0, ws@0.4.32, express@4.8.8,
fs-extra@0.14.0, errorhandler@1.2.4, loopback-boot@2.6.5, loopback-datasource-juggler@2.23.0, request@2.55.0, express-jsxtransform@1.1.0
, loopback@2.15.0, strong-mesh-client@1.4.0, strong-pm@1.7.3, loopback-workspace@3.10.1)
```

**Comment by hellsan631** [comment]
The reason for the errors is right here:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-
```

Its an error that's caused when building one of the dependencies, node_gyp.

I would take a look at the windows installation instructions for [node_gyp](https://github.com/TooTallNate/node-gyp), which has instructions on what is needed. From the error, it looks like your going to need to install the recommended version of python, and make sure the python is in your [path variables](https://docs.python.org/2/using/windows.html)

**Comment by ynagarjuna1995** [comment]
I have installed node-gyp through npm and build essentails too Everything on my ubuntu vagrant box is up to date but unable to install strongloop


vagrant@strongloop:~$ sudo npm install -g strongloop
npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile
would not be propagated

> heapdump@0.3.5 install /usr/local/lib/node_modules/strongloop/node_modules/str
ong-supervisor/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/st
rong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  SOLINK_MODULE(target) Release/obj.target/addon.node: Finished
  COPY Release/addon.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/str
ong-supervisor/node_modules/heapdump/build'

> strong-fork-syslog@1.2.3 install /usr/local/lib/node_modules/strongloop/node_m
odules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/st
rong-supervisor/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/obj.target/syslog.node
  SOLINK_MODULE(target) Release/obj.target/syslog.node: Finished

**Comment by superkhau** [comment]
Please post `strongloop` related issues at https://github.com/strongloop/strongloop/issues.

/cc @rmg @sam-github

**Comment by superkhau** [comment]
@wzup Please follow up on this issue at https://github.com/strongloop/loopback/issues/1297.
