### ISSUE TITLE
Polymorphic relation includes result in Uncaught

### ISSUE THREAD

**Issue by seriousben** [strongloop/loopback#1313]
This is new since `loopback-datasource-juggler@2.25.0` The findOne of modelTo is undefined.

```javascript
Uncaught TypeError: undefined is not a function

TypeError: undefined is not a function
    at BelongsTo.related (project/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1401:15)
    at project/node_modules/loopback-datasource-juggler/lib/include.js:199:7
    at project/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (project/node_modules/async/lib/async.js:46:24)
    at Object.async.each (project/node_modules/async/lib/async.js:124:9)
    at processIncludeItem (project/node_modules/loopback-datasource-juggler/lib/include.js:156:11)
    at project/node_modules/loopback-datasource-juggler/lib/include.js:118:5
    at project/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (project/node_modules/async/lib/async.js:46:24)
    at Object.async.each (project/node_modules/async/lib/async.js:124:9)
    at Function.Inclusion.include (project/node_modules/loopback-datasource-juggler/lib/include.js:117:9)
    at project/node_modules/loopback-connector-mongodb/lib/mongodb.js:595:33
    at handleCallback (project/node_modules/mongodb/lib/utils.js:95:12)
    at project/node_modules/mongodb/lib/cursor.js:571:16
    at handleCallback (project/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
    at setCursorDeadAndNotified (project/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
    at Cursor.next (project/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:543:14)
    at fetchDocs (project/node_modules/mongodb/lib/cursor.js:567:10)
    at project/node_modules/mongodb/lib/cursor.js:583:7
    at handleCallback (project/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
    at Cursor.next (project/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:603:5)

```

**Comment by seriousben** [comment]
This is the query I am doing:

```
    Invitation.findOne({
      where: {
        id: invitationId
      },
      include: ['invitee', 'owner', 'invitable']
    })
```

**Comment by raymondfeng** [comment]
Can you provide a link to your github repo that contains a runnable test?

**Comment by seriousben** [comment]
Closing this, the uncaught was caused by a wrong model name in a relation. Correct name was: "Comment" wrong name that was used 'comment'.
