### ISSUE TITLE
slc loopback:model gives error on excluding some properties from base model.

### ISSUE THREAD

**Issue by miteshsondhi** [strongloop/loopback#1325]
```
"base": "User",
"properties": { 
    "credentials": null,
    "challenges": null
}
```
`slc loopback:model` gives -

```
/home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/definition.js:131
        if (relation.model === 'ModelProperty' && !config.type) {
                                                         ^
TypeError: Cannot read property 'type' of null
    at /home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/definition.js:131:58
    at Array.forEach (native)
    at /home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/definition.js:128:32
    at Array.forEach (native)
    at Function.Definition.addRelatedToCache (/home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/definition.js:112:30)
    at /home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/facet.js:114:25
    at Array.forEach (native)
    at /home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/facet.js:103:28
    at /home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/async/lib/async.js:610:21
    at /home/dexter/.nvm/versions/node/v0.12.0/lib/node_modules/strongloop/node_modules/async/lib/async.js:249:17
```

```
"base": "User",
"properties": { 
    "credentials": false,
    "challenges": false
}
```
`slc loopback:model` works fine

**Comment by bajtos** [comment]
Thank you for reporting the problem, it looks like a bug in loopback-workspace to me. We need to update it to support model definitions that are excluding base properties, this feature was introduced recently by https://github.com/strongloop/loopback-datasource-juggler/pull/494.

**Comment by superkhau** [comment]
@miteshsondhi I'm trying to reproduce this. Can you tell me the steps you've taken? I did:

```
slc loopback test
cd test
slc loopback:model
? Enter the model name: user
? Select the data-source to attach user to: db (memory)
? Select model's base class: User
? Expose user via the REST API? Yes
? Custom plural form (used to build REST URL):
Let's add some user properties now.

Enter an empty property name when done.
? Property name: credentials
   invoke   loopback:property
? Property type: (other)
? Enter the type: null
? Required? No
Let's add another user property.

Enter an empty property name when done.
? Property name: challenges
   invoke   loopback:property
? Property type: (other)
? Enter the type: null
? Required? No

Let's add another user property.
Enter an empty property name when done.
? Property name:
```

I get no errors. Can you confirm?
