### ISSUE TITLE
performing upsert being offline doesnt work

### ISSUE THREAD

**Issue by codeyad** [strongloop/loopback#1336]
im trying to make an upsert inside a "before save" but it doesn't work and the server throw me this error:
TypeError: Cannot read property 'userId' of undefined
    at /var/www/html/main/common/models/mymodel.js:223:29
    at notifySingleObserver (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:668:22)
    at iterate (/var/www/html/main/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/var/www/html/main/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:165:9)
    at doNotify (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:665:11)
    at doNotify (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:663:49)
    at doNotify (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:663:49)
    at doNotify (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:663:49)
    at Function.ModelBaseClass._notifyBaseObservers (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:686:5)
    at Function.ModelBaseClass.notifyObserversOf (/var/www/html/main/node_modules/loopback-datasource-juggler/lib/model.js:661:8)

by the way, userId is something im printing in the console and is doing it until i try the upsert and this happen.

**Comment by bajtos** [comment]
Please provide us with full instructions how to reproduce the problem on our machines, ideally a sample app per [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by codeyad** [comment]
ModelExample.observe('before save', function(ctx, next){

//values that im sending through the model  
    var userId = ctx.instance.userId;
    var personalId = ctx.instance.personalId;

    ModelExample.findOne({where:{personalId:personalId}},function(err1, succ){
      if (succ && userId) {
        ModelExample.upsert({id:succ.id, userId:userId}, function(err, succ2){
          
        });
      }
      next();
    });

});

**Comment by codeyad** [comment]
another point i really want to focus in is that im trying to do this being offline (no token) in my app, but when i try it using an "beforeRemote('create', ... " this makes the upsert, even when at the end (i dont know the reason) this gives me an status:500, i expect this can help.

**Comment by bajtos** [comment]
@codeyad I am afraid that I still don't understand what you are trying to achieve from your description. I'll repeat myself, please provide us with full instructions how to reproduce the problem on our machines, ideally a sample app per [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report). We need steps that we can reproduce without the need to figure out where and how to put the various fragments mentioned in your comments above.

**Comment by codeyad** [comment]
i dont really know if this was my bad and that's whats supposed to happen but when i changed the "next()" response status to 500 it was everything fine.

**Comment by bajtos** [comment]
ok, I am closing this issue as resolved then.

BTW, `ctx.instance` is not set for certain operations like `updateAttributes`, in which case you should use `ctx.data` instead. See the [documentation](http://docs.strongloop.com/display/LB/Operation+hooks) for more details.
