### ISSUE TITLE
npm install on git cloned loopback give EJSONPARSE (Windows OS)

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback#1350]
This is probably an issue with my Windows 8.1: but just in case,  issue while I am finding out if it happens on another Windows installation

Windows 8.1: EJSONPARSE
Redhat: no problem 

I found another windows machine (windows server): gave me other problems WorkInProgress

[npm log](http://pastebin.com/MMwMSewE)
[contents of C:\Users\ob_000\AppData\Roaming\npm-cache\loopback-testing\1.1.0\package\package.json](http://pastebin.com/rBLZLzG5)

1336 silly cache afterAdd loopback-testing@1.1.0
1337 verbose afterAdd C:\Users\ob_000\AppData\Roaming\npm-cache\loopback-testing\1.1.0\package\package.json not in flight; writing
1338 verbose afterAdd C:\Users\ob_000\AppData\Roaming\npm-cache\loopback-testing\1.1.0\package\package.json written
1339 verbose stack Error: Failed to parse json
1339 verbose stack Unexpected token  
1339 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:378:25)
1339 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:85:51)
1339 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:59:33
1339 verbose stack     at evalmachine.<anonymous>:336:14
1339 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
1339 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
1340 verbose cwd C:\Users\ob_000\tmp\loopback
1341 error Windows_NT 6.3.9600
1342 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1343 error node v0.12.1
1344 error npm  v2.5.1
1345 error file C:\Users\ob_000\AppData\Roaming\npm-cache\nodemailer\1.3.4\package\package.json
1346 error code EJSONPARSE
1347 error Failed to parse json
1347 error Unexpected token  
1348 error File: C:\Users\ob_000\AppData\Roaming\npm-cache\nodemailer\1.3.4\package\package.json
1349 error Failed to parse package.json data.
1349 error package.json must be actual JSON, not just JavaScript.
1349 error
1349 error This is not a bug in npm.
1349 error Tell the package author to fix their package.json file. JSON.parse
1350 verbose exit [ 1, true ]

**Comment by OwenBrotherwood** [comment]
Closed: if anyone else get's the same, clean the npm
