### ISSUE TITLE
Error: Timeout in connecting after 5000 ms for pg

### ISSUE THREAD

**Issue by transedward** [strongloop/loopback#1383]
g0v/ppt#6

It's weird that tables and all row are already constructed, however when I send request(using explorer):
it got this error, even if it's in localhost
```
{
"error": {
"name": "Error",
"status": 500,
"message": "Timeout in connecting after 5000 ms",
"stack": "Error: Timeout in connecting after 5000 ms\n at [object Object]. (/Users/mac/GitHub/edward_ptt/node_modules/loopback-datasource-juggler/lib/datasource.js:2029:10)\n at [object Object]._onTimeout (/Users/mac/GitHub/edward_ptt/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)\n at Timer.listOnTimeout (timers.js:89:15)"
}
}
```
any possible reason or suggestion?

**Comment by transedward** [comment]
Today, I tired it again.
when I use autoupdate in server/boot/mock-data.js, all the get methods work
but if I change to automigrate, then the same error happens again.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by superkhau** [comment]
Closing due to inactivity. Please open a new issue if you are still having problems.
