### ISSUE TITLE
Error slc loopback:datasource

### ISSUE THREAD

**Issue by samtux** [strongloop/loopback#1403]
I get the next error with slc loopback:datasource command in RH 6.4:

```
$ slc loopback:datasource
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Invalid workspace: no facets found.
    at /usr/lib/node_modules/generator-loopback/node_modules/loopback-workspace/models/workspace.js:282:10
    at allCb (/usr/lib/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler/lib/dao.js:1339:7)
    at /usr/lib/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:371:7
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
```

**Comment by raymondfeng** [comment]
After you scaffold the app, you need to cd into the root dir of your app to run slc loopback:datasource

**Comment by samtux** [comment]
Thanks @raymondfeng.  Effectively the solution was to create the project.

Thank you.
