### ISSUE TITLE
trackChanges does not work with PostgreSQL

### ISSUE THREAD

**Issue by Nutelac** [strongloop/loopback#1414]
When `trackChanges` is `true`, I got error:
```
error: relation "public.program-change" does not exist
    at [object Object].Connection.parseE (.../node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:534:11)
    at [object Object].Connection.parseMessage (.../node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (.../node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

When is `false` or with memory connector, everything works well.

**article.json:**
```json
{
  "name": "Program",
  "base": "PersistedModel",
  "trackChanges": true,
  "options": {
    "postgresql": {
      "schema": "myschema",
      "table": "programs"
    }
  },
  "properties": {
    "id": {
      "id": true,
      "type": "string",
      "defaultFn": "guid",
      "postgresql": {
        "columnName": "id",
        "dataType": "text"
      }
    }
  }
}
```

Is there something that I missed?

**Comment by ritch** [comment]
Did you migrate your database with change tracking enabled?

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by superkhau** [comment]
@Nutelac Closing due to inactivity. Please open a new issue if you are still running into problems.
