### ISSUE TITLE
Error: Cannot GET /apple-touch-icon-precomposed.png

### ISSUE THREAD

**Issue by benmarten** [strongloop/loopback#1463]
When generating a brand new loopback project, then running it results in two initial errors:

    Ben@Bens-MacBook-Pro ~/N/elster> node .
    Browse your REST API at http://0.0.0.0:3000/explorer
    Web server listening at: http://0.0.0.0:3000/
    Error: Cannot GET /apple-touch-icon-precomposed.png
        at raiseUrlNotFoundError (/Users/Ben/NodeProjects/elster/node_modules/loopback/server/middleware/url-not-found.js:15:17)
        at Layer.handle [as handle_request] (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
        at trim_prefix (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:302:13)
        at /Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:270:7
        at Function.proto.process_params (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:321:12)
        at next (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:261:10)
        at /Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:603:15
        at next (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:246:14)
        at Function.proto.handle (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:166:3)
        at router (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:35:12)
    Error: Cannot GET /apple-touch-icon.png
        at raiseUrlNotFoundError (/Users/Ben/NodeProjects/elster/node_modules/loopback/server/middleware/url-not-found.js:15:17)
        at Layer.handle [as handle_request] (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
        at trim_prefix (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:302:13)
        at /Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:270:7
        at Function.proto.process_params (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:321:12)
        at next (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:261:10)
        at /Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:603:15
        at next (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:246:14)
        at Function.proto.handle (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:166:3)
        at router (/Users/Ben/NodeProjects/elster/node_modules/loopback/node_modules/express/lib/router/index.js:35:12)

**Comment by Neil-UWA** [comment]
this is not a issue of loopback, mac os will request icons for your website, if you want to eliminate this error, just put those icon assets under your directory that serves static files.

**Comment by superkhau** [comment]
@benmarten Are you still running into this issue? The error has nothing to do with LoopBack. Are you sure you're scaffolding a new project? Can you provide the steps to reproduce?

**Comment by benmarten** [comment]
yes this is probably a safari issue. in any case it's a little bit weird, when you scaffold the app and already see this error.
Steps to reproduce:

mkdir test
cd test
slc loopback
node .
Visit http://0.0.0.0:3000/ with Safari and see Console.

**Comment by superkhau** [comment]
I've tried to reproduce it, I get no error messages in my Safari `Version 8.0.7 (10600.7.12)`. It's probably something to do with your setup. Please try on a different machine and reopen this issue if you are still having problem. Closing for now.
