### ISSUE TITLE
afterRemote on 'login' Error - extended User model

### ISSUE THREAD

**Issue by vasumahesh1** [strongloop/loopback#1490]
I basically made my own `AppUser` Model from `User` as a base.

This is how it looks like:
```
{
	"name": "AppUser",
	"base": "User",
	"idInjection": true,
	"options": {
		"validateUpsert": true
	},
	"properties": {
		"accountType": {
			"type": "string",
			"required": true
		},
		"loginMethod": {
			"type": "string",
			"required": true
		}
	},
	"validations": [],
	"relations": {
		"profile": {
			"type": "embedsOne",
			"model": "Profile",
			"property": "userProfile"
		}
	},
	"acls": [
	{
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "register"
    }],
	"methods": []
}
```

Now I wanted to Include `userProfile` in my response for `login` Remote Hook at the same time using the User.login base login method.
```js
AppUser.afterRemote('login', function (ctx, next) {
		console.log(ctx.result);
		AppUser.findById(ctx.result.userId, function (err, appUserObject) {
			if (err === null) {
				ctx.result.userProfile = appUserObject.userProfile;
			}
			next();
		});
	});
```

So I added this and got this error on Login, as you can see I clearly got my ctx.result... but after that I got this weird mongo error:
```
Browse your REST API at http://localhost:3000/explorer
Web server listening at: http://localhost:3000/
{ ttl: 1209600,
  userId: 558f1965ff6bc8e57000db02,
  created: Sun Jun 28 2015 16:47:03 GMT+0630 (India Standard Time),
  id: 'KwgRt3KDL0a56TEIrkTpubRepYVOh55H3oqTPdkruz4wU2UYeltPcweKbojMAp8w' }
P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\lib\utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: object is not a function
    at P:\schoolu\server_workbench\schoolu\common\models\app-user.js:85:4
    at P:\schoolu\server_workbench\schoolu\node_modules\loopback-datasource-juggler\lib\dao.js:1443:5
    at allCb (P:\schoolu\server_workbench\schoolu\node_modules\loopback-datasource-juggler\lib\dao.js:1374:7)
    at P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\lib\mongodb.js:713:9
    at handleCallback (P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\lib\utils.js:95:12)
    at P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\lib\cursor.js:590:16
    at handleCallback (P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:234:5)
    at setCursorDeadAndNotified (P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:433:3)
    at nextFunction (P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:553:12)
    at Cursor.next [as _next] (P:\schoolu\server_workbench\schoolu\node_modules\loopback-connector-mongodb\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:629:3)

```

Pretty new here. Any Help? Or is there any alternative to get this embedded `userProfile`...

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by vasumahesh1** [comment]
Sure on it ... Will update you soon

**Comment by bachirelkhoury** [comment]
@vasumahesh1 you're getting this error because the second parameter is the 'result' object and not a function. You are missing missing an argument, your method should be:

     AppUser.afterRemote('login', function (ctx, result, next) {
         // the rest of the code
         next();
     });

**Comment by vasumahesh1** [comment]
@bachirelkhoury Okay I will try it soon, I found a work around for this issue so, Never really got the time to go back to this. Should I close this Issue?

**Comment by superkhau** [comment]
Closing this issue as it seems like it's an application error. @vasumahesh1 Please ping again if you want this reopened.
