### ISSUE TITLE
intermittent getCurrentContext === null on windows

### ISSUE THREAD

**Issue by digitalsadhu** [strongloop/loopback#1505]
We are using getCurrentContext reliably to pass the user around in our mac development environment. We are attempting to deploy to windows server 2012. I can refresh an api endpoint that uses getCurrentContext and see it flick back and forth between correct behaviour and a can't call get on null getCurrentContext error.

We have tried:
node 0.10.39
node 0.12.6

loopback 2.14 -> 2.18

Running npm update to update deps

Wipe and reinstall node_modules
reinstall app entirely

NODE_ENV=development and NODE_ENV=production 

Some debugging revealed that the context is always present but ns.active alternates between incorrect with an empty object:

``` js
 { name: 'loopback',
  active: {},
  _set: [ null, {} ],
  id:
   { create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 1,
     data: null } }
```

and correct with user object:

``` js
 { name: 'loopback',
  active: { user: { name: 'bob', group: 'managers', department: 1 } },
  _set: [ null, { user: [Object] } ],
  id:
   { create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 1,
     data: null } }
```

User object is set into context in server.js

``` js
app.use(loopback.context());

app.use(function (req, res, next) {
  var ctx = loopback.getCurrentContext();
  ctx.set('user', { name: 'bob', group: 'managers', department: 1 });
  next();
});
```

And will show up in subsequent middleware, not so in boot scripts and intermittently elsewhere such as model before save hooks

We have a boot script server/boot/script.js

``` js
var loopback = require('loopback');
var roles = require('../ldapconfig.json').roles;

module.exports = function loadAdditionalScripts(app) {
  var Role = app.models.Role;

  Object.keys(roles).forEach(function (appRole) {
    Role.registerResolver(appRole, function(role, context, cb) {
      return cb(null, loopback.getCurrentContext().get('user').group === roles[appRole]);
    });
  });
};
```

This always works on our macs, but does not work on windows at all. My initial fix for this was to move this code back into a middleware in server.js. This helped but I then got stuff in model hooks.

A single call to getCurrentContext in a model.observe seems to work some of the time but odd effects seem to occur if multiple handlers for the same event are used. eg:

``` js
Contract.observe('access', function (ctx, next) {
    var user = loopback.getCurrentContext().get('user');
    //often works here
    ...
    next();
  });

Contract.observe('access', function (ctx, next) {
    var user = loopback.getCurrentContext().get('user');
    //user is usually null here
    ...
    next();
  });
```

I would appreciate any help in diagnosing the issue. Even just some leads/ideas to follow up on would be great. 

Thanks.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by matt-in-a-hat** [comment]
@superkhau thanks in advance for looking at this.
Test project: https://github.com/mediasuitenz/loopback-sandbox
STR
- Clone on windows
- Update `server/datasource.json` to connect to an MSSQL instance
- Try GET contracts from http://localhost:8000/api/contracts or through the explorer
-- `loopback.getCurrentContext()` seems to fail in `server/boot/script.js`
- To get around that error and see it fail in the model, checkout the branch `other_use_case`
- Try GET contracts
-- `loopback.getCurrentContext()` seems to fail in `common/models/contract.js`. See stack trace below.

```
TypeError: Cannot call method 'get' of null
at restrictGroup (loopback-sandbox\common\models\contract.js:8:45)
at notifySingleObserver (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:98:22)
at iterate (loopback-sandbox\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:181:13)
at Object.async.eachSeries (loopback-sandbox\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:197:9)
at doNotify (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:95:11)
at doNotify (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:93:49)
at doNotify (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:93:49)
at doNotify (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:93:49)
at Function.ObserverMixin._notifyBaseObservers (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:116:5)
at Function.ObserverMixin.notifyObserversOf (loopback-sandbox\node_modules\loopback-datasource-juggler\lib\observer.js:91:8)
```

I have noticed that this only seems to fail while using the `mssql` connector. Using a `memory` db doesn't have this issue (on windows or mac) and using `mysql` on mac doesn't have this issue.

**Comment by digitalsadhu** [comment]
In light of the fact that this seems to be mssql connector related, should we move the issue there or is it fine here @superkhau ?

**Comment by bkniffler** [comment]
Postgres also fails on this on windows.

**Comment by bkniffler** [comment]
Postgres on windows has the exact same issue.

**Comment by digitalsadhu** [comment]
It's actually beginning to look to me like a port issue. I don't understand why yet but when I restart the process, this null context error starts, if I update the port to something else, the issue seems to go away again until process restart.

**Comment by rh389** [comment]
I'm seeing this on on a mac (and linux) using the mongodb connector. Not sure whether it's the same bug but it looks like the same symptoms - test project here: https://github.com/rh389/loopback-context-bug (the two supertest tests illustrate the issue)

**Comment by digitalsadhu** [comment]
How can we progress this issue? We are still seeing this issue.

**Comment by digitalsadhu** [comment]
@superkhau Is there anything we can do to provide additional information or progress this in any way?

**Comment by superkhau** [comment]
>Is there anything we can do to provide additional information or progress this in any way?

@raymondfeng ^ Maybe we can get @cgole to reproduce on a Windows machine?

**Comment by beaglez** [comment]
Experiencing the same issue intermittently. On a mac connecting to a PostgreSQL database, so seems like this is not isolated to Windows/MSSQL.

**Comment by beaglez** [comment]
Looks like this is occurring because of getCurrentContext's dependence on cls - see strongloop/loopback#1495 for a workaround.

**Comment by bajtos** [comment]
I am closing this issue since there was no activity in more than a year.

Please see https://github.com/strongloop/loopback/issues/1495 for the new "official" way for propagating current context.

You can also try the new https://github.com/strongloop/loopback-context and see if it works in your app. If you do, then please report any issues to loopback-context's issue tracker.
