### ISSUE TITLE
Can not access properties of instance that is going to be deleted in before delete and after delete hook 

### ISSUE THREAD

**Issue by lengyueChen** [strongloop/loopback#1529]
Hi 
I have a model called Environment and it has a property named instance_ids which is an array of string to store ids of the instances, which are virtual machines on my cluster.

I need to grab the virtual machine ids and pass them as arguments into a python script to perform shut down action on those virtual machine which are going to be deleted. Below is my code in the hook:

Environment.observe('before delete', function(ctx, next){
    //get all virtual machine id in this environment
    var ids = ctx.instance.instance_ids;
    if(ids.length>0){
      var instance_id_string = "--"
      for (var i = 0;i<ids.length;i++){
        instance_id_string+=ids[i];
        instance_id_string+="?";
      }
      console.log('in delete hook:'+instance_id_string);
    }
    //execute the script
    var exec = require('child_process').exec,child;
    child = exec('python delete_lab.py '+instance_id_string);
    next();
  });

The error msg is :
/home/lchen95/Desktop/nds-webservice/common/models/environment.js:64
    var ids = ctx.instance.instance_ids;
                          ^
TypeError: Cannot read property 'instance_ids' of undefined

According to the documentation , I should be able to retrieve the property of the instance being deleted but ctx.instance is undefined in this case. Is there any other way for me to access the property of the instance? Many thanks.

**Comment by raymondfeng** [comment]
What delete method do you use? Check ctx.currentInstance.

**Comment by lengyueChen** [comment]
/home/lchen95/Desktop/nds-webservice/common/models/environment.js:64
    var ids = ctx.currentInstance.instance_ids;
                                 ^
TypeError: Cannot read property 'instance_ids' of undefined

It is still undefined. the doc said ctx.instance should be available in before delete hook.
http://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-beforedelete

The delete method I used is the default one in the CRUD method.

**Comment by lengyueChen** [comment]
Below is the version info:

strongloop v4.0.5 (node v0.12.6)
├── strong-arc@1.6.0 (cfb2378)
├── strong-build@2.0.3 (b66d030)
├── strong-deploy@2.2.2 (13baab4)
├── strong-pm@4.3.1 (45d254a)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.2.0 (e59f8b5)
├─┬ strong-supervisor@2.0.2 (610a578)
│ └── strong-agent@1.6.3
├── generator-loopback@1.10.1 (eae270c)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

I tried to reproduce this error by creating a new application with one model called TestModel and it has one property 'size'. 
Below is the code in test-model.js

module.exports = function(TestModel) {
	TestModel.observe('before delete', function(ctx, next){ 
        var size = ctx.instance.size;
        console.log(size);
       next();
       });
};

Below is the same error of undefined in instance I got:
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "Cannot read property 'size' of undefined",
    "stack": "TypeError: Cannot read property 'size' of undefined\n    at /home/lchen95/Desktop/tes/common/models/test-model.js:4:28\n    at notifySingleObserver (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:98:22)\n    at iterate (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:181:13)\n    at Object.async.eachSeries (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:197:9)\n    at doNotify (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:95:11)\n    at doNotify (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at doNotify (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at doNotify (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at Function.ObserverMixin._notifyBaseObservers (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)\n    at Function.ObserverMixin.notifyObserversOf (/home/lchen95/Desktop/tes/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)"
  }
}

**Comment by gunjpan** [comment]
@lengyueChen: Hi, could you please advise if you're still facing this issue. If yes, can you please provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues.

**Comment by gunjpan** [comment]
Closing this issue due to inactivity. If you are still running into problems, feel free to leave a comment and I will reopen the issue.
