### ISSUE TITLE
Automated tests using Tape importing `server.js` get "Pool is closed" after first test teardown

### ISSUE THREAD

**Issue by mikesparr** [strongloop/loopback#1547]
Thanks so much for your help thus far. Using `tape` and `supertest` we solved why the tests would "hang" in #1538 and solution was to explicitly call `.disconnect()` on the datasources in teardown. This works for individual tests, however when multiple tests are run in the suite, the next test cannot get database connection and complains "Pool is closed".

Since I `var app = require('../../../../server');` in each test, I would expect the connections to reset even though prior test I disconnect them in teardown.

**my.test.js (imports at top)**
~~~
var test = require('tape');
var sinon = require('sinon');
var app = require('../../../server/server');
var request = require('supertest');
var restApiRoot = app.get('restApiRoot');

// change these
var model = app.models.<model_to_test>;
~~~

**my.test.js (teardown at bottom)**
~~~
// teardown
test(apiPath + ' functional tests teardown', function(t) {
    //t.comment('closing Redis...');
    // end Redis connection
    app.dataSources.redis2Ds.disconnect(function() {
        //t.comment('closed redis2');
        app.dataSources.redis1Ds.disconnect(function() {
            //t.comment('closed redis1');
            app.dataSources.mysqlDs.disconnect(function() {
               //t.comment('closed mysql');
               t.end(); 
            });
        });
    });
});
~~~

At the top of every test I import the `server/server.js` and expect it to run like any other but instead I get the following errors for all subsequent tests if run in serial:
~~~
  not ok 59 Error: Pool is closed.
    ---
      operator: error
      expected: undefined
      actual:   [Error: Pool is closed.]
      at: createCallback (/Users/mike/Work/identity-service/src/node_modules/loopback-datasource-juggler/lib/dao.js:284:20)
      stack:
        Error: Pool is closed.
          at /Users/mike/Work/identity-service/src/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:26:17
          at /Users/mike/Work/identity-service/src/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
          at process._tickDomainCallback (node.js:381:11)
          at process.<anonymous> (/Users/mike/Work/identity-service/src/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
~~~

## Question: Is there any way I can detect pool and reconnect in setup() if it's missing?
Also I'm curious why the pool is lost after first test if each script ran in serial by test runner. Appreciate any suggestions.

**Comment by raymondfeng** [comment]
`disconnect` will close the connection pool behind a data source. You need to recreate data sources via reloading the app. Please note that `require` cache the `app` object.

**Comment by mikesparr** [comment]
Okay that makes sense on caching, thus not reconnecting each time.  Since these are already established datasources I don't want to recreate them every test.  Can I instead call boot() and perhaps make that a function within the server.js file so it can be called on the cached app instance to re-establish the datasource connections during test setup?

**Comment by mikesparr** [comment]
Otherwise what do you mean by response "by reloading the app"?  Thanks @raymondfeng

**Comment by raymondfeng** [comment]
One hacky way for test is to remove the cached app module from `require.cache`. Otherwise, you may have to wrap the app create/boot into a factory function.

**Comment by mikesparr** [comment]
Yes I was just testing this in my teardown:
`delete require.cache[require.resolve('../../../server/server')];` but doesn't seem to work so the factory approach may have to be the way. Crazy how difficult just to add functional tests. I'll share if I find solution.

**Comment by mikesparr** [comment]
I wrapped the `server.js` boot() call and then call the `app.boot(cb)` from setup of each test and they work. If others run into this, it might be wise to update scaffolding for LB server file to do this in future.

**server.js (lower portion)**
~~~
app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    console.log('Web server listening at: %s', app.get('url'));
  });
};

app.boot = function(cb) {
    // boot scripts mount components like REST API
    boot(app, __dirname, function(err) {
        if (err) throw err;

        // POST data handling
        app.use(bodyParser.json()); 
        app.use(bodyParser.urlencoded({ extended: true }));
        app.use(multer()); // for parsing multipart/form-data

        // The access token is only available after boot
        app.use(loopback.token({
          model: app.models.accessToken
        }));

        app.use(loopback.cookieParser(app.get('cookieSecret')));
        passportConfigurator.init();

        passportConfigurator.setupModels({
        	userModel: app.models.user,
        	userIdentityModel: app.models.userIdentity,
        	userCredentialModel: app.models.userCredential
        });
        for (var s in config) {
        	var c = config[s];
        	c.session = c.session !== false;
        	passportConfigurator.configureProvider(s, c);
        }

        if (isMain)
        	app.start();

        app.loaded = true;
        app.emit('loaded');
        
        cb(app);
    });  
};

app.boot(function(app) {
    app.emit('booted');
    console.log('booted');
});
~~~

Then in setup step of functional tests I call the `boot()` function.

**my.test.js (stripped)**
~~~
var test = require('tape');
var sinon = require('sinon');
var app = require('../../../server/server');
var request = require('supertest');
var restApiRoot = app.get('restApiRoot');

// change these
var model = app.models.<my_model>;

var apiPath = 'my_model';

var testObj = {
  // snip
};

var testObjUpdate = {
    description: 'Updated description'
};

// custom objects for additional tests

// END changes

// setup
test('-- ' + apiPath + ' functional tests setup ---------------', function(t) {
    // Arrange
    testObj.created = Date();
    
    // delete apps so starting fresh
    app.boot(function(bootedApp) {
        app = bootedApp;
        console.log('set bootedApp as app');
    });
    
    model.destroyAll(function(err,info) {
       if(err) t.error(err);
       
       // create a test app we have 2 records for list
       model.create(testObj, function(err, rec) {
           if (err) t.error(err);

           t.end();
       });
    });
});

/**
 TESTS GO HERE
*/

// teardown
test(apiPath + ' functional tests teardown', function(t) {
    //t.comment('closing Redis...');
    // end Redis connection
    app.dataSources.queueDb.disconnect(function() {
        //t.comment('closed queueDb');
        app.dataSources.cacheDb.disconnect(function() {
            //t.comment('closed cacheDb');
            app.dataSources.authDb.disconnect(function() {
               //t.comment('closed authDb');
               t.end(); 
            });
        });
    });
});
~~~
