### ISSUE TITLE
disable Loopback-component-explorer issue

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback#1700]
to disable explorer in production, simply removing `server/boot/explorer` doesn't work. In addition, you also have to remove the config fle `server/component-config.json`.

**Comment by superkhau** [comment]
@bajtos ^

/cc @crandmck Maybe we need to update the docs to reflect the new best practices with the new `loopback-component-explorer` changes?

**Comment by bajtos** [comment]
> Maybe we need to update the docs to reflect the new best practices with the new loopback-component-explorer changes?

Yes please.

> to disable explorer in production

To disable explorer in production (and keep it available in development mode), one should add the following file to the project:

```js
// server/component-config.json
{
  "loopback-component-explorer": false
}
```

**Comment by crandmck** [comment]
When I tried the above, it disabled Explorer altogether; what do you mean by  
> disable explorer in production (and keep it available in development mode)

How is it available in "development mode"?  Do I need to set an env var or something?

**Comment by bajtos** [comment]
> How is it available in "development mode"? Is there a way to use a different component-config.json depending on an env var or something?

Oh, I beg my pardon, you need to put the JSON snippet to a different file: `server/component-config.production.json`. I'll fix my comment above to prevent further confusion.

```
// server/component-config.production.json
{
  "loopback-component-explorer": false
}
```

**Comment by bajtos** [comment]
> Is there a way to use a different component-config.json depending on an env var or something?

Yes, you can use the same convention that works for other config files (datasources, model-config, etc.) - just add `.{env}.` to your file name, e.g. `server/component-config.production.json`

**Comment by crandmck** [comment]
OK, please review:
- [Turning off stack traces](https://docs.strongloop.com/display/LB/Environment-specific+configuration#Environment-specificconfiguration-Turningoffstacktraces)
- [Disabling API Explorer](https://docs.strongloop.com/display/LB/Environment-specific+configuration#Environment-specificconfiguration-DisablingAPIExplorer)

**Comment by echmykhun** [comment]
Hello!
I just wanted to test production config of my application. I set NODE_ENV to "production" and called node server/server.js and it returns me this:

>/vagrant/node_modules/loopback-boot/lib/config-loader.js:239
    throw new Error('Cannot apply ' + fileName + ': ' + err);
    ^
Error: Cannot apply /vagrant/server/component-config.production.json: Cannot merge values of incompatible types for the option `loopback-component-explorer`.
    at mergeComponentConfig (/vagrant/node_modules/loopback-boot/lib/config-loader.js:239:11)
    at mergeConfigurations (/vagrant/node_modules/loopback-boot/lib/config-loader.js:138:5)
    at loadNamed (/vagrant/node_modules/loopback-boot/lib/config-loader.js:76:16)
    at Object.ConfigLoader.loadComponents (/vagrant/node_modules/loopback-boot/lib/config-loader.js:56:10)
    at compile (/vagrant/node_modules/loopback-boot/lib/compiler.js:60:20)
    at bootLoopBackApp (/vagrant/node_modules/loopback-boot/index.js:139:22)
    at Object.<anonymous> (/vagrant/server/server.js:21:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

here is my component-config.production.json
```javascript
{
  "loopback-component-explorer": false
}
```

and midleware.production.json
```javascript
{
  "final:after": {
    "loopback#errorHandler": {
      "params": {
        "includeStack": false
      }
    }
  }
}
```

Here is my slc -v

>slc -v
strongloop v5.0.1 (node v4.2.1)
├── strong-arc@1.8.3 (d95b140)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.0 (46b06b4)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.12.1 (a374136)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3


And i failed to understand why it crushes and why it shows stacktrace on it's crush

Could you help, please

**Comment by hemantvayali009** [comment]
> > How is it available in "development mode"?
> 
> Oh, I beg my pardon, you need to put the JSON snippet to a different file: `server/component-config.production.json`. I'll fix my comment above to prevent further confusion.
> 
> ```
> // server/component-config.production.json
> {
>   "loopback-component-explorer": false
> }
> ```

Tried this method... But didn't work. Can you please help?

Following are my loopback dependencies in package.json:
 "loopback": "2.25.0",
    "loopback-api-definition": "1.0.0",
    "loopback-boot": "2.14.2",
    "loopback-component-explorer": "2.1.0",
    "loopback-component-push": "^3.0.0",
    "loopback-component-storage": "^1.9.2",
    "loopback-connector": "2.2.0",
    "loopback-connector-mongodb": "1.13.3",
    "loopback-datasource-juggler": "2.43.0",
    "loopback-explorer": "1.8.0",
    "loopback-sdk-angular": "1.6.0",

Also tried "null" instead of "false" in component-config.{env}.json, but didn't work.

**Comment by bajtos** [comment]
@hemantvayali009 please create a small app reproducing the problem (see our [bug reporting instructions](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs)) and open a new issue.
