### ISSUE TITLE
AssertionError: missing path on slc run

### ISSUE THREAD

**Issue by ianseyer** [strongloop/loopback#1715]
Hi all. Had a stable lb application that I recently added a bunch of models to via `slc loopback:model`.

Immediately after that, I ran `node server/server.js` (and `slc run`) only to get a very vague error:

```
Ians-MacBook-Pro:loopback-directgiving ianseyer$ node server/server.js 

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:363:3)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/common/models/donation.js:2:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/node_modules/loopback-boot/lib/executor.js:217:20
    at Array.forEach (native)
    at defineModels (/Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/node_modules/loopback-boot/lib/executor.js:198:23)
    at setupModels (/Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/node_modules/loopback-boot/lib/executor.js:166:3)
    at execute (/Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/node_modules/loopback-boot/lib/executor.js:32:3)
    at bootLoopBackApp (/Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/node_modules/loopback-boot/index.js:140:3)
    at Object.<anonymous> (/Users/ianseyer/Documents/code/web/web/misfits/node/directgiving/loopback-directgiving/server/server.js:22:1)
```

I have looked at `server.js`L22, and it is this:
```
// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
  if (err) throw err;
```

So I'm guessing it has something to do with `__dirname`?

Any ideas?

**UPDATE**

I have reverted to the last stable version of my code (via git) and I get the same error. I have also tried removing the new models from `/common/models` and `model-config`.

Is there a particular environment setting I am missing?

**MYSTERY UPDATE**
So i git reverted, and was still getting the error. However, I created a new git branch, and then went **back** to the original branch and the problem was gone. I then copy pasted the files from the slc loopback:model commands into `/common/models` and everything was happy again.

However, I now get this:
`(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.`

**Comment by superkhau** [comment]
@ianseyer Are you still running into this issue? Can you try updating to the latest `strongloop` via `npm install -g strongloop`. Then scaffold a new project as you did above and see if you still get the same errors.

**Comment by loay** [comment]
Closing due to inactivity, if still experiencing the same issue, please feel free to leave a comment and will re-open. Thanks
