### ISSUE TITLE
Not able to run on windows a project  that I started on linux

### ISSUE THREAD

**Issue by brilvio** [strongloop/loopback#1717]
Data source is memory db, it is running fine on ubuntu but on windows after I installed the node modules, when I try to run with node . this error appears.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at Server._listen2 (D:\gordosteam\medias\node_modules\loopback\node_modules\
continuation-local-storage\node_modules\async-listener\index.js:72:23)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:459:13)
    at process.<anonymous> (D:\gordosteam\medias\node_modules\loopback\node_modu
les\continuation-local-storage\node_modules\async-listener\index.js:19:15)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)

**Comment by brilvio** [comment]
Sorry about that another process was using the 3000 port. sorry.
