### ISSUE TITLE
Error while discovering models from existing `redshift` table.

### ISSUE THREAD

**Issue by sandipp** [strongloop/loopback#1743]
Got the following error while discovering models from existing `redshift` table.

```
Oops! Something is wrong
Cannot read property 'toUpperCase' of undefined
Show/hide details
Message: Cannot read property 'toUpperCase' of undefined
Request: /workspace/api/DataSourceDefinitions/server.bl-pgsql/discoverModelDefinition
Staus: 500
TypeError: Cannot read property 'toUpperCase' of undefined
    at mysqlDataTypeToJSONType (/home/user/appname/node_modules/loopback-connector-postgresql/lib/discovery.js:349:25)
    at /home/user/appname/node_modules/loopback-connector-postgresql/lib/discovery.js:180:20
    at Array.map (native)
    at callback (/home/user/appname/node_modules/loopback-connector-postgresql/lib/discovery.js:179:17)
    at /home/user/appname/node_modules/loopback-datasource-juggler/lib/observer.js:166:22
    at doNotify (/home/user/appname/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)
    at PostgreSQL.ObserverMixin._notifyBaseObservers (/home/user/appname/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)
    at PostgreSQL.ObserverMixin.notifyObserversOf (/home/user/appname/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)
    at cbForWork (/home/user/appname/node_modules/loopback-datasource-juggler/lib/observer.js:156:14)
    at /home/user/appname/node_modules/loopback-connector/lib/sql.js:413:7
```

Please find my [package.json] (https://gist.github.com/sandipp/66a61e245681317b1d6b) 
I'm working on newly installed `loopback` app.
My connection with `redshift` was successful.

**Comment by sandipp** [comment]
found error following function
```javascript
PostgreSQL.prototype.discoverModelProperties = function (table, options, cb) {
    var args = getArgs(table, options, cb);
    var owner = args.owner;
    table = args.table;
    options = args.options;
    cb = args.cb;

    var sql = queryColumns(owner, table);
    var callback = function (err, results) {
      if (err) {
        cb(err, results);
      } else {
        results.map(function (r) {
          r.type = mysqlDataTypeToJSONType(r.dataType, r.dataLength);
        });
        cb(err, results);
      }
    };
    this.execute(sql, callback);
  };
```
in `node_modules/loopback-connector-postgresql/lib/discovery.js` file
if I print r variable is having following values
```javascript
{ owner: 'public',
  tablename: 'tbl_name',
  columnname: 'col_name',
  datatype: 'int',
  datalength: null,
  dataprecision: null,
  datascale: null,
  nullable: 'YES' }
```
So need to change this line
```javascript 
r.type = mysqlDataTypeToJSONType(r.dataType, r.dataLength);
```
to
 ```javascript
 r.type = mysqlDataTypeToJSONType(r.datatype, r.datalength);
```

**Comment by superkhau** [comment]
Can you provide a sample project for me to reproduce this? I don't get lowercase results in the return values in the tests.

**Comment by sandipp** [comment]
I'd not make any changes in code. So I can't provide you sample project.
I already shared my [package.json] (https://gist.github.com/sandipp/66a61e245681317b1d6b).
In addition to that I've connected `redshift` which is using `PostgreSql Server 8.x` from my local `psql-client 9.3`.
Then I've tried discover model link and got this error, and this lowercase properties name.
What more information I can provide?

**Comment by superkhau** [comment]
It looks like you have some discovery code you are writing. Why can't you provide a sample project with the sample project? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by superkhau** [comment]
Closing due to inactivity. Please create a new issue if you are still running into problems.

**Comment by saubhagyab** [comment]
@sandipp I did the fix you said but after model creation none properties cam in all were undefined. Did you face the same problem?
