### ISSUE TITLE
Adding a schema to a model

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#1746]
https://docs.strongloop.com/display/public/LB/Validating+model+data#Validatingmodeldata-Addingaschematoamodel

the code from the example does not work

var productSchema = {
  "name": { "type": "string", "required": true },
  "price": "number"
};
var Product = Model.extend('product', productSchema)

ReferenceError: Model is not defined
    at Object.<anonymous> (/home/test/dev/common/models/product.js:41:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/test/dev/node_modules/loopback-boot/lib/executor.js:219:20
    at Array.forEach (native)
    at defineModels (/home/test/dev/node_modules/loopback-boot/lib/executor.js:200:23)
Program node . exited with code 1

project.js 

look like this

module.exports = function(Product) {

}

Where do I put the code?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
