### ISSUE TITLE
Error: FileSystemProvider: Path does not exist: undefined

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#1761]
According to this doc,

https://docs.strongloop.com/display/public/LB/Storage+component

I created a folder 'storage' under server folder

server/server.js

var ds = loopback.createDataSource({
    connector: require('loopback-component-storage'),
    provider: 'filesystem',
    root: path.join(__dirname, 'storage')
});
 
var container = ds.createModel('container')

Error: FileSystemProvider: Path does not exist: undefined
    at new FileSystemProvider (/home/test/beta/node_modules/loopback-component-storage/lib/providers/filesystem/index.js:25:11)
    at Object.module.exports.createClient (/home/test/beta/node_modules/loopback-component-storage/lib/providers/filesystem/index.js:17:10)
    at Object.createClient (/home/test/beta/node_modules/loopback-component-storage/lib/factory.js:86:18)
    at new StorageService (/home/test/beta/node_modules/loopback-component-storage/lib/storage-service.js:29:25)
    at Object.exports.initialize (/home/test/beta/node_modules/loopback-component-storage/lib/storage-connector.js:12:19)
    at DataSource.setup (/home/test/beta/node_modules/loopback-datasource-juggler/lib/datasource.js:332:17)
    at new DataSource (/home/test/beta/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
    at Registry.createDataSource (/home/test/beta/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/home/test/beta/node_modules/loopback/lib/application.js:414:19)
    at EventEmitter.app.dataSource (/home/test/beta/node_modules/loopback/lib/application.js:221:12)
Program node . exited with code 1

**Comment by mike-aungsan** [comment]
I see what the problem is. The error actually come from datasources.json 

This command should ask for root storage path.

slc loopback:datasource
