### ISSUE TITLE
Error using connector-remote datasource for AccessToken model

### ISSUE THREAD

**Issue by danilat** [strongloop/loopback#1769]
Using loopback to develop a couple of microservices I found a bug when I try to use a common microservice to auth validate access-tokens using remote-connector. 

I have this configuration in the datasource:

```
{
  "db": {
    "database": "mydb",
    "username": "root",
    "name": "db",
    "connector": "mysql"
  },
  "auth": {
    "url": "http://myauthservice/api",
    "name": "auth",
    "connector": "remote"
  }
}
```

And all related authentication/authorization stuff in the model-config use the auth datasource. For example:

```
"AccessToken": {
    "dataSource": "auth",
    "public": false
  }
```

When I use an existing access-token I get this error:

```
/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback/common/models/access-token.js:104
          token.validate(function(err, isValid) {
                ^
TypeError: undefined is not a function
    at HttpInvocation.<anonymous> (/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback/common/models/access-token.js:104:17)
    at /Users/dani/workspace/bierasolutions/accounts/node_modules/loopback-connector-remote/node_modules/strong-remoting/lib/rest-adapter.js:131:18
    at execStack (/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback-connector-remote/node_modules/strong-remoting/lib/remote-objects.js:460:7)
    at RemoteObjects.execHooks (/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback-connector-remote/node_modules/strong-remoting/lib/remote-objects.js:464:10)
    at HttpInvocation.<anonymous> (/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback-connector-remote/node_modules/strong-remoting/lib/rest-adapter.js:129:15)
    at HttpInvocation.transformResponse (/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback-connector-remote/node_modules/strong-remoting/lib/http-invocation.js:337:12)
    at Request._callback (/Users/dani/workspace/bierasolutions/accounts/node_modules/loopback-connector-remote/node_modules/strong-remoting/lib/http-invocation.js:261:10)
    at Request.self.callback (/Users/dani/workspace/bierasolutions/accounts/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/dani/workspace/bierasolutions/accounts/node_modules/request/request.js:1063:14)
```

I'm working to send you a fix to resolve this error

**Comment by superkhau** [comment]
Thanks for the PR. I will pass it along to @ritch since he knows this area better.

**Comment by superkhau** [comment]
@danilat Actually can you submit the PR? You only referenced it.

**Comment by superkhau** [comment]
Actually nevermind, its here at: https://github.com/strongloop/loopback/pull/1770

**Comment by bajtos** [comment]
@ritch this issue seems legit to me.

Based on my understanding of the problem and the discussion in #1770, the problem has two parts:

 - `AccessToken.prototype.validate` cannot be called via loopback-connector-remote.
 - When invoking AccessToken methods via loopback-connector-remote, the responses don't correctly coerce Date properties. This may be a bug in remoting metadata of AccessToken or a bug in loopback-connector-remote.

I think we need somebody from @strongloop/loopback-dev to reproduce the issue. Once it's confirmed, we should prioritize this as a bug fix.

@danilat Sorry for the long silence at our part. I appreciate the effort you put in #1170! I am afraid that this problem is more complex and requires deeper investigation on how AccessToken remoting metadata, loopback-connector-remote and jugglers' Model property coercion works together. I am not sure if this is a good task for new contributors. However, if you feel like digging deep, then let me know and I am happy to guide you!
