### ISSUE TITLE
EMFILE, too many open files during perf test

### ISSUE THREAD

**Issue by priyavivek1** [strongloop/loopback#1836]
I am running a performance test with 50 users. After a certain number of request, approx 3500, all requests started to throw "too many files open" issues. Ulimit of my OS is 1024. 

Following is the full stack trace:
```
2015-11-24T21:02:01.841Z - INSIDE-ERROR-HANDLER: Error: EMFILE, too many open files '/tmp/spawn-sync_input_82911b51d5d59af3dc5757fa' - EMFILE, too many open files '/tmp/spawn-sync_input_82911b51d5d59af3dc5757fa' - apierrorhandler
2015-11-24T21:02:01.841Z - INSIDE-ERROR-HANDLER:  - {"status":{"serverStatusCode":"404","severity":"ERROR","additionalStatus":[{"statusCode":404,"serverStatusCode":"ERROR-NOT-FOUND","severity":"Error","statusDesc":"EMFILE, too many open files '/tmp/spawn-sync_input_82911b51d5d59af3dc5757fa'"}]}} - apierrorhandler
***Server Crashed with Uncaught Exception*** { [Error: EMFILE, too many open files] errno: 20, code: 'EMFILE', syscall: 'uv_resident_set_memory' }
Error: EMFILE, too many open files
    at collectHeap (/home/vagrant/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/info.js:44:21)
    at Object.exports.poll (/home/vagrant/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/info.js:40:3)
    at Agent.poll (/home/vagrant/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/agent.js:350:8)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.unrefdHandle [as ontimeout] (timers.js:295:14)
  Metadata:
  stack:
    - Error: EMFILE, too many open files
    -     at collectHeap (/home/vagrant/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/info.js:44:21)
    -     at Object.exports.poll (/home/vagrant/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/info.js:40:3)
    -     at Agent.poll (/home/vagrant/.nvm/v0.10.38/lib/node_modules/strongloop/node_modules/strong-agent/lib/agent.js:350:8)
    -     at wrapper [as _onTimeout] (timers.js:261:14)
    -     at Timer.unrefdHandle [as ontimeout] (timers.js:295:14)
  message:   EMFILE, too many open files
  errno:     20
  code:      EMFILE
  syscall:   uv_resident_set_memory
```

A lot of places states increasing the ulimit is the solution, what should be the valid value of unlimit to be set. 

@bnoordhuis :

**Comment by bnoordhuis** [comment]
I'd set it high, there's no real reason not to these days.  Try `ulimit -n 32768` and see if that resolves the issue.

**Comment by priyavivek1** [comment]
@bnoordhuis :Changing ulimit will definitely resolve the issue. Just wanted to comfirm, is this the only solution or we can fix it some other way.
i have gone through the code at /strongloop/node_modules/strong-agent/lib/info.js:44:21), and found its process.memoryUsage(), where its throwing error.

i tried putting a timeout at socket connection, but it didn't resolve the issues. any thoughts?

**Comment by bnoordhuis** [comment]
`process.memoryUsage()` opens `/proc/self/stat` to find out how much RSS the process is currently using.  I'll add some error handling to strong-agent for this particular case but in general, if your server is under moderate load, you're going to hit the default file descriptor limit sooner or later.

**Comment by richardpringle** [comment]
@priyavivek1, @bnoordhuis, this good to close?

**Comment by bnoordhuis** [comment]
Yes, I'll close the issue.
