### ISSUE TITLE
destroyAll with where clause crashes

### ISSUE THREAD

**Issue by fablife** [strongloop/loopback#1837]
TestModel.destroyAll({where: {testprop: {like: "hallo%"}}}, function(err, results) {
      if (err) {
        console.log(err);
        done(err);
      }   
      console.log("success");
      console.log(results);
    }); ` 

The `where` clause object is being interpreted as a field for lookup.
This happens in the context of an `after()` mocha test function.

    TypeError: Cannot read property 'type' of undefined
      at PostgreSQL.toColumnValue (node_modules/loopback-connector-postgresql/lib/postgresql.js:432:11)
      at PostgreSQL.SQLConnector._buildWhere (node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:819:28)
      at PostgreSQL.SQLConnector.buildWhere (node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:641:26)
      at PostgreSQL.SQLConnector.buildDelete (node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:540:25)
      at PostgreSQL.SQLConnector.destroyAll (node_modules/loopback-connector-postgresql/node_modules/loopback-connector/lib/sql.js:557:19)

**Comment by Amir-61** [comment]
Hi @fablife,

The syntax you are using is not right; I recommend that you go through the documentations for [destroyAll](https://docs.strongloop.com/display/LB/PersistedModel+class#persistedmodel-destroyall) and [where clause syntax](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Whereclauseforothermethods). Also there are some examples showing the right syntax,...; please follow them. For these types of questions please post your question in our [Google Forum](https://groups.google.com/forum/#!forum/loopbackjs)

Here is one of the examples I'm just referencing from our documentation for `where clause`, so as you see there is no `where` keyword :

```
productModel.destroyAll( { cost: {gt: 100} }, function(err, obj) { ... } )
```

Thanks!
