### ISSUE TITLE
Cannot read property 'type' of undefined for polymorphic relationship keys used in a composite id

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback#1867]
Reading from your documentation I can add set an id property to a positive integer to make it part of a composite id (https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-IDproperties)

as, soon as I add a id property it crashed.

Before

``` json
    "actorType": {
      "type": "string",
      "required": true
    },
    "actorId": {
      "type": "string",
      "required": true
    }
```

after

``` json
    "actorType": {
      "type": "string",
      "id": 1,
      "required": true
    },
    "actorId": {
      "type": "string",
      "id": 2,
      "required": true
    }
```

``` bash
TypeError: Cannot read property 'type' of undefined
    at DataSource.defineForeignKey (/node_modules/loopback-datasource-juggler/lib/datasource.js:1806:45)
    at Function.RelationDefinition.belongsTo (/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1240:28)
    at Function.RelationMixin.belongsTo (/node_modules/loopback-datasource-juggler/lib/relations.js:123:29)
    at /node_modules/loopback-datasource-juggler/lib/datasource.js:481:28
    at Array.forEach (native)
    at DataSource.defineRelations (/node_modules/loopback-datasource-juggler/lib/datasource.js:442:28)
    at DataSource.setupDataAccess (/node_modules/loopback-datasource-juggler/lib/datasource.js:522:8)
    at DataSource.attach (/node_modules/loopback-datasource-juggler/lib/datasource.js:738:8)
    at Function.ModelClass.attachTo (/node_modules/loopback-datasource-juggler/lib/model-builder.js:331:16)
    at Registry.configureModel (/node_modules/loopback/lib/registry.js:238:15)
```

The property is part of a polymorphic relation. I want to be able to upsert using a composite id, is this possible?

**Comment by gunjpan** [comment]
@kennethlynne : Hi, I tried to reproduce the issue with a sandbox and composite id worked fine. Could you please let me know the config of your `datasource.json` as well as the `actor.json` (i.e. `model.json`)
Also, a sample repo with the steps to reproduce will  greatly help me to identify the cause.

**Comment by AlmaasAre** [comment]
@gunjpan Are you using mongodb? Ended up using unique indexes as a workaround for composite id's for mongodb. But upsert does not seem to take a unique index into consideration.

**Comment by gunjpan** [comment]
@AlmaasAre : I was using `memory` as db. I will give it a spin with mongodb.

**Comment by gunjpan** [comment]
@AlmaasAre @kennethlynne : related issue:
https://github.com/strongloop/loopback/issues/1295
