### ISSUE TITLE
Explorer/Swagger UI adds = after ?filter (GET)

### ISSUE THREAD

**Issue by Stwissel** [strongloop/loopback#1981]
A URL looking like this works as defined:

http://localhost:3000/api/Members/findOne?filter[where][Nickname]=NotesSensei

However filling in the filter parameter in the Explorer UI results in an URL looking like this:

http://localhost:3000/api/Members/findOne?filter=[where][Nickname]=NotesSensei

where there is an equal sign after filter that shouldn't be there. 

Loopback 2.26.2

**Comment by 0candy** [comment]
API Explorer automatically adds "filter" to the query string, but you must enter Stringified JSON in the filter field. Also make sure that the quotes you use are proper straight quotes ( " ), not curved or typographic quotation marks ( “ or ” ).

The equal sign should not be a problem if the filter value is a json object:
>REST:
/medias?filter[where][keywords][inq]=foo&filter[where][keywords][inq]=bar
>Or 
>?filter={"where": {"keywords": {"inq": ["foo", "bar"]}}}

See documentation:
https://docs.strongloop.com/display/public/LB/Where+filter

**Comment by Stwissel** [comment]
Thx for the reply. Seems I need to still learn, since I can't get it to work.
This one does:
http://localhost:3000/api/Members/findOne?filter[where][Nickname]=NotesSensei

I entered this into the filter parameter input box: ```{where: {Nickname: 'NotesSensei'}}``` (also tried with double quotes). The displayed request URL looks like this:

http://localhost:3000/api/Members/findOne?filter=%7Bwhere%3A%20%7BNickname%3A%20'NotesSensei'%7D%7D

and the result isn't the record, but:

```
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "invalid value for argument 'filter' of type 'object': {where: {Nickname: 'NotesSensei'}}. Received type was string. Error: Unexpected token w",
    "statusCode": 400,
    "stack": "Error: invalid value for argument 'filter' of type 'object': {where: {Nickname: 'NotesSensei'}}. Received type was string. Error: Unexpected token w\n    at new badArgumentError (/Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:268:13)\n    at coerceAccepts (/Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:324:13)\n    at SharedMethod.invoke (/Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:217:16)\n    at HttpContext.invoke (/Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:384:12)\n    at /Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:620:11\n    at execStack (/Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:460:7)\n    at RemoteObjects.execHooks (/Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:464:10)\n    at /Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:617:10\n    at /Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/lib/application.js:358:13\n    at /Users/stw/Code/bitbucket/joyriders-server/node_modules/loopback/lib/model.js:313:7"
  }
}
```
So either I have a knot in my understanding (which would be my first assumption ;-) ) or there might be a bug in how the explorer and the API work together.

Help is very much appreciated

**Comment by AurelieV** [comment]
@Stwissel you have to add " around all string.

- `{where:{Nickname: 'NotesSensei'}}` not good
- `{"where":{"Nickname": "NotesSensei"}}`good

**Comment by 0candy** [comment]
@Stwissel Did @AurelieV's suggestion help?

**Comment by 0candy** [comment]
@Stwissel I am closing this issue due to inactivity. If you are still running into problems, feel free to leave a comment and I will reopen the issue. Thanks!

**Comment by emacaya** [comment]
I am using strongloop on bluemix with the cloudant database. On the swagger explorer this filter works {"where":{"id":"f0bce4b3906318f37ff1d90454874008"}}

But when I use the filter in code, the call execute successfully but the records are not filtered.
Here's the code using the filter

client.Shoe.Shoe_find({"where":{"id":"f0bce4b3906318f37ff1d90454874008"}}).then(function (result) {
       success(result);
}).catch(function (error) {
      alert(error);
});

The code uses swagger-client.js library.

**Comment by emacaya** [comment]
We found the problem. I am getting a CORS error when a filter is added to the call. To fix add this on your server.js

var cors = require('cors'); 
app.use(cors());

reference:(https://github.com/strongloop/loopback/issues/575)

client.Shoe.Shoe_find({"filter":{"where":{"id":"f0bce4b3906318f37ff1d90454874008"}}}).then(function (result) {
success(result);
}).catch(function (error) {
alert(error);
});
