### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by johannesjo** [strongloop/loopback#1992]
In my production environment (Plesk running JXCore and node v.0.10.24) I get the following error on every request that requires authentication. Locally everything works fine.

I really would be thankful for any clue about what could be causing this.

```
/my-project/node_modules/loopback/node_modules/continuation-local-storage/context.js:78
throw exception;
^
TypeError: Cannot read property 'length' of undefined
at IncomingMessage.removeListener (events.js:181:16)
at IncomingMessage.removed (/my-project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:106:35)
at cleanup (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:317:12)
at invokeCallback (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:255:7)
at done (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
at IncomingMessage.onEnd (/my-project/node_modules/loopback/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
at IncomingMessage. (/my-project/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)
at IncomingMessage.emit (events.js:79:17)
at IncomingMessage.emitted [as emit] (/my-project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
at _stream_readable.js:889:16
Spawner error:	Application exited by itself with code: 8
Spawner info:	Spawner could not kill the app when exiting: Error: kill ESRCH
Spawner info:	Subscribing is delayed by 2000 ms.
Spawner info:	Subscribed successfully (as root): Successfully subscribed process 32307 to the monitor.
Spawner info:	Restart manager is active.
Web server listening at: http://0.0.0.0:10014
Browse your REST API at http://0.0.0.0:10014/explorer
```

**Comment by loay** [comment]
Hi @johannesjo 
It looks like it is an issue in the 
``` 
namespace.bind(callback, [context])
```
function. 

What's the discrepancy between your development and production environment?
Same node version?
Same npm version?

also, since there is no repo for me to test, I am not sure if it is in the `loopback` component or `continuation-local-storage`
So please double check first what seems to be different in your environment server and let know and we will see from there. Thanks.

**Comment by johannesjo** [comment]
Hello @loay! Thank you for getting back to me so quickly. Indeed the node and npm versions differ. Locally I use node v5.5.0 and npm 3.3.12 ad on my remote host it's node v0.10.24 and npm 1.3.21. 

I would love to update npm and node on the remote server, but unfortunately I'm stuck with Debian Wheezy there for now as a dist-upgrade would be very painful to do.

**Comment by johannesjo** [comment]
After having done a luckily not so painful update from Debian 6 to 7 I can say that his is related to jxcore and not the node version.

**Comment by loay** [comment]
Also, if you look at this case:
https://github.com/othiym23/node-continuation-local-storage/issues/12
it is not the same property but it can point you to the direction of the issue.

**Comment by loay** [comment]
@johannesjo It doesn't look that it is loopback related. I will close this issue for now. If you are still having troubles, please leave a comment and I will re-open the issue.

**Comment by johannesjo** [comment]
Yes, it's probably an issue of jxcore. Thanks for your support though!
