### ISSUE TITLE
Sign up with a model that inherets from User model

### ISSUE THREAD

**Issue by achref-benahmed** [strongloop/loopback#2008]
I'm trying to sign up a UserRh that inherets from User but it includes other properties ; phoneNumber , companyName. Here's the code : 

// ejs file
```
<section>
  <form action="/api/UserRhs" method="post">
    <fieldset>
      <legend>Sign up form</legend>
      <div>
        <label for="email">Email:</label>
        <input type="text" name="email" value="<%= email %>"/>
      </div>
      </div>
        <label for="password">Password:</label>
        <input type="text" name="password" value="<%= password %>"/>
      </div>
      <div>
        <label for="CompanyName">CompanyName:</label>
        <input type="text" name="CompanyName" value="<%= companyName %>"/>
      </div>
     
      <div>
        <label for="phoneNumber">Phone number:</label>
        <input type="number" name="phoneNumber" value="<%= phoneNumber %>"/>
      
       
      <div>
        <input type="submit" value="Sign up"/>
      </div>
```

// js file 
```
UserRh.afterRemote('create', function(context, UserRh, next) {
  
    console.log('> UserRh.afterRemote triggered');
    console.log(UserRh.email);
    console.log(UserRh.password);
var options = {
      type: 'email',
      to: UserRh.email,
      from: 'noreply@loopback.com',
      subject: 'Thanks for registering.',
      template: path.resolve(__dirname, '../../server/views/verify.ejs'),
      redirect: '/verified',
      UserRh: UserRh
    };
```

My problem is that when executing the application doesn't accept added properties. Here's my UserRh.json

```
{
  "name": "UserRh",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "email": {
      "type": "string",
      "required": true
    },
    "password": {
      "type": "string",
      "required": true
    },
    "companyName": {
      "type": "string",
      "required": true
    },
    "phoneNumber": {
      "type": "number",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

How can I fix it?

500 ReferenceError: /home/egoe/Hiringme/server/views/login.ejs:32

       30|       <div>
       31|         <label for="CompanyName">CompanyName:</label>
    >> 32|         <input type="text" name="CompanyName" value="<%= companyName %>"/>
       33|       </div>
       34|      
       35|       <div>
    companyName is not defined
       at eval (eval at <anonymous> (/home/egoe/Hiringme/node_modules/loopback/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:20:23)
       at returnedFn (/home/egoe/Hiringme/node_modules/loopback/node_modules/ejs/lib/ejs.js:514:17)
       at View.exports.renderFile [as engine] (/home/egoe/Hiringme/node_modules/loopback/node_modules/ejs/lib/ejs.js:358:31)
       at View.render (/home/egoe/Hiringme/node_modules/loopback/node_modules/express/lib/view.js:126:8)
       at tryRender (/home/egoe/Hiringme/node_modules/loopback/node_modules/express/lib/application.js:639:10)
       at EventEmitter.render (/home/egoe/Hiringme/node_modules/loopback/node_modules/express/lib/application.js:591:3)
       at ServerResponse.render (/home/egoe/Hiringme/node_modules/loopback/node_modules/express/lib/response.js:961:7)
       at /home/egoe/Hiringme/server/boot/routes.js:7:9
       at Layer.handle [as handle_request] (/home/egoe/Hiringme/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
       at next (/home/egoe/Hiringme/node_modules/loopback/node_modules/express/lib/router/route.js:131:13)

**Comment by achref-benahmed** [comment]
@raymondfeng

**Comment by richardpringle** [comment]
Hey @achref-benahmed, have you tried to POST a UserRh with explorer?

**Comment by achref-benahmed** [comment]
@richardpringle Hey sorry for the late answer.
I fixed the problem and it's working.
Thank you
