### ISSUE TITLE
Loopback.io does not work with node-red

### ISSUE THREAD

**Issue by thaiat** [strongloop/loopback#2139]
Using the latest of both, here is my code to embed node-red into loopback:
```js
var loopback = require('loopback');
var boot = require('loopback-boot');
var RED = require('node-red');

var settings = {
    httpAdminRoot: "/red",
    httpNodeRoot: "/api",
    userDir: "/Users/thaiat/.node-red",
    functionGlobalContext: {} // enables global context
};

var app = module.exports = loopback();

RED.init(app, settings);

app.use(settings.httpAdminRoot, RED.httpAdmin);
app.use(settings.httpNodeRoot, RED.httpNode);

app.start = function() {
    // start the web server
    return app.listen(function() {
        app.emit('started');
        var baseUrl = app.get('url').replace(/\/$/, '');
        console.log('Web server listening at: %s', baseUrl);
        if (app.get('loopback-component-explorer')) {
            var explorerPath = app.get('loopback-component-explorer').mountPath;
            console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
        }
    });
};

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
    if (err) throw err;

    // start the server if `$ node server.js`
    if (require.main === module) {
        app.start();
    }
});
```

When i navigate to http://localhost:3000/red, no nodes (node-red components) are showing up an i get the following error:
```
ypeError: Cannot read property 'en-US' of undefined
    at Object.i18n.functions.extend.load (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/i18next/lib/i18nextWrapper.js:282:39)
    at init (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/i18next/node_modules/i18next-client/i18next.js:988:19)
    at Object.setLng (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/i18next/node_modules/i18next-client/i18next.js:1200:16)
    at module.exports.get (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/red/api/locales.js:57:16)
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/index.js:277:22
    at param (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/index.js:349:14)
TypeError: Cannot read property 'en-US' of undefined
    at Object.i18n.functions.extend.load (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/i18next/lib/i18nextWrapper.js:282:39)
    at init (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/i18next/node_modules/i18next-client/i18next.js:988:19)
    at Object.setLng (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/i18next/node_modules/i18next-client/i18next.js:1200:16)
    at module.exports.get (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/red/api/locales.js:57:16)
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/index.js:277:22
    at param (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/index.js:349:14)
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.storageModuleInterface.getAllFlows (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/red/runtime/storage/index.js:117:30)
    at module.exports.getAll (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/red/api/library.js:80:17)
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:131:13)
    at /Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/red/api/auth/index.js:63:13
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /Users/thaiat/Documents/Phonegap/loopback-node-red/node_modules/node-red/node_modules/express/lib/router/index.js:277:22
```

**Comment by knolleary** [comment]
As per the linked node-red issue, the code above never actually starts node-red, so it fails to service the routes properly. This came up recently and we'll be adding better error reporting for this scenario.

**Comment by thaiat** [comment]
solved here https://github.com/node-red/node-red/issues/831

**Comment by sachinhub** [comment]
There is a a node-RED contrib module available @ https://github.com/EdgeVerve/loopback-connector-nodes-for-Node-RED which allows running Node-RED from within loopback application. It also provides nodes which can observe events happening in loopback application and trigger a flow. 

Please have a look at the wiki page @ https://github.com/EdgeVerve/loopback-connector-nodes-for-Node-RED/wiki/Loopback-connector-for-Node-RED 

This is my recent work which our company has opensourced. Please visit the repo and leave your comments.
