### ISSUE TITLE
slc pm error

### ISSUE THREAD

**Issue by luckymancvp** [strongloop/loopback#2160]
I dont know why ? But I can not deploy my app to develop server  by this command in local : 
`slc build; slc deploy http://dev.chotsale.vn`

But when I run `slc pm` in my local and then deploy by command `slc build; slc deploy http://127.0.0.1`, so I can run in local

This is log from develop server .

```
2016-03-22T17:14:44.293Z pid:1327 worker:4 WARNING: LoopBack connector "mongoDb" is not installed as any of the following modules:
2016-03-22T17:14:44.294Z pid:1327 worker:4  ./connectors/mongoDb
2016-03-22T17:14:44.294Z pid:1327 worker:4 loopback-connector-mongoDb
2016-03-22T17:14:44.294Z pid:1327 worker:4 mongoDb
2016-03-22T17:14:44.295Z pid:1327 worker:4 To fix, run:
2016-03-22T17:14:44.295Z pid:1327 worker:4     npm install mongoDb
2016-03-22T17:14:44.295Z pid:1327 worker:4     at DataSource.setup (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback-datasource-juggler/lib/datasource.js:304:28)
2016-03-22T17:14:44.295Z pid:1327 worker:4     at new DataSource (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
2016-03-22T17:14:44.296Z pid:1327 worker:4     at Registry.createDataSource (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback/lib/registry.js:349:12)
2016-03-22T17:14:44.296Z pid:1327 worker:4     at dataSourcesFromConfig (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback/lib/application.js:415:19)
2016-03-22T17:14:44.296Z pid:1327 worker:4     at EventEmitter.app.dataSource (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback/lib/application.js:222:12)
2016-03-22T17:14:44.296Z pid:1327 worker:4     at /root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback-boot/lib/executor.js:174:9
2016-03-22T17:14:44.297Z pid:1327 worker:4     at /root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback-boot/lib/executor.js:265:5
2016-03-22T17:14:44.297Z pid:1327 worker:4     at Array.forEach (native)
2016-03-22T17:14:44.301Z pid:1327 worker:4     at forEachKeyedObject (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback-boot/lib/executor.js:264:20)
2016-03-22T17:14:44.305Z pid:1327 worker:4     at setupDataSources (/root/.strong-pm/svc/1/work/ae79850555e92ed60a1fdae72675093eba35c335.1458666860378/node_modules/loopback-boot/lib/executor.js:173:3)
```

**Comment by luckymancvp** [comment]
I'm sure that I install mongoDb, "loopback-connector-mongodb": "^1.13.3",

**Comment by richardpringle** [comment]
@luckymancvp, it looks like this issue is in the wrong-repo. Please migrate to https://github.com/strongloop/strongloop/issues
