### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by farlynd** [strongloop/loopback#2191]
Hi, 
I try to follow ReferencesMany helper's method, and get this error

```
process.nextTick(function() { throw err;});
                                  ^
TypeError:` Cannot read property create of undefined
```

this is kamar's remote method code,

```
module.exports = function (Kamar) {
    Kamar.addFasilitasKamarFK = function (id, fk, callback) {
         Kamar.findById(id, function (err, kamars) {
            console.log("Kamar: ",kamars);
            kamars.fasilitass.create(fk);
});

Kamar.remoteMethod(
        "addFasilitasKamarFK",
        {
            description: ["Adding FK"],
            accepts: [
                {arg: "id", type: "string", http: {source: 'path'}, required: true, description: "Id"},
                {
                    arg: "fk",
                    type: "string",
                    http: {source: 'path'},
                    required: true,
                    description: "FK"
                }
            ],
            returns: {
                arg: "status", type: "object", root: true, description: "Return value"
            },
            http: {verb: "put", path: "/:id/addMoreKamarForeignKey/:fk"}
        }
    );`
```

and this is kamar model json : 

```
`{
  "name": "Kamar",
  "plural": "Kamars",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "nama": {
      "type": "string",
      "required": true
    },
    "tipe": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "Fasilitass": {
      "type": "referencesMany",
      "model": "Fasilitas",
      "foreignKey": "fasilitasIds",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  },
  "acls": [],
  "methods": {}
}`

```
is this a bug or something i missing?
Thanks.

Farly.

**Comment by jannyHou** [comment]
@farlynd I think the problem happens with your model name `Fasilitas`, I tried with model `Account` it works fine:
```
"accounts": {
      "type": "referencesMany",
      "model": "account",
      "foreignKey": "accountIds"
    }
```
I will dig into the reason.

**Comment by jannyHou** [comment]
@farlynd ah...the tricky thing is **Relation Name** is case sensitive, so you should use 
`*Fasilitass*` instead of 
`*fasilitas*` 
in `kamars.fasilitass.create(fk);`,
if you  define you relation name as `*Fasilitas*`:
```
"relations": {
    "Fasilitass": {
      "type": "referencesMany",
```

**Comment by farlynd** [comment]
wow, so fast! 

actually thats works, thanks!, 

```
Kamar.findById(id, function (err, kamars) {
            kamars.fasilitass.add(fk,callback);
});
```

**Comment by shrimaliakash** [comment]
If i write that code console print following error;

**Comment by shrimaliakash** [comment]
```
  user.launchUserGoal = function(id,userGoalId, cb) {
    console.log(userGoalId);
    var UserGoal = app.models.userGoal;
    var filter = {};
      filter["include"] = [{
        relation: 'User',
      },
      {
        relation: 'UserSubscription',
      }
      ];
      //filter["where"] = {"userId" : id};
      //if (userGoalId) filter.where["userGoalId"]; = userGoalId;
      console.log('akash');
      console.log(userGoalId);
      //var userGoalId = filter.where["userGoalId"];
      console.log(userGoalId);
      UserGoal.findById(userGoalId, filter, function(err, UserGoal){
        console.log('user: ' + JSON.stringify(UserGoal));
        if(UserGoal.length < 1){
          returnError("User Goal not found", httpStatus.NOT_FOUND, "USER_GOAL_NOT_FOUND", cb);
          return;
        }
        else{
          cb(null,UserGoal);
        }  
      });
  } 
```

      
 

If i write that code console print following error: 
Unhandled error for request POST /users/launchUserGoal?access_token=EjXWhnKmghet
E37Fe47KOrFlWk3jJmspeUrCqT0OSxhwrWLBpjlCuY0ZBdF5Ev8x: TypeError: Cannot read pro
perty 'findById' of undefined
    at Function.user.launchUserGoal (C:\Users\ketan\Desktop\sprezie\common\model
s\user.js:1061:15)
    at SharedMethod.invoke (C:\Users\ketan\Desktop\sprezie\node_modules\strong-r
emoting\lib\shared-method.js:270:25)
    at HttpContext.invoke (C:\Users\ketan\Desktop\sprezie\node_modules\strong-re
moting\lib\http-context.js:297:12)
    at phaseInvoke (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\
lib\remote-objects.js:677:9)
    at runHandler (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\n
ode_modules\loopback-phase\lib\phase.js:135:5)
    at iterate (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node
_modules\loopback-phase\node_modules\async\lib\async.js:146:13)
    at Object.async.eachSeries (C:\Users\ketan\Desktop\sprezie\node_modules\stro
ng-remoting\node_modules\loopback-phase\node_modules\async\lib\async.js:162:9)
    at runHandlers (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\
node_modules\loopback-phase\lib\phase.js:144:13)
    at iterate (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node
_modules\loopback-phase\node_modules\async\lib\async.js:146:13)
    at C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node_modules\
loopback-phase\node_modules\async\lib\async.js:157:25
    at C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node_modules\
loopback-phase\node_modules\async\lib\async.js:154:25
    at execStack (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\li
b\remote-objects.js:522:7)
    at RemoteObjects.execHooks (C:\Users\ketan\Desktop\sprezie\node_modules\stro
ng-remoting\lib\remote-objects.js:526:10)
    at phaseBeforeInvoke (C:\Users\ketan\Desktop\sprezie\node_modules\strong-rem
oting\lib\remote-objects.js:673:10)
    at runHandler (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\n
ode_modules\loopback-phase\lib\phase.js:135:5)
    at iterate (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node
_modules\loopback-phase\node_modules\async\lib\async.js:146:13)
    at C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node_modules\
loopback-phase\node_modules\async\lib\async.js:157:25
    at reportSharedCtorError (C:\Users\ketan\Desktop\sprezie\node_modules\strong
-remoting\lib\remote-objects.js:669:5)
    at runHandler (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\n
ode_modules\loopback-phase\lib\phase.js:135:5)
    at iterate (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\node
_modules\loopback-phase\node_modules\async\lib\async.js:146:13)
    at Object.async.eachSeries (C:\Users\ketan\Desktop\sprezie\node_modules\stro
ng-remoting\node_modules\loopback-phase\node_modules\async\lib\async.js:162:9)
    at runHandlers (C:\Users\ketan\Desktop\sprezie\node_modules\strong-remoting\
node_modules\loopback-phase\lib\phase.js:144:13)

**Comment by shrimaliakash** [comment]
answer for that comment as follow;

**Comment by Nilesh-Misal** [comment]
TypeError: Cannot read property 'create' of undefined
    at /home/nilesh/Desktop/proximus project (2)/routes/customer.js:58:21
    at Layer.handle [as handle_request] (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/layer.js:95:5)
    at /home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:174:3)
    at router (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:317:13)
    at /home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nilesh/Desktop/proximus project (2)/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/home/nilesh/Desktop/proximus project (2)/node_modules/cookie-parser/index.js:56:14)

**Comment by Nilesh-Misal** [comment]
router.post('/create11', function(req, res) {
   var params = {
    newcustomerno:req.body.customer,
    existingcustomerno:req.body.existingnumber,
    language:req.body.language,
    conatctperson    : req.body.cname,
}

    models.Customer.create(params)
  .then((result) => {
    console.log('helllo')
    console.log(result)
    res.redirect('/');
  //  console.log(req.body);
  
     
  //  res.redirect('/customer');
    
  })
  .catch(function(err){
    console.log(err)
  })
});

this is my code can any one help me?

**Comment by Arathy-sivan** [comment]
Hi, 
I try to download files using Loopback4 , then I got these error message

Server is running at http://[::1]:3000
Try http://[::1]:3000/ping
Unhandled error in GET /testfile: 500 TypeError: Cannot read property 'status' of undefined
    at TodoController.getFile (D:\todo\src\controllers\todo.controller.ts:280:8)
    at invokeTargetMethod (D:\todo\node_modules\@loopback\context\src\invocation.ts:255:47)
    at D:\todo\node_modules\@loopback\context\src\invocation.ts:232:12
    at Object.transformValueOrPromise (D:\todo\node_modules\@loopback\context\src\value-promise.ts:270:12)
    at invokeTargetMethodWithInjection (D:\todo\node_modules\@loopback\context\src\invocation.ts:227:10)
    at InterceptedInvocationContext.invokeTargetMethod (D:\todo\node_modules\@loopback\context\src\invocation.ts:118:14)    at targetMethodInvoker (D:\todo\node_modules\@loopback\context\src\interceptor.ts:341:23)
    at D:\todo\node_modules\@loopback\context\src\interceptor-chain.ts:175:14
    at Object.transformValueOrPromise (D:\todo\node_modules\@loopback\context\src\value-promise.ts:270:12)
    at GenericInterceptorChain.invokeNextInterceptor (D:\todo\node_modules\@loopback\context\src\interceptor-chain.ts:170:12)
    at GenericInterceptorChain.next (D:\todo\node_modules\@loopback\context\src\interceptor-chain.ts:158:17)
    at GenericInterceptorChain.invokeInterceptors (D:\todo\node_modules\@loopback\context\src\interceptor-chain.ts:144:17)
    at Object.invokeInterceptors (D:\todo\node_modules\@loopback\context\src\interceptor-chain.ts:207:16)
    at D:\todo\node_modules\@loopback\context\src\interceptor.ts:343:14
    at Object.tryWithFinally (D:\todo\node_modules\@loopback\context\src\value-promise.ts:196:14)
    at Object.invokeMethodWithInterceptors (D:\todo\node_modules\@loopback\context\src\interceptor.ts:337:10)


** controller is ,

 @get('/testfile', {
    responses: {
      '200': {
        description: 'get dummy file',
        content: { 'application/txt': { schema: { type: 'string' } } },
      },
    },
  })
  getFile() {
    let data = fs.readFileSync('D:/todo/public/files/file1');
    this.response
      .status(200)
      .contentType('application/txt')
      .attachment('file1.txt')
      .send(data);
  }
