### ISSUE TITLE
Certain api urls not working with a Hasmany through relation for user roles

### ISSUE THREAD

**Issue by shalkam** [strongloop/loopback#2249]
Hello,
First here is the message that I get for calling this url :
>http://0.0.0.0:3000/api/users/1/roles/1

```javascript{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'",
    "code": "ER_BAD_FIELD_ERROR",
    "errno": 1054,
    "sqlState": "42S22",
    "index": 0,
    "stack": "Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'\n    at Query.Sequence._packetToError (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)\n    at Query.ErrorPacket (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)\n    at Protocol._parsePacket (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/Protocol.js:280:23)\n    at Parser.write (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/Parser.js:73:12)\n    at Protocol.write (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/Connection.js:96:28)\n    at emitOne (events.js:90:13)\n    at Socket.emit (events.js:182:7)\n    at readableAddChunk (_stream_readable.js:147:16)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:525:20)\n    --------------------\n    at Protocol._enqueue (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/Protocol.js:141:48)\n    at PoolConnection.query (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/Connection.js:201:25)\n    at runQuery (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/loopback-connector-mysql/lib/mysql.js:146:16)\n    at executeWithConnection (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/loopback-connector-mysql/lib/mysql.js:188:7)\n    at Ping.onOperationComplete (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/Pool.js:99:5)\n    at Ping.<anonymous> (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/continuation-local-storage/context.js:76:17)\n    at bound (domain.js:287:14)\n    at Ping.runBound [as _callback] (domain.js:300:12)\n    at Ping.Sequence.end (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)\n    at Ping.Sequence.OkPacket (/mnt/all/programming/nodejs/sandbox/lp-ng-admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)"
  }
}

My user model definition :
{
  "name": "user",
  "plural": "users",
  "base": "User",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "accessToken",
      "foreignKey": "userId"
    },
    "identities": {
      "type": "hasMany",
      "model": "userIdentity",
      "foreignKey": "userId"
    },
    "credentials": {
      "type": "hasMany",
      "model": "userCredential",
      "foreignKey": "userId"
    },
    "roles": {
      "type": "hasMany",
      "model": "Role",
      "foreignKey": "principalId",
      "through": "RoleMapping"
    },
    "visits": {
      "type": "hasMany",
      "model": "Visit",
      "foreignKey": "userId"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```
I absolutely have no idea where to start to find out what wrong with the code.
Please help.

regards,
Mostafa

**Comment by shalkam** [comment]
I've been able to figure it out.
The problem was with the [role-mapping.json](loopback/common/models/role-mapping.json) 

it didn't have the relationship for the user model so I had to add it manually
so I edited the its relations to become like this - added a "user" relationship -
```javascript
    "relations": {
        "role": {
            "type": "belongsTo",
            "model": "Role",
            "foreignKey": "roleId"
        },
        "user": {
            "type": "belongsTo",
            "model": "user",
            "foreignKey": "principalId"
        }
    }
```
but I had to change the core code inside loopback module itself, I don't know if there is a better way to do it or not.

regards,
Mostafa

**Comment by jannyHou** [comment]
@shalkam I think you are trying to create a relation from your model(`user`) to a lb build-in model(`Role`) which is not suggested. 

Regarding how to use `Role`, please check our doc https://docs.strongloop.com/display/public/LB/Defining+and+using+roles to see more details.

And also this example: https://github.com/strongloop/loopback-example-access-control to see like how to register resolver.

**Comment by shalkam** [comment]
@jannyHou  I am using the angular sdk, and it's easier for me to do the user/roles link via the api.
What about if I create the a couple of models that extend the "Role" and the "RoleMapping" model instead of using the  loopback built-in models, would that be recommended?

**Comment by shalkam** [comment]
I've fixed the issue using models extending the built-in models, and things seems to be ok

**Comment by jannyHou** [comment]
@shalkam Glad to know that you fix it! Build-in models are read-only, that's why sometimes your change wouldn't work. I am closing issue since it's fixed. Please feel free to reopen it if you have further  questions.
