### ISSUE TITLE
Filter on second-level property does not respect type

### ISSUE THREAD

**Issue by mrbatista** [strongloop/loopback#2303]
I have the model `Model1` with the following properties (note that lastMessage is embedsOne model):

``` javascript
{
  "name": "Model1",
  "base": "PersistedModel",
  "strict": true,
  "idInjection": true,
  },
  "properties": {
    "lastMessage": {
      "type": "object",
      "required": true
    },
    "created": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    }
  },
  "relations": {
    "_lastMessage": {
      "type": "embedsOne",
      "model": "Model2",
      "property": "lastMessage",
      "options": {
        "persistent": true
      }
    }
}
```

and the model `Model2` with the following properties:

``` javascript
{
  "name": "Model2",
  "base": "PersistedModel",
  "strict": true,
  "idInjection": true
  },
  "properties": {
    "created": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    }
  }
}
```

Example of query:

``` javascript
filter: {"where": {"lastMessage.created": {"lt": "2016-05-05T10:57:36.717Z"}}, "limit": 10, "order": "lastMessage.created DESC" }}
```

The value of property `lastMessage.created` is coerced to type `String` instead of `Date`;
I use mongo connector.

**Comment by jannyHou** [comment]
@mrbatista  I am trying to reproduce your error, but seems your filter doesn't work:

I upload the app I created onto sandbox https://github.com/jannyHou/loopback-sandbox/tree/test/mongo-date
The models are built according to the json file in your comment
Open explorer try `GET/Model1s` with filter you provided:
`{"where": {"lastMessage.created": {"lt": "2016-05-05T10:57:36.717Z"}}, "limit": 10, "order": "lastMessage.created DESC" }}`

Error msg:
```
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "invalid value for argument 'filter' of type 'object': {\"where\": {\"lastMessage.created\": {\"lt\": \"2016-05-05T10:57:36.717Z\"}}, \"limit\": 10, \"order\": \"lastMessage.created DESC\" }}. Received type was string. Error: Unexpected token }",
    "statusCode": 400,
    "stack": "Error: invalid value for argument 'filter' of type 'object': {\"where\": {\"lastMessage.created\": {\"lt\": \"2016-05-05T10:57:36.717Z\"}}, \"limit\": 10, \"order\": \"lastMessage.created DESC\" }}. Received type was string. Error: Unexpected token }\n    at new badArgumentError (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:272:13)\n    at coerceAccepts (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:328:13)\n    at SharedMethod.invoke (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:221:16)\n    at HttpContext.invoke (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\http-context.js:384:12)\n    at phaseInvoke (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:645:9)\n    at runHandler (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\loopback-phase\\lib\\phase.js:130:5)\n    at iterate (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:146:13)\n    at Object.async.eachSeries (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:162:9)\n    at runHandlers (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\loopback-phase\\lib\\phase.js:139:13)\n    at iterate (C:\\Users\\IBM_ADMIN\\Desktop\\triage\\mongodate\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:146:13)"
  }
}
```
Could you fork that sandbox and provide me maybe a script in boot folder to create some instances for test.
And also make the filter work:) Thanks.

**Comment by mrbatista** [comment]
@jannyHou I have created [fork](https://github.com/mrbatista/loopback-sandbox/tree/test/mongo-date) with boot script that create some data. 
This is the correct filter: `{"where": {"lastMessage.created": {"lt": "2016-05-07T10:57:36.717Z"}}, "limit": 10, "order": "lastMessage.created DESC"}`.
Note that the filter in boot script works because property `lastMessage.created` is converted to type `Date`; doesn't works if query with explorer or angular SDK

**Comment by mrbatista** [comment]
@jannyHou Any update?

**Comment by mrbatista** [comment]
Issue resolved! 🎉 https://github.com/strongloop/loopback-datasource-juggler/pull/1361
