### ISSUE TITLE
working with  PDF files loopback storage component

### ISSUE THREAD

**Issue by m3hari** [strongloop/loopback#2520]
**How can I upload PDF files using loopback storage component?**
I have tried adding PDF content type on storage config as follows

```
  "storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./uploads",
    "allowedContentTypes": [
      "image/jpg",
      "image/jpeg",
      "image/png",
      "application/pdf"
    ]
  }
```

but it fails with the following  stacktrace

```
        exception[ERROR_SYMBOL] = context;
                                ^
TypeError: Cannot assign to read only property 'error@context' of FileTypeError: Only File of Image type is accepted.
    at IncomingMessage.<anonymous> (/project/node_modules/loopback/node_modules/continuation-local-storage/context.js:80:33)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.emitted [as emit] (/project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:759:26)
    at resume_ (_stream_readable.js:739:3)
    at /project/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at nextTickCallbackWith2Args (node.js:442:9)


```

**Comment by meharig** [comment]
There was a problem/bug on boot script . . . Sorry !
