### ISSUE TITLE
Error only in staging server : 401 AUTHORIZATION_REQUIRED for 2 requests

### ISSUE THREAD

**Issue by inv-joseph** [strongloop/loopback#2612]
Hi I have an un trackable error in staging server, locally it is working with out any error ,

Please check error and need a solution for this issue.

> {"error":{"name":"Error","status":401,"message":"Authorization Required","statusCode":401,"code":"AUTHORIZATION_REQUIRED"
,"stack":"Error: Authorization Required\n  at /var/publish-server/node_modules/loopback/lib/application
.js:394:21\n  at /var/publish-server/node_modules/loopback/lib/model.js:318:7\n  at /var/publish-server
/node_modules/loopback/common/models/acl.js:470:23\n  at /var/publish-server/node_modules/async/lib/async
.js:251:17\n  at done (/var/publish-server/node_modules/async/lib/async.js:132:19)\n  at /var/publish-server
/node_modules/async/lib/async.js:32:16\n  at /var/publish-server/node_modules/async/lib/async.js:248
:21\n  at /var/publish-server/node_modules/async/lib/async.js:572:34\n  at /var/publish-server/node_modules
/loopback/common/models/acl.js:452:17\n  at /var/publish-server/node_modules/loopback/common/models/role
.js:190:9\n  at /var/publish-server/node_modules/async-listener/glue.js:188:31\n  at /var/publish-server
/node_modules/async-listener/glue.js:188:31\n  at process._tickDomainCallback (node.js:492:13)\n  at
 process.fallback (/var/publish-server/node_modules/async-listener/index.js:482:15)\n"}}

**Comment by gunjpan** [comment]
@inv-joseph : That seems to be an issue with ACL. How's your model setup?

**Comment by gunjpan** [comment]
@inv-joseph : Closing due to inactivity. If the issue still persists and further assistance is needed, please mention me in the comments and I'll be happy to help. Thank you :)
