### ISSUE TITLE
Is it a BUG when modifying request data

### ISSUE THREAD

**Issue by namth91** [strongloop/loopback#2698]
I have an issue when modifying request data.
I can NOT reassign value or remove an attribute if it is array, but other type, e.g string, number, boolean.

**Source code:**

```
Item.beforeRemote("*.__create__posts", (ctx, nothing, next) => {
    let data = ctx.args.data

    console.log("-----\nBefore modification\n", data)

    data.title = "new title"                        // This works
    data.content = "new content"                    // This works
    data.images = "whatever type of data you want"  // But this FAILS

    console.log("-----\nAfter modification\n", data)
})
```

**Result:**

![screen shot 2016-09-01 at 12 50 39 am](https://cloud.githubusercontent.com/assets/6341961/18140194/a0a6f37a-6fde-11e6-9597-92571e8ccb56.png)

PLZ Help me! I wanna know the truth!

**Comment by nammaianh** [comment]
Yes yes! I'm facing this problem, too!

**Comment by davidcheung** [comment]
@namth91 @nammaianh  how is your remoteMethod setup, would you be able to problem a [sample repo](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) of this issue? 


## Scenario 1
when i am expecting a specified type such and then forcefully change it, 
```js
Author.remoteMethod('helloworld', {
    accepts: [
      {arg: 'str', type: 'string'},
      {arg: 'num', type: 'number'},
      {arg: 'img', type: 'array'}
    ],
    http: {
      path: '/helloworld'
    }
  });

Author.beforeRemote('helloworld', function(ctx, nothing, next) {
    ctx.args.str += ' helloworld';
    ctx.args.img = 'not array anymore';
    next();
  });
```

```
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "invalid value for argument 'img' of type 'any': not array anymore. Received type was string. Error: Unexpected token o in JSON at position 1",
    "statusCode": 400,
    "stack": "Error: invalid value for argument 'img' of type 'any': not array anymore. Received type was string. Error: Unexpected token o in JSON at position 1\n    at new badArgumentError (/Users/davidcheung/node-web/box-of-sand/node_modules/strong-remoting/lib/shared-method.js:283:13)\n    at coerceAccepts (/Users/davidcheung/node-web/box-of-sand/node_modules/strong-remoting/lib/shared-method.js:345:13)\n    at SharedMethod.invoke (/Users/davidcheung/node-web/box-of-sand/node_modules/strong-remoting/lib/shared-method.js:232:16)\n    at HttpContext.invoke (/Users/davidcheung/node-web/box-of-sand/node_modules/strong-remoting/lib/http-context.js:389:12)\n    at phaseInvoke (/Users/davidcheung/node-web/box-of-sand/node_modules/strong-remoting/lib/remote-objects.js:654:9)\n    at runHandler (/Users/davidcheung/node-web/box-of-sand/node_modules/loopback-phase/lib/phase.js:135:5)\n    at async.eachSeries.iterate (/Users/davidcheung/node-web/box-of-sand/node_modules/async/lib/async.js:146:13)\n    at Object.async.eachSeries (/Users/davidcheung/node-web/box-of-sand/node_modules/async/lib/async.js:162:9)\n    at runHandlers (/Users/davidcheung/node-web/box-of-sand/node_modules/loopback-phase/lib/phase.js:144:13)\n    at async.eachSeries.iterate (/Users/davidcheung/node-web/box-of-sand/node_modules/async/lib/async.js:146:13)"
  }
}
```

-------
## Scenario 2
when data is one big object, i have no problem overriding types inside, see the `arr` key below

```js
  Book.beforeRemote('bodyMethod', function(ctx, nothing, next) {
    var data = ctx.args.data;
    console.log('data is type: %s', typeof data);
    for (var i in data) {
      console.log('key: %s (%s)', data[i], typeof data[i]);
    };
    data.str = 123;
    //data.arr.push = 'another value';
    data.arr = 'not an array anymore';
    next();
  });

  Book.remoteMethod('bodyMethod',
    {
      accepts: [
        {arg: 'data', type: 'object'}
      ],
      http: {path: '/bodyMethod', verb: 'post'}
    }
  );
```

passing in 
`curl -H "Content-Type: application/json" -X POST -d '{ "data":{ "str":"fox jumps over something", "num":1337, "arr":["foobar"]}}' http://localhost:3000/api/Books/bodyMethod
`
```json
{
  "data": {
    "str": "fox jumps over something",
    "num": 1337,
    "arr": [
      "foobar"
    ]
  }
}
```
I get something like
```
data is type: object
key: fox jumps over something (string)
key: 1337 (number)
key: foobar (object)
received data: { str: 123, num: 1337, arr: 'not an array anymore' }
```

cc/ @richardpringle @bajtos

**Comment by nammaianh** [comment]
This remote method is a the remote method for creating a new record of the relation `posts`.

The URL is: `POST http://localhost:3000/items/:id/posts`

`images` field is just an additional field, not a field to be stored in `posts` table. I wanna use this field in the remote hook, and then unset it from request body in order to not store it.

**Comment by davidcheung** [comment]
@nammaianh would you be able to fork a sandbox to reproduce the issue? Please see https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report for more details.

**Comment by nammaianh** [comment]
Oh! Really sorry! I will do it right now

**Comment by davidcheung** [comment]
Thanks @nammaianh! I wasn't able to reproduce the issue

**Comment by davidcheung** [comment]
Trying to clean up old issues, @nammaianh were you able to reproduce this issue? please ping me here or reopen a new issue and link to this one if you can reproduce this issue, thanks
