### ISSUE TITLE
BelongsTo Relationship Include causes crash

### ISSUE THREAD

**Issue by Destreyf** [strongloop/loopback#2803]
I am making a request like this
![image](https://cloud.githubusercontent.com/assets/967304/18926916/d573bc52-8576-11e6-9b8f-79d5a870b04a.png)

and it causes the loopback api to crash.
```
C:\Projects\loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:152
        if (!arr.length) {
                ^

TypeError: Cannot read property 'length' of undefined
    at Object.async.each (C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:152:17)
    at linkOneToMany (C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\lib\include.js:812:19)
    at C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
    at _each (C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:156:9)
    at targetLinkingTask (C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\lib\include.js:808:17)
    at C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:723:21
    at C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:391:17
    at C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
    at _each (C:\KyteLearning\kyte-loopback-api\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:57:9)
```

my relationships look like this:
**course.json**
```json
    "author": {
      "type": "belongsTo",
      "model": "author",
      "foreignKey": "authorId"
    },
    "sections": {
      "type": "hasMany",
      "model": "section",
      "foreignKey": "courseId"
    },
```

**author.json**
```json
    "courses": {
      "type": "hasMany",
      "model": "course",
      "foreignKey": "authorId"
    }
```

if i do a different relationship include on courses (sections) it works fine, funny enough, if i go to my sections which has a belongs to of course, i get the same error, so either i'm defining belongs to incorrectly or there's an underlying bug in the loopback datasource juggler which results in arr being undefined.

**Comment by Destreyf** [comment]
Also, i'd like to note that i am using the postgres connector.  there's also issue #2112 which has the same error but no resolution, its specifically mentions nested relationships, but this is happening with including them.

**Comment by Destreyf** [comment]
Its also worth noting that this only happens when triggering a findById.  using find with the filter works perfectly.

**Comment by Destreyf** [comment]
I think i have something else wrong, when i do a /courses/407, i get returned course id 394 so something is wonky and not using what its supposed to.

**Comment by Destreyf** [comment]
This was caused by a mixin rewriting they "query" and basically removing the where statement causing it to have a bad query, i thought i had removed all the mixins during my testing but i had left one hanging.
