### ISSUE TITLE
TypeError: Cannot create data source "mqlight": Cannot initialize connector "mqlight": options object missing

### ISSUE THREAD

**Issue by FrankenGit** [strongloop/loopback#2861]
### Bug or feature request

- [X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Have done:
- npm install loopback-connector-mqlight --save
- apic create --type datasource

### Link to sample repo to reproduce issue (if bug)
{
  "mqlight": {
    "password": "vdm",
    "name": "mqlight",
    "service": "amqp://localhost:5672",
    "user": "vdm",
    "connector": "mqlight"
  }
}

### Additional information (Node.js version, LoopBack version, etc)
node --version
v4.4.7
apic --version
API Connect: v5.0.4.0 (apiconnect: v2.3.6)

**Comment by superkhau** [comment]
What is the expected result and actual result?

**Comment by FrankenGit** [comment]
expected result: successfull connection to mqlight
actual result:
TypeError: Cannot create data source "mqlight": Cannot initialize connector "mqlight": options object missing
    at Object.exports.createClient (/Users/de091307/git/vdm-lbneu/node_modules/loopback-connector-mqlight/node_modules/mqlight/mqlight.js:458:11)
    at MQLightConnector.connect (/Users/de091307/git/vdm-lbneu/node_modules/loopback-connector-mqlight/lib/mqlight-connector.js:98:11)
    at Object.initializeDataSource [as initialize] (/Users/de091307/git/vdm-lbneu/node_modules/loopback-connector-mqlight/lib/mqlight-connector.js:40:13)
    at DataSource.setup (/Users/de091307/git/vdm-lbneu/node_modules/loopback-datasource-juggler/lib/datasource.js:339:19)
    at new DataSource (/Users/de091307/git/vdm-lbneu/node_modules/loopback-datasource-juggler/lib/datasource.js:117:8)
    at Registry.createDataSource (/Users/de091307/git/vdm-lbneu/node_modules/loopback/lib/registry.js:355:12)
    at dataSourcesFromConfig (/Users/de091307/git/vdm-lbneu/node_modules/loopback/lib/application.js:440:19)
    at EventEmitter.app.dataSource (/Users/de091307/git/vdm-lbneu/node_modules/loopback/lib/application.js:235:14)
    at /Users/de091307/git/vdm-lbneu/node_modules/loopback-boot/lib/executor.js:190:9
    at /Users/de091307/git/vdm-lbneu/node_modules/loopback-boot/lib/executor.js:281:5

**Comment by FrankenGit** [comment]
Simon, 
I debugged into it and found the code working with the following workaround in 
node_modules/loopback-connector-mqlight/lib/mqlight-connector.js:
function MQLightConnector(config) {
  //this.settings = config.settings;
  this.settings = config;

**Comment by superkhau** [comment]
@FrankenGit Great! :+1: Would like like to submit a patch to fix it? I can help you review/land it.
