### ISSUE TITLE
Error : "Cannot redefine property: getConnection" using slc run to start a server

### ISSUE THREAD

**Issue by amerishk** [strongloop/loopback#2873]
### Bug or feature request

- [x] Bug
- [ ] Feature request
### Description

When using oracledb (node-oracle) module to establish a connection in a SLC Project, we are getting "error: uncaughtException: Cannot redefine property: getConnection ". This is happening whenever we use "SLC RUN" to start the node server. On the other than, when we use "NODE ." everything works. We asked the same issue in node-oracledb (git) (link oracle/node-oracledb#505) but got redirected to Strongloop team.

The issue is with the getConnection property of Oracledb instance present in Oracledb.js. This attribute is writable as true. If we add "configurable: true" to the getConnection property all works fine.

Can you please look into this and suggest.
Below is the sample code:

```
var oracledb = require('oracledb'); // while start-up at this line we are getting the ERROR.

oracledb.getConnection(
{
user : "test",
password : "test",
connectString : "localhost/XE"
},
function(err, connection)
{
if (err) { console.error(err.message); return; }

connection.execute(
"SELECT department_id, department_name " +
"FROM departments " +
"WHERE manager_id < :id",
[110], // bind value for :id
function(err, result)
{
if (err) { console.error(err.message); return; }
console.log(result.rows);
});
});
```
### Expected Result

Server should have started successfully without an error.
### Actual Result

On server start-up using SLC RUN Command, we are getting below error (error log):

```
error: uncaughtException: Cannot redefine property: getConnection date=Mon Oct 10 2016 21:46:43 GMT+0530 (India Standard Time), pid=11016, uid=null, gid=null, cwd=D:\Project, execPath=C:\Program Files\nodejs\node.exe, version=v4.2.3, argv=[C:\Program Files\nodejs\node.exe, server\server.js], rss=99450880, heapTotal=74440704, heapUsed=52147416, loadavg=[0, 0, 0], uptime=48725.2610621, trace=[column=null, file=null, function=Function.defineProperty, line=null, method=defineProperty, native=true, column=10, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=install, line=259, method=null, native=false, column=38, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=null, line=59, method=null, native=false, column=32, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=null, line=133, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=8, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=each, line=133, method=null, native=false, column=3, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=around, line=55, method=null, native=false, column=40, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js, function=Object.after, line=19, method=after, native=false, column=9, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js, function=oracleBase, line=20, method=null, native=false, column=10, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js, function=oracledb, line=15, method=null, native=false, column=50, file=C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\agent.js, function=Module.module.proto.require, line=188, method=module.proto.require, native=false, column=17, file=module.js, function=require, line=385, method=null, native=false, column=16, file=D:\Project\common\adapters\adapterv10\adapterv10.js, function=, line=23, method=null, native=false, column=26, file=module.js, function=Module.compile, line=435, method=compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=442, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false], stack=[TypeError: Cannot redefine property: getConnection, at Function.defineProperty (native), at install (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:259:10), at C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:59:38, at C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:133:32, at Array.forEach (native), at each (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:133:8), at around (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:55:3), at Object.after (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\proxy.js:19:40), at oracleBase (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js:20:9), at oracledb (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\probes\oracledb.js:15:10), at Module.module.__proto.require (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\lib\agent.js:188:50), at require (module.js:385:17), at Object. (D:\Project\common\adapters\adapterv10\adapterv10.js:23:16), at Module._compile (module.js:435:26), at Object.Module._extensions..js (module.js:442:10), at Module.load (module.js:356:32)]
```
### Additional information (Node.js version, LoopBack version, etc)

Node JS Version - 0.10.40 and 4.2.3 ( we tried on both versions)
loopback version - 5.0.1 and 6.0.1 (we tried on both versions)
Node-oracledb / Oracledb Versoin - 1.11
Oracle 11g XE

**Comment by jannyHou** [comment]
@amerishk We mostly move to `slc start` instead of `slc run`, please check http://loopback.io/doc/en/lb2/Running-and-debugging-apps.html

**Comment by raymondfeng** [comment]
@sam-github It seems that `oracledb.getConnection()` has `configurable` set to `false`. As a consequence, the monkey-patching technique used by `strong-agent` fails to work. What can we do here? I guess `strong-agent` should check if the property/method can be patched.

**Comment by sam-github** [comment]
I'm having trouble reproducing, so it will be hard to develop a fix.

```
npm i oracledb
...
  SOLINK_MODULE(target) Release/obj.target/oracledb.node
  COPY Release/oracledb.node
make: Leaving directory '/home/sam/w/sn/strong-agent/node_modules/oracledb/build'
strong-agent@2.1.1 /home/sam/w/sn/strong-agent
└─┬ oracledb@1.12.2 
  └── nan@2.4.0 

sn/strong-agent (master $ u=) % node lb-2873.js 
/home/sam/w/sn/strong-agent/node_modules/oracledb/lib/oracledb.js:38
    throw err;
    ^

Error: libclntsh.so.12.1: cannot open shared object file: No such file or directory
```

How do I install oracledb to reproduce? Will I need an actual oracle server, or will it fail earlier than that?

cc @bnoordhuis

**Comment by bnoordhuis** [comment]
@sam-github You probably need to set LD_LIBRARY_PATH / DYLD_LIBRARY_PATH.

@raymondfeng strong-agent checks that `.configurable` is true before trying to define a new property descriptor (function around() in lib/proxy.js.)

**Comment by raymondfeng** [comment]
@sam-github You need to follow https://github.com/oracle/node-oracledb/blob/master/INSTALL.md to have Oracle instant client installed and configured for `oracledb` to work.

**Comment by raymondfeng** [comment]
I can reproduce the problem now. 
```
2017-01-26T16:27:49.950Z pid:52625 worker:37 { value: [Function: getConnection],
2017-01-26T16:27:49.950Z pid:52625 worker:37   writable: true,
2017-01-26T16:27:49.950Z pid:52625 worker:37   enumerable: true,
2017-01-26T16:27:49.950Z pid:52625 worker:37   configurable: true }
2017-01-26T16:27:49.950Z pid:52625 worker:37 TypeError: Cannot redefine property: getConnection
2017-01-26T16:27:49.950Z pid:52625 worker:37     at Function.defineProperty (native)
2017-01-26T16:27:49.950Z pid:52625 worker:37     at install (/Users/rfeng/.nvm/versions/node/v6.9.4/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:274:10)
2017-01-26T16:27:49.950Z pid:52625 worker:37     at /Users/rfeng/.nvm/versions/node/v6.9.4/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:66:38
```

**Comment by sam-github** [comment]
node version?

**Comment by raymondfeng** [comment]
6.9.4

**Comment by bnoordhuis** [comment]
If I had to venture a guess I'd say the object has been frozen or sealed.  Does this patch help?
```diff
diff --git a/lib/proxy.js b/lib/proxy.js
index 66c5afe..eb8dcce 100644
--- a/lib/proxy.js
+++ b/lib/proxy.js
@@ -265,10 +265,12 @@ function install(object, method, des, proxy) {
     return;
   }
   var newdes = {
     configurable: true,
     enumerable: des.enumerable,
     writable: des.writable,
     value: proxy,
   };
-  Object.defineProperty(object, method, newdes);
+  if (Object.isExtensible(object)) {
+    Object.defineProperty(object, method, newdes);
+  }
 }
```

**Comment by priyavivek1** [comment]
if we update node oracledb module oracledb.js file with property Configurable : TRUE in getConnection, it works fine. 
So following comment is correct:
"@raymondfeng strong-agent checks that .configurable is true before trying to define a new property descriptor (function around() in lib/proxy.js.)"

@sam-github : we use nodeversion 0.10.39 currently.

**Comment by sam-github** [comment]
I've reproduced this, and found a fix, I'll look at Ben's suggestion above, too.

**Comment by sam-github** [comment]
I have submitted a fix, it is under review.

**Comment by sam-github** [comment]
Fixed in https://www.npmjs.com/package/strong-agent v2.1.2

I'm not sure what version of strong-pm or strongloop you are using, I may need to backport the fix to 1.x.

**Comment by sam-github** [comment]
strongloop 5.x is now using strong-agent@2.1.2

**Comment by priyavivek1** [comment]
We are using strongloop 5.0.0 currently. it should work. Thanks

**Comment by sam-github** [comment]
@priyavivek1 can you confirm that it did in fact work?

**Comment by priyavivek1** [comment]
@sam-github : it worked for us. Till now, no problems reported. the exception is not coming and the issue has been resolved.
