### ISSUE TITLE
Context example should be deleted

### ISSUE THREAD

**Issue by tomers** [strongloop/loopback#2965]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Context example (`example/context`) should be deleted in version 3.0.
```
~/dev/loopback/example/context$ node app.js 
/home/tomer/dev/loopback/server/middleware/context.js:9
  throw new Error(g.f(
  ^

Error: loopback#context middleware was removed in version 3.0. See http://loopback.io/doc/en/lb2/Using-current-context.html for more details.
    at Function.module.exports [as context] (/home/tomer/dev/loopback/server/middleware/context.js:9:9)
    at Object.<anonymous> (/home/tomer/dev/loopback/example/context/app.js:11:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by Amir-61** [comment]
Fixed by https://github.com/strongloop/loopback/pull/2972

Thanks!
