### ISSUE TITLE
Mobile-models example application does not start

### ISSUE THREAD

**Issue by tomers** [strongloop/loopback#2966]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

models file is missing. The following log explains the bug:

```
~/dev/loopback/example/mobile-models$ node app.js 
module.js:474
    throw err;
    ^

Error: Cannot find module '../../lib/models'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tomer/dev/loopback/example/mobile-models/app.js:7:14)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by 0candy** [comment]
@gunjpan Missed this example when making update to `app.model`.
https://github.com/strongloop/loopback/pull/2401

**Comment by pthieu** [comment]
Possible duplicate of https://github.com/strongloop/loopback/issues/2967 (different app)
