### ISSUE TITLE
Replication example application is broken

### ISSUE THREAD

**Issue by tomers** [strongloop/loopback#2967]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

```
~/dev/loopback/example/replication$ node app.js 
loopback deprecated The model color is tracking changes, which requries a string id with GUID/UUID default value. events.js:292:16
createSomeInitialSourceData
replicateSourceToTarget
bound list
current SOURCE data
 - red
 - blue
 - green

bound list
current TARGET data

updateSomeTargetData
/home/tomer/dev/loopback/example/replication/app.js:95
    color.name = 'conflict';
               ^

TypeError: Cannot set property 'name' of null
    at /home/tomer/dev/loopback/example/replication/app.js:95:16
    at /home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:2007:62
    at /home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1936:9
    at /home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at async.each (/home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
    at _asyncMap (/home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)
    at Object.map (/home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)
    at allCb (/home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:1855:13)
    at /home/tomer/dev/loopback/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:473:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by 0candy** [comment]
@gunjpan Missed this example when making update to `app.model`.
https://github.com/strongloop/loopback/pull/2401

**Comment by gunjpan** [comment]
@0candy : It's not due to changes in #2401. Investigating

**Comment by pthieu** [comment]
Possible duplicate of https://github.com/strongloop/loopback/issues/2966 (different app)
