### ISSUE TITLE
Error using remoteMethod Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by asaf050** [strongloop/loopback#3009]
Hey,
I'm getting error while access the remote method via REST. here's my remote method:
```
function checkout(id, fk, quantity, serials, cb) {
        cb();
    };
    Kit.remoteMethod(
        'checkout', {
            description: 'Checkout quantity/serials of spesific kit item',
            accepts: [
                { arg: 'id', type: 'string', required: true },
                { arg: 'fk', type: 'string', required: true },
                { arg: 'quantity', type: 'number', required: true },
                { arg: 'serials', type: 'object' }
            ],
            returns: { root: true },
            http: { path: '/:id/kits/:fk/checkout', verb: 'post' }
        }
    );

```
The error i'm getting is:
```
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "Cannot read property 'apply' of undefined",
    "stack": "TypeError: Cannot read property 'apply' of undefined\n    at SharedMethod.invoke (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\shared-method.js:263:24)\n    at HttpContext.invoke (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\http-context.js:389:12)\n    at phaseInvoke (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\remote-objects.js:654:9)\n    at runHandler (d:\\nextplus3\\node_modules\\loopback-phase\\lib\\phase.js:135:5)\n    at iterate (d:\\nextplus3\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:146:13)\n    at Object.async.eachSeries (d:\\nextplus3\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:162:9)\n    at runHandlers (d:\\nextplus3\\node_modules\\loopback-phase\\lib\\phase.js:144:13)\n    at iterate (d:\\nextplus3\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:146:13)\n    at d:\\nextplus3\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:157:25\n    at d:\\nextplus3\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:154:25\n    at execStack (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\remote-objects.js:493:7)\n    at d:\\nextplus3\\node_modules\\loopback-component-logger\\lib\\hooks\\remoteHook.js:16:13\n    at Function.<anonymous> (d:\\nextplus3\\node_modules\\loopback\\lib\\model.js:205:18)\n    at execStack (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\remote-objects.js:485:26)\n    at RemoteObjects.execHooks (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\remote-objects.js:497:10)\n    at phaseBeforeInvoke (d:\\nextplus3\\node_modules\\strong-remoting\\lib\\remote-objects.js:650:10)"
  }
}

```

**Comment by b-admike** [comment]
Hi @asaf050, can you give me the steps you took to reproduce this issue? I am trying to reproduce locally.

**Comment by asaf050** [comment]
Hey,

I changed the 
`function checkout (..)`
to `Modelname.checkout(..)`

Works now, Thanks!
Closing the issue.

**Comment by b-admike** [comment]
Awesome! I suspected that but also my app didn't have `strong-remoting` as a dep and I wanted to find out what was happening there from your trace.
