### ISSUE TITLE
HttpContext.prototype.getArgByName show not pollute the body.

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback#3025]
args = JSON.parse(args);

```
   SyntaxError: Unexpected token o in JSON at position 1
            at Object.parse (native)
            at HttpContext.getArgByName (C:\CI-Cor\acrop\acrop\node_modules\strong-remoting\lib\http-context.js:244:17)
            at HttpContext.buildArgs (C:\CI-Cor\acrop\acrop\node_modules\strong-remoting\lib\http-context.js:174:17)
            at new HttpContext (C:\CI-Cor\acrop\acrop\node_modules\strong-remoting\lib\http-context.js:58:20)
            at restStaticMethodHandler (C:\CI-Cor\acrop\acrop\node_modules\strong-remoting\lib\rest-adapter.js:447:15)
            at Layer.handle [as handle_request] (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\layer.js:95:5)
            at next (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\route.js:131:13)
            at Route.dispatch (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\route.js:112:3)
            at Layer.handle [as handle_request] (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\layer.js:95:5)
            at C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:277:22
            at param (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:349:14)
            at param (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:365:14)
            at Function.process_params (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:410:3)
            at next (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:271:10)
            at Function.handle (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:176:3)
            at router (C:\CI-Cor\acrop\acrop\node_modules\express\lib\router\index.js:46:12)
LOG: 'The body is:', '{}'
```

I have a custom command that have args as it's attribute.

**Comment by bosco-li** [comment]
@lygstate Thank you for asking.  We will need more information on what you did to be able to reproduce this issue.  Can you please provide a sample code for us?
