### ISSUE TITLE
How to make sure the uniqueness of indexes

### ISSUE THREAD

**Issue by lygstate** [strongloop/loopback#3037]
### Bug or feature request
- [X] Bug
- [X ] Feature request

### Description of feature (or steps to reproduce if bug)
The following is my model description.
```
  "indexes": {
    "ackId_deviceId_index": {
      "keys": {
        "ackId": 1,
        "deviceId": 1
      },
      "options": {
        "unique": true
      }
    }
  },
  "validations": [],
```
And when I insert duplicated ackId join with deviceId
loopback doesn't raise error for me.

**Comment by dancingshell** [comment]
@lygstate are you using memory connector? I noticed when running my tests through the memory connector it doesn't throw index errors, but using the postgres connector it will throw a uniqueness error

**Comment by lygstate** [comment]
I am using MongoDB

**Comment by kjdelisle** [comment]
@lygstate Sorry for the delay, we've got quite the backlog to churn through!

I've reproduced what you're seeing here, but only when I use a model that hasn't been migrated to the target datasource.

If I use the automigrate feature, it correctly creates the index as defined in the model and enforces the constraint.

For example, I have a model definition for a Widget:
```
{
  "name": "Widget",
  "base": "PersistedModel",
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "widgetId": {
      "type": "number"
    },
    "vendorId": {
      "type": "number",
      "required": "true"
    },
    "name": {
      "type": "string"
    },
    "inventedOn": {
      "type": "date"
    }
  },
  "indexes": {
    "widget_vendor_index": {
      "keys": {
        "widgetId": 1,
        "vendorId": 1
      },
      "options": {
        "unique": true
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

Automigrating this definition to my datasource and then attempting to insert two records with the same `widgetId` and `vendorId` will fail.

In MongoDB:
```
Unhandled error for request POST /api/Widgets: MongoError: E11000 duplicate key error collection: mongo.Widget index: widget_vendor_index dup key: { : 123, : 123 }
    at Function.MongoError.create (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mongodb/lib/utils.js:139:22)
    at /Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mongodb/lib/collection.js:659:23
    at handleCallback (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at /Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mongodb-core/lib/connection/pool.js:461:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

In PostgreSQL:
```
Unhandled error for request POST /api/Widgets: error: duplicate key value violates unique constraint "widget_vendor_index"
    at Connection.parseE (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

In MySQL:
```
Unhandled error for request POST /api/Widgets: Error: ER_DUP_ENTRY: Duplicate entry '123-123' for key 'widget_vendor_index'
    at Query.Sequence._packetToError (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/kevin/dev/sandbox/test-index-uniqueness/node_modules/mysql/lib/Connection.js:103:28)
```

**Comment by kjdelisle** [comment]
Please let me know if this resolves your issue.

**Comment by lygstate** [comment]
OK I Will try it , does this need the master version of loopback?

**Comment by kjdelisle** [comment]
Sorry, we had some interesting difficulties related to switching labels for our team tasks, and this item fell through!  I'm assuming that you've had some success with this, so I'm closing this issue. Please let me know if you're still stuck, and I'll reopen this.
