### ISSUE TITLE
[2.0] Calling findOrCreate causes an UnAttached exception to be thrown even though model is attached to a data-source

### ISSUE THREAD

**Issue by kraman** [strongloop/loopback#311]
```
var loopback = require('loopback'); 
var ds = loopback.createDataSource('memory');
var foo = ds.createModel("Foo");
foo.findOrCreate( {a:1}, {a:2}, function(){ console.log(arguments) });

Error: Cannot call Foo.findOrCreate(). The findOrCreate method has not been setup. The DataModel has not been correctly attached to a DataSource!
    at throwNotAttached (/root/krishnaraman.net/blog2/node_modules/loopback/lib/models/data-model.js:63:9)
    at Function.findOrCreate (/root/krishnaraman.net/blog2/node_modules/loopback/lib/models/data-model.js:122:3)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
```

**Comment by wesleymilan** [comment]
I'm having the same issue using remote connector and lasted versions
"loopback": "^2.22.0",
"loopback-boot": "^2.14.0",
"loopback-connector-remote": "^1.0.3",
"loopback-datasource-juggler": "^2.41.1",

**Comment by superkhau** [comment]
@wesleymilan Please open your own issue since this issue is already closed.
