### ISSUE TITLE
context issue: 'invoke' runs after createOptionsFromRemotingContext

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3205]
Consider the code below, its not yet a running test tho because I can see from the output that invoke is triggered after 'createOptionsFromRemotingContext' according to the example found on https://loopback.io/doc/en/lb3/Using-current-context.html.

> Applications can define a custom phase to run code before any remote hooks are invoked, such code can be placed in a boot script for example.

Not working.

```
describe('Test', function () {

    // Wait extension
    this.timeout(10000);


    before(function (done) {
        // Init phase
        server.remotes().phases
            .addBefore('invoke', 'options-from-request')
            .use(function (ctx, next) {
                console.log("Invoke")
                ctx.args.options.foo = 'bar';
                next();
            });

        // Boot server
        boot(server, __dirname + "/../../server/", function (err) {

            server.models.bdata.remoteMethod(
                'testRemoteOptions',
                {
                    accepts: [
                        {arg: "options", type: "object", http: "optionsFromRequest"}
                    ],
                    returns: {arg: 'item', type: 'object'},
                    http: {path: '/test/remote', verb: 'get'},
                    notes: "Queries arbitrary aggregate objects from the database"
                }
            );

            server.models.bdata.testRemoteOptions = function (options, cb) {
                cb(null, {options: options});
            }

            server.models.bdata.remoteMethod(
                'testRemoteHook',
                {
                    accepts: [
                        {arg: "options", type: "object", http: "optionsFromRequest"}
                    ],
                    returns: {arg: 'item', type: 'object'},
                    http: {path: '/test/hook', verb: 'get'},
                    notes: "Queries arbitrary aggregate objects from the database"
                }
            );

            server.models.bdata.testRemoteHook = function (options, cb) {
                server.models.bdata.create({
                    foo: '1'
                }, options, function (err, result) {
                    console.log("Create done", err, result)
                    cb(null, {ok: 1});
                })

            }
            server.models.bdata.createOptionsFromRemotingContext = function (ctx) {
                var base = this.base.createOptionsFromRemotingContext(ctx);
                console.log("Base", base); // this runs before 'invoke'... WHY?
                return base;
            };

            done();
        });
    })

    it('Operation Hook: Should return options object', function (done) {
        server.models.bdata.observe('before save', function (ctx, next) {
            console.log("before save ophook")
            console.log(ctx.options);
        });
        request(server)
            .get('/api/bdata/test/hook')
            .set('Accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200, done);
    })
```

tracing out createOtionsFromRemotingContext... // MAN WHY SUCH LONG NAME??? //
```
 at Function.server.models.bdata.createOptionsFromRemotingContext (api\test\api\options.test.js:84:25)
 at createOptionsViaModelMethod (api\node_modules\loopback\lib\model.js:495:22)
 at HttpContext.buildArgs (pi\node_modules\strong-remoting\lib\http-context.js:137:17)
 at new HttpContext (api\node_modules\strong-remoting\lib\http-context.js:57:20)
```

so exactly what is the trigger, event, or hook that I can listen to so can manipulate the args.options object before ANYTHING runs? Just because the example given is not working as expected.

**Comment by PhanindraKumar** [comment]
Hi @barocsi  Did you find any event or hook  to manipulate args.options.  How to make that example working.
