### ISSUE TITLE
Loopback api error

### ISSUE THREAD

**Issue by hester113** [strongloop/loopback#3399]
Loopback
404 Error: Cannot GET /explorer
   at raiseUrlNotFoundError (/home/augustins/backend/node_modules/loopback/server/middleware/url-not-found.js:20:17)
   at Layer.handle [as handle_request] (/home/augustins/backend/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/augustins/backend/node_modules/express/lib/router/index.js:317:13)
   at /home/augustins/backend/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/home/augustins/backend/node_modules/express/lib/router/index.js:335:12)
   at next (/home/augustins/backend/node_modules/express/lib/router/index.js:275:10)
   at compression (/home/augustins/backend/node_modules/compression/index.js:219:5)
   at Layer.handle [as handle_request] (/home/augustins/backend/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/augustins/backend/node_modules/express/lib/router/index.js:317:13)
   at /home/augustins/backend/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/home/augustins/backend/node_modules/express/lib/router/index.js:335:12)
   at next (/home/augustins/backend/node_modules/express/lib/router/index.js:275:10)
   at favicon (/home/augustins/backend/node_modules/serve-favicon/index.js:63:7)
   at Layer.handle [as handle_request] (/home/augustins/backend/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/augustins/backend/node_modules/express/lib/router/index.js:317:13)
   at /home/augustins/backend/node_modules/express/lib/router/index.js:284:7

**Comment by raymondfeng** [comment]
How did you scaffold the loopback application? Do you see the following content in `server/component-config.json`?
```json
{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  }
```

**Comment by hester113** [comment]
sure, This app is running in Nginx server.
This is my configuration.
upstream api_upstream {
	server 127.0.0.1:3001;
	keepalive 64;
}

server {
	listen 80;
	
	server_name api.augustins.digidustlabs.com;	
	location /v1 {		
		proxy_redirect off;
		proxy_set_header   X-Real-IP            $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto $scheme;
		proxy_set_header   Host                   $http_host;
		proxy_set_header   X-NginX-Proxy    true;
		proxy_set_header   Connection "";
		proxy_set_header   Content-Type "application/json";
		add_header Content-Type "application/json";
		add_header Access-Control-Allow-Origin *;
		add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept";		
		proxy_http_version 1.1;
		#proxy_cache one;
		proxy_cache_key sfs$request_uri$scheme;
		proxy_pass         http:/api_upstream;
		
	}
    	location /explorer {
       		 proxy_redirect off;
       		 proxy_set_header X-Real-IP $remote_addr;
       		 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       		 proxy_set_header X-Forwarded-Proto $scheme;
       		 proxy_set_header host $http_host;
       		 proxy_set_header X-NginX-Proxy true;
       		 proxy_set_header Connection "";
       		 proxy_http_version 1.1;
       		 #proxy_cache one;
       		 proxy_cache_key sfs$request_uri$scheme;
       		 proxy_pass http://api_upstream;
   		 }

location ~* \.(eot|ttf|woff|woff2)$ {
	add_header Access-Control-Allow-Origin *;
	}


}
Are there any errors in this setting?
If so, how to fix it?
Sorry for my broken English.
Anyway, thanks for your kind reply

**Comment by hans118** [comment]
Hi Raymond, I have same error on my server.
How to fix it?
