### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by veenaramu** [strongloop/loopback#3404]
I am running into this issue while trying to  generate models from the SOAP data source

# Description/Steps to reproduce

$ lb soap

? Select the datasource for SOAP discovery findclaimds
WSDL for datasource findclaimds: C:\\Users\gok9kur\FindClaim\DocumentIndexingAPI_AAA.wsdl
? Select the service: DocumentIndexingAPI_AAA
? Select the binding: DocumentIndexingAPI_AAASoap11Binding
? Select operations to be generated: (Press <space> to select, <a> to toggle all, <i> to inverse selection)searchClaim
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'add' of undefined
    at Function.createEnvelopeDescriptor (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-soap\src\parser\wsdl\operation.js:330:25)
    at Operation.describe (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-soap\src\parser\wsdl\operation.js:229:17)
    at getParameters (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:211:39)
    at getOperationInfo (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:168:19)
    at getAPIData (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:152:15)
    at BaseGenerator.generateRemoteMethods (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:104:17)
    at Object.exports.generateRemoteMethods (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\index.js:22:25)
    at Object.generateAPICode (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\generator-loopback\soap\wsdl-loader.js:87:28)
    at constructor.generate (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\generator-loopback\soap\index.js:186:27)
    at Object.<anonymous> (C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\run-async\index.js:25:25
    at C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\run-async\index.js:24:19
    at C:\Users\gok9kur\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\yeoman-generator\lib\base.js:432:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Here are the version of loopback and npm I am using

>lb -version
2.5.0 (generator-loopback@3.6.0 loopback-workspace@3.40.1)

>npm -version
3.10.10

Thank you.

**Comment by veenaramu** [comment]
appreciate your help, any suggestions?

**Comment by siddhipai** [comment]
Hi @veenaramu , Can you send me the wsdl and any xsd schema it imports.

**Comment by rashmihunt** [comment]
@veenaramu is this still an issue. If yes, can you send your WSDL and any schema it imports?

**Comment by freeart** [comment]
Yes, a problem is still this
[EXT-CD-1.12.zip](https://github.com/strongloop/loopback/files/1095183/EXT-CD-1.12.zip)
