### ISSUE TITLE
Still not able to load datasources file

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback#3441]
hi @archenroot @0candy same in #2026 . here is my setup

├── loopback@3.8.0
├── loopback-boot@3.0.0
├── loopback-component-explorer@4.2.0
├── loopback-component-push@3.0.0
├── loopback-component-storage@3.2.0
├── loopback-connector-mongodb@3.1.0
├── loopback-connector-mysql@3.0.0
├── loopback-connector-postgresql@3.0.1
├── loopback-connector-redis@0.1.0
├── loopback-connector-rest@2.1.0
├── loopback-context@3.1.0
├── loopback-datasource-juggler@3.6.1

I also got the error from loading datasources
I have set NODE_ENV=production
darwin x64 node js 6.9.5

I have setup mode-config.production.json with the correct configurations but it still failed.
The datasource file is [here](https://github.com/ONode/salisgallia/blob/preproduction/server/datasources.production.js)

Unhandled rejection AssertionError: AccessToken is referencing a dataSource that does not exist: "rocket_us_east"

the error is raised from using async-hook
```

warning: you are using async-hook which is unstable.
Unhandled rejection AssertionError: AccessToken is referencing a dataSource that does not exist: "rocket_us_east"
    at configureModel (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/loopback/lib/application.js:526:5)
    at EventEmitter.app.model (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/loopback/lib/application.js:126:5)
    at /Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/loopback-boot/lib/plugins/model.js:310:9
    at Array.forEach (native)
    at Model.start (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/loopback-boot/lib/plugins/model.js:306:16)
    at executePluginPhase (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/loopback-boot/lib/bootstrapper.js:166:39)
    at /Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/async/dist/async.js:3060:16
    at replenish (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/async/dist/async.js:931:17)
    at /Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/async/dist/async.js:906:16
    at onPluginPhaseResolved (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/loopback-boot/lib/bootstrapper.js:169:13)
    at tryCatcher (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Volumes/RAMDISK/backends/loopback-backend-gallerio/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by 0candy** [comment]
What did you set as the value of `process.env.ROCKET_EAST`?
