### ISSUE TITLE
Cant add relations on before save hook

### ISSUE THREAD

**Issue by george-oakling** [strongloop/loopback#3466]
# Description/Steps to reproduce

Having two models which are related to each other by hasAndBelongsToMany, eg. Foo and Bar, I cant add relations to each other in on before save hook if its new instance. It ends up with error.

foo.js
```
module exports = function(Foo) {
   Foo.observe('before save', function(ctx, next) {
      if(ctx.isNewInstance) {
         Foo.app.models.Bar.find({}, function(err, bars) {
            if(err) {
               console.log(err);
            } else {
               ctx.instance.bars.add(bars);
            }
            next();
         }
      }
   })
```

# Expected result
Foo has all available Bar models.

# Actual result
```
/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:432
  var nodes = Object.keys(this.collection(model)).map(function(key) {
                     ^

TypeError: Cannot convert undefined or null to object
    at Memory._findAllSkippingIncludes (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:432:22)
    at Memory.findOrCreate (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:328:20)
    at /home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/dao.js:1160:19
    at doNotify (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at _findOrCreate (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/dao.js:1154:11)
    at /home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/dao.js:1223:13
    at ModelConstructor.<anonymous> (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/validations.js:528:11)
    at ModelConstructor.next (/home/jirka/NodeProjects/api/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
```

**Comment by george-oakling** [comment]
Any news on this? Am I doing the addition wrongly?

**Comment by germanamz** [comment]
This issue is thrown when you don't have any user registered and you try to make a find on the collection, this only exist with the memory connector and the User model or any of its model childs.
