### ISSUE TITLE
Unhandled error for request GET /__webpack_hmr

### ISSUE THREAD

**Issue by lcaprini** [strongloop/loopback#3614]
I created a new loopback app with app generator and without any change I run `node .`
I have the following error every 3/4 seconds:
```
Unhandled error for request GET /__webpack_hmr: Error: Cannot GET /__webpack_hmr
    at raiseUrlNotFoundError (/Users/Masterplan/Development/loopback/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:317:13)
    at /Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:275:10)
    at /Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:635:15
    at next (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:317:13)
    at /Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Masterplan/Development/loopback/node_modules/express/lib/router/index.js:275:10)
    at nosniff (/Users/Masterplan/Development/loopback/node_modules/dont-sniff-mimetype/index.js:4:5)
```

**Comment by StillOnMyWay** [comment]
Is noone able to address this?

**Comment by 501army** [comment]
any solution for this problem ? i have some problem too
