### ISSUE TITLE
Change Password throwing wierd error

### ISSUE THREAD

**Issue by rahulrsingh09** [strongloop/loopback#3622]
```
Web server listening at: http://localhost:8080
Browse your REST API at http://localhost:8080/explorer
Unhandled error for request POST /api/users/change-password?access_token=J7IJxUjR0FZ8ew2Q7gaUEuySF08VodmrkxOGuC1RVCm6pRgqM9Cd3TdS2sEjQkx3: Error: Model::findById requires the id argument
    at /home/rahul/DSP/dsp-api/node_modules/loopback-datasource-juggler/lib/dao.js:1370:10
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```
Login is working fine

**Comment by shimks** [comment]
change-password didn't throw any errors for me.
Here are the dependencies I'm using:

outfit-uploader@1.0.0 /Users/kyusungshim/dev/project/outfit-uploader
├── eslint-config-loopback@8.0.0
├── loopback@3.11.1
├── loopback-boot@2.26.1
├── loopback-component-explorer@5.0.0
├── loopback-connector-mongodb@1.18.1
