### ISSUE TITLE
Error: `msbuild` failed with exit code: 1

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#3663]
# Description/Steps to reproduce

```
$ npm install -g loopback-cli
```

# Expected result

Unknown since the package throws during initial installation from the very start

# Additional information

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10240 N/A Build 10240
System Type:               x64-based PC

Node v6.3.1
npm 4.0.2

# Error

```
$ npm install -g loopback-cli
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
C:\Users\user\AppData\Roaming\npm\lb -> C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\bin\loopback-cli.js

> ursa@0.9.4 install C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa
> node-gyp rebuild


C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
..\src\ursaNative.cc(157): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(378): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(379): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(686): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(734): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(779): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(826): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(945): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1003): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\user\AppData\Roaming\npm
`-- loopback-cli@4.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\loopback-cli\node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by imohsenb** [comment]
Please install OpenSSl-Win64 from [Here](https://slproweb.com/products/Win32OpenSSL.html) or [DirectHere](https://slproweb.com/download/Win64OpenSSL-1_0_2m.exe) with path of **C:\OpenSSL-Win64** and select **The OpenSSL binaries /bin directory** option. then try **npm install -g loopback-cli** again.

**Comment by urig** [comment]
I've just experienced this exact same issue on my Windows 10 machine. I think the issue should be reopened because other people are likely experiencing it and abandoning loopback before even trying it.

If the issue cannot be resolved automatically through npm then I would suggest that at least instructions to install OpenSSL-Win64 (and where to download it from) would be added to the loopback [Getting Started ](https://loopback.io/getting-started/) guide.
