### ISSUE TITLE
No validation on DataSourceDefinition when adding in a database connector

### ISSUE THREAD

**Issue by piotrekkmt** [strongloop/loopback#3780]
# Description/Steps to reproduce

No validation done on naming the DataSource definition when creating a database connector to overwrite the default in memory db connector.

### Steps to reproduce:

**~/Development/git/db2-playground    lb datasource**
```
? Enter the datasource name: db
? Select the connector for db: IBM DashDB (supported by StrongLoop)
? Connection String dsn to override other settings (eg: DATABASE=MY_DB;HOSTNAME=MY_HOST;PORT=MY_PORT;PROTOCOL=TCPIP;UID=MY_UID;PWD=MY_PWD)): 
DATABASE=BLUDB;HOSTNAME=dashdb-xxxxxxxxxxx.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;UID=xxxxxxxxxxx;PWD=xxxxxxxxxxx;
? host: dashdb-xxxxxxxxxxx.services.dal.bluemix.net
? port: 50000
? user: xxxxxxxxxxx
? password: xxxxxxxxxxx
? database: xxxxxxxxxxx
```

# Link to reproduction sandbox

Local MacOS environment with node 6.11 installed. Versions below.

# Expected result

Created or overwritten db connector in ./server/datasources.json 

# Actual result

Console error:

```
Validation error: invalid DataSourceDefinition
 - name: is not unique

events.js:160
      throw er; // Unhandled 'error' event
      ^
ValidationError: The `DataSourceDefinition` instance is not valid. Details: `name` is not unique (value: "db").
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:330:12
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:511:13)
    at ModelConstructor.next (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/hooks.js:82:12)
    at done (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:508:25)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:586:7
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:380:5)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:2009:11
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at done (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:1986:17
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)

```

# Additional information

**~/Development/git/db2-playground    lb --version**
`4.1.0 (generator-loopback@5.5.0 loopback-workspace@4.0.0)`

**~/Development/git/db2-playground      node -e 'console.log(process.platform, process.arch, process.versions.node)'**
`darwin x64 6.11.0`

**~/Development/git/db2-playground      npm ls --prod --depth 0 | grep loopback**
```
├── loopback@3.18.0
├── loopback-boot@2.27.0
├── loopback-component-explorer@5.2.0
├── loopback-connector-dashdb@2.0.2
```

**Comment by mcolburn** [comment]
I also get this error.  Would someone please address it.
