### ISSUE TITLE
Error downloading file

### ISSUE THREAD

**Issue by jkunwar** [strongloop/loopback#3817]
```
TypeError: res.type is not a function
    at download (/Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback-component-storage/lib/storage-handler.js:257:9)
    at Object.exports.download (/Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback-component-storage/lib/storage-handler.js:242:12)
    at StorageService.download (/Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback-component-storage/lib/storage-service.js:280:18)
    at /Applications/XAMPP/xamppfiles/htdocs/epechaweb/common/models/epecha-file.js:155:43
    at /Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:2111:9
    at /Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Applications/XAMPP/xamppfiles/htdocs/epechaweb/node_modules/loopback/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
```

my remote method is

```js
Epechafile.downloadFile = function(container, file, ctx, res, cb){
    var fileName = file;
    var container = container;
    Epechafile.find({where:{fileName: fileName, container: container}}, function(err, result){
      if(err) {
        cb(err);
      }
      else {
        if(result[0].isPublic == false){
          var error = {
            "message": "Authorization required",
            "statusCode": 401
          }
          cb(error);
        }else{
          Epechafile.app.models.Container.download(container, file, res, cb);
        }
      }
    });
  }

  Epechafile.remoteMethod('downloadFile', {
    description: 'Download authorized files.',
    accepts: [
      {arg: 'container', type: 'string', required: 'true'},
      {arg: 'file', type: 'string', required: 'true'},
      {arg: 'ctx', type: 'object', http: {source: 'context'}},
      {arg: 'res', type: 'object', 'http': {source: 'res'}}
    ],
    isStatic: true,
    returns: [
      { arg: 'body', type: 'file', root: true },
      { arg: 'Content-Type', type: 'string', http: { target: 'header' } },
    ],
    http: {path: '/:container/download-file/:file', verb: 'get'}
  });
```

**Comment by bajtos** [comment]
Hello, I don't see any obvious problem. Could you please create a small application reproducing this issue in isolation? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by jkunwar** [comment]
i have figured out solution for this. thank you for the response though :)

**Comment by jkunwar** [comment]
hello @arnaud-git  I haven't created remote method instead use same URL , and open file by using arraybuffer

**Comment by pookdeveloper** [comment]
I have the same error:
My code:
````javascript
  Documentos.get_document = function (req, res, options, tipo, id_registro, data, cb) {
    console.log(`------->: Documentos.get_document -> Documentos.getFile`, Documentos.getFile);
    id_registro = "8362bd07-8823-4dd9-b0d2-c63aca97dcf0.pdf";
    Documentos.download(tipo, id_registro, res, function (err, data) {
      if (err) {
        cb(err);
      } else {
        cb(data);
      }
    });
  };
````

**Comment by pookdeveloper** [comment]
Like this it works for me:
Documentos.get_document = function (req, res, options, tipo, id_registro, data, cb) {
    console.log(`------->: Documentos.get_document -> Documentos.getFile`, Documentos.getFile);
    id_registro = "8362bd07-8823-4dd9-b0d2-c63aca97dcf0.pdf";
    Documentos.download(tipo, id_registro, req, res);
  };
