### ISSUE TITLE
lb soap - failed to parse wsdl

### ISSUE THREAD

**Issue by Tiberriver256** [strongloop/loopback#3881]
# Description/Steps to reproduce

Following the steps listed here: https://loopback.io/doc/en/lb3/Connecting-to-SOAP.html

When I run the command ```lb soap``` on the attached wsdl I get the following error:

```
events.js:183
      throw er; // Unhandled 'error' eventChangeDNDStatus
      ^

TypeError: Cannot read property '$name' of undefined
    at buildElementProperties (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:314:76)
    at buildElementProperties (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:327:7)
    at getModels (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:270:5)
    at BaseGenerator.generateModels (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\lib\codegen\generator-soap.js:141:16)
    at Object.exports.generateModels (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-soap\index.js:43:25)
    at Object.generateAPICode (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\generator-loopback\soap\wsdl-loader.js:88:30)
    at constructor.generate (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\generator-loopback\soap\index.js:186:27)
    at Object.<anonymous> (C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\yeoman-generator\lib\base.js:439:23)
    at C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\run-async\index.js:24:19
    at C:\Users\wmrm\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\yeoman-generator\lib\base.js:440:9
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
[wsdl.zip](https://github.com/strongloop/loopback/files/2010583/wsdl.zip)

**Comment by Tiberriver256** [comment]
@rashmihunt - Let me know if it would be better to open the issue here:
https://github.com/strongloop/loopback-soap
