### ISSUE TITLE
Unhandled error for request GET /explorer/null: Error: Cannot GET /explorer/null

### ISSUE THREAD

**Issue by J-Siu** [strongloop/loopback#3887]
# Description/Steps to reproduce

Follow loopback getting start instruction at : http://loopback.io/getting-started/

After starting the app at the end, open browser and connect to http://localhost:3000/explorer

Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Unhandled error for request GET /explorer/null: Error: Cannot GET /explorer/null
    at raiseUrlNotFoundError (/Users/js/code/nobackup/test-loopback/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:317:13)
    at /Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:275:10)
    at /Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:635:15
    at next (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:317:13)
    at /Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:635:15)

# Link to reproduction sandbox
This is from loopback official getting start page. 

# Expected result

Not expect any error show in terminal. But get following:

Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Unhandled error for request GET /explorer/null: Error: Cannot GET /explorer/null
    at raiseUrlNotFoundError (/Users/js/code/nobackup/test-loopback/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:317:13)
    at /Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:275:10)
    at /Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:635:15
    at next (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:317:13)
    at /Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Users/js/code/nobackup/test-loopback/node_modules/express/lib/router/index.js:635:15)

# Additional information

darwin x64 8.11.2
test-loopback@1.0.0 /Users/js/code/nobackup/test-loopback
├── loopback@3.19.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.0.1
js@js-imac-pro [00:12:34] [~/code/nobackup/test-loopback]

**Comment by jannyHou** [comment]
Hi @J-Siu which version of nodejs are you using?

**Comment by J-Siu** [comment]
I tried with both 8.11 the LTS version and 10.x the latest current one. Both versions give same error.

**Comment by pverhelle** [comment]
i'm having the same issue after upgrading an existing api to node 8.11.1
using 
   ` "loopback": "3.8.0",`
  ` "loopback-boot": "^2.25.0",`

for some reason, i get the `raiseUrlNotFoundError` when installing the node modules using npm but i don't get the error when using yarn.
however we want to eliminate the use of yarn

any help would be appreciated, if there are any questions, please let me know

**Comment by hacksparrow** [comment]
@J-Siu @pverhelle it should not happen, most likely a misconfiguraion or something incorrect somewhere. Please upload failing sample project on GitHub, so I can inspect what's going on.

**Comment by ssinhaprgx** [comment]
I am facing the same error when opening on browser:
{"error":{"statusCode":404,"name":"Error","message":"Cannot GET /explorer","status":404,"stack":"Error: Cannot GET /explorer\n    at raiseUrlNotFoundError (/usr/local/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)\n    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)\n    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15\n    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)\n    at router (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)\n    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)\n    at urlencodedParser (/usr/local/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)"}}

**This is the error on Rest Server dynamic log:**

Unhandled error for request GET /explorer: Error: Cannot GET /explorer
    at raiseUrlNotFoundError (/usr/local/lib/node_modules/composer-rest-server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/composer-rest-server/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/usr/local/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
