### ISSUE TITLE
.findOne does not work

### ISSUE THREAD

**Issue by samritabakshi** [strongloop/loopback#3892]
# Description/Steps to reproduce

# Link to reproduction sandbox

{
  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "Unknown \"BidSample\" id \"5b067566f6f7f8e2dc9f9233\".",
    "code": "MODEL_NOT_FOUND"
  }
}

# Expected result

# Additional information

I get this error when I do a .findById() on my model.Although I have inclueded 
"options": {
      "strictObjectIDCoercion": true
    }
in my datasource

**Comment by hacksparrow** [comment]
@samritabakshi it is very difficult to gather what could be happening with that limited information. If you create a small app which reproduces the error you are facing, we can help troubleshoot and resolve the issue.

**Comment by dhmlau** [comment]
@samritabakshi , are you still encountering this problem?  If so, please provide a sample app for problem reproduction.  Thanks.

**Comment by rafaneri** [comment]
@hacksparrow  and @dhmlau, I have the same error.
I'm using mongodb with default configuration on datasources.json.

It is my model (the database is empty):

```json
{
  "name": "TaggedMaterial",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "forceId": false,
  "properties": {
    "tagId": {
      "type": "string",
      "required": true,
      "description": "Identificador da etiqueta RFID"
    },
    "validity": {
      "type": "date",
      "required": true,
      "description": "Validade do material médico"
    }
  },
  "validations": [],
  "relations": {
    "material": {
      "type": "belongsTo",
      "model": "Material",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}
```

When I call in loopback explorer the **findOne** (http://macbook-pro-de-rafael.local:3200/api/TaggedMaterials/findOne) I get the same error:

```json
{
  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "\"TaggedMaterial\" id \"undefined\" desconhecido.",
    "status": 404,
    "code": "MODEL_NOT_FOUND",
    "stack": "Error: \"TaggedMaterial\" id \"undefined\" desconhecido.\n    at Function.convertNullToNotFoundError (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/loopback/lib/persisted-model.js:89:17)\n    at invokeRestAfter (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/lib/rest-adapter.js:472:25)\n    at /Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/async/dist/async.js:3853:24\n    at replenish (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/async/dist/async.js:946:17)\n    at iterateeCallback (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/async/dist/async.js:931:17)\n    at /Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/async/dist/async.js:906:16\n    at /Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/async/dist/async.js:3858:13\n    at interceptInvocationErrors (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/lib/remote-objects.js:713:22)\n    at /Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25\n    at /Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25\n    at /Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25\n    at execStack (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/lib/remote-objects.js:522:7)\n    at RemoteObjects.execHooks (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/lib/remote-objects.js:526:10)\n    at phaseAfterInvoke (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/lib/remote-objects.js:684:10)\n    at runHandler (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:135:5)\n    at iterate (/Volumes/MacintoshHDFiles/Documents/R&D/test-loopback/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)"
  }
}
```

**Comment by rafaneri** [comment]
I did a new test, if I insert a new register, then the findOne works, but if collection is empty, I get this error.
