### ISSUE TITLE
Error: Cannot find module 'ieee754' - while trying to run the lb command

### ISSUE THREAD

**Issue by deepakparamesh** [strongloop/loopback#3894]
# Description/Steps to reproduce
  I installed the Loopback using the  command "npm install -g loopback-cli" 
  the loopback-cli@4.2.0 was successfully installed. 

after i run the command "lb" the cli threw an error 

`module.js:538
    throw err;
    ^

Error: Cannot find module 'ieee754'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:7:11355)
    at t (C:\Users\dell\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:1:177)
    at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:7:15)
    at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:7:11111)
    at t (C:\Users\dell\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:1:177)
    at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:1:48717) `

# Expected result
expecting the command to generate questions.. 

Thanks in advance

# Additional information
Node version : 8.0 +

**Comment by diegoazh** [comment]
Same issue here!
Other question is, install module globally or how dev dependency.

**Comment by shinta5150** [comment]
Having same issue on loopback-cli@3.x

**Comment by shinta5150** [comment]
Temporary fix npm i -g ieee754 --save-dev and to get local working npm i ieee754 --save-dev

**Comment by adrian999999** [comment]
`npm i ieee754 --save-dev` will solve the issue temperately, I reckon someone removed this package?

**Comment by virkt25** [comment]
Cross posting from https://github.com/strongloop/loopback-next/issues/1367#issuecomment-392345837

> swagger-api/swagger-js#1326 is the culprit.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/swagger-api/swagger-js/pull/1328
