### ISSUE TITLE
Unable to catch default findById 404 invalid id error by afterRemoteError hook

### ISSUE THREAD

**Issue by MengdanCode** [strongloop/loopback#3901]
# Description/Steps to reproduce

I'm trying to use afterRemoteError hook to modify the default findById 404 invalid id error. However, it seems the error has never been thrown so the afterRemoteError is not able to catch it.

```
Transaction.afterRemoteError('findById', function(ctx, next) {
    console.log('remote hook triggerred');
    var error = new Error()
    error.status = 404
    error.message = 'Find By ID - hook See server console log for details.'
    next(error);
  });
```
# Link to reproduction sandbox

# Expected result
1. Console log to print out "remote hook triggerred". 
2. Error msg should be changed to "Find By ID - hook See server console log for details."

# Actual Result:
```
Browse your REST API at http://localhost:3001/explorer
Unhandled error for request GET /api/Transactions/44: Error: Unknown "Transaction" id "44".
    at Function.convertNullToNotFoundError (/Users/user/code/backend/stored-value/App/node_modules/loopback/lib/persisted-model.js:91:17)
    at invokeRestAfter (/Users/user/code/backend/stored-value/App/node_modules/strong-remoting/lib/rest-adapter.js:531:25)
    at /Users/user/code/backend/stored-value/App/node_modules/async/dist/async.js:3866:24
    at replenish (/Users/user/code/backend/stored-value/App/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/user/code/backend/stored-value/App/node_modules/async/dist/async.js:983:17)
    at /Users/user/code/backend/stored-value/App/node_modules/async/dist/async.js:958:16
    at /Users/user/code/backend/stored-value/App/node_modules/async/dist/async.js:3871:13
    at interceptInvocationErrors (/Users/user/code/backend/stored-value/App/node_modules/strong-remoting/lib/remote-objects.js:721:22)
    at /Users/user/code/backend/stored-value/App/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /Users/user/code/backend/stored-value/App/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /Users/user/code/backend/stored-value/App/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at execStack (/Users/user/code/backend/stored-value/App/node_modules/strong-remoting/lib/remote-objects.js:530:7)
    at RemoteObjects.execHooks (/Users/user/code/backend/stored-value/App/node_modules/strong-remoting/lib/remote-objects.js:534:10)
    at phaseAfterInvoke (/Users/user/code/backend/stored-value/App/node_modules/strong-remoting/lib/remote-objects.js:692:10)
    at runHandler (/Users/user/code/backend/stored-value/App/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/Users/user/code/backend/stored-value/App/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
```

<img width="861" alt="screen shot 2018-05-30 at 10 35 08" src="https://user-images.githubusercontent.com/8488558/40697597-37059c98-63f5-11e8-9c4a-82b46962fcce.png">

# Additional information

**Comment by hacksparrow** [comment]
@MengdanCode there are many factors we need to consider when troubleshooting an issue like this, please upload a minimal project which reproduces this error. We will be able to help you resolve it then.
