### ISSUE TITLE
Many-to-Many relationship with string id --- Error: Duplicate entry for Tag.name

### ISSUE THREAD

**Issue by mehhrad** [strongloop/loopback#3903]
i'm trying to make a simple weblog app with loopback
i have Post, Tag, Category models
Post model has many Tags through PostTag model.
Tag  has many Posts also
Post model has many Categories though PostCat model.
Category has many Posts also

Post.json:
` "name": "Post",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "title": {
      "type": "string",
      "required": true
    },
    "body": {
      "type": "string",
      "required": true
    },
    "desc": {
      "type": "string"
    },
    "date": {
      "type": "date"
    },
    "publisherId": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {
    "tags": {
      "type": "hasMany",
      "model": "Tag",
      "foreignKey": "postId",
      "options": {
        "nestRemoting": true
      },
      "through": "PostTag"
    },
    "writer": {
      "type": "belongsTo",
      "model": "Writer",
      "foreignKey": "publisherId",
      "options": {
        "nestRemoting": true
      }
    },
    "comments": {
      "type": "hasMany",
      "model": "Comment",
      "foreignKey": "postId",
      "options": {
        "nestRemoting": true
      }
    },
    "categories": {
      "type": "hasMany",
      "model": "Category",
      "foreignKey": "postId",
      "options": {
        "nestRemoting": true
      },
      "through": "PostCat"
    }
  },`

Tag.json:
`{
  "name": "Tag",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "id": true,
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "posts": {
      "type": "hasMany",
      "model": "Post",
      "foreignKey": "tagId",
      "options": {
        "nestRemoting": true
      },
      "through": "PostTag"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
`

Category.json
`{
  "name": "Category",
  "plural": "categories",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true,
      "id":true
    }
  },
  "validations": [],
  "relations": {
    "posts": {
      "type": "hasMany",
      "model": "Post",
      "foreignKey": "categoryId",
      "options": {
        "nestRemoting": true
      },
      "through": "PostCat"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
`
PostTag.json
`{
  "name": "PostTag",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "post": {
      "type": "belongsTo",
      "model": "Post",
      "foreignKey": "postId",
      "options": {
        "nestRemoting": true
      }
    },
    "tag": {
      "type": "belongsTo",
      "model": "Tag",
      "foreignKey": "tagId",
      "options": {
        "nestRemoting": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
`

PostCat:
`{
  "name": "PostCat",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "post": {
      "type": "belongsTo",
      "model": "Post",
      "foreignKey": "postId",
      "options": {
        "nestRemoting": true
      }
    },
    "category": {
      "type": "belongsTo",
      "model": "Category",
      "foreignKey": "categoryId",
      "options": {
        "nestRemoting": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
`

Reproducing the Error:
what is the problem?
when i want to create same tag for a different post i get this error message

1.create post1 and post2
2.add "mytag" to post1 by  POST http://localhost:3000/api/Posts/1/Tags?access_token=...
3.add "mytag" to post2 by POST http://localhost:3000/api/Posts/2/Tags?access_token=...

`Unhandled error for request POST /api/Posts/2/Tags?access_token=eW35RtZNgRgxBcJOcbNeFF0YPR62lYPwX0ulXg4Qi7tldoKFvnUXgqZmRQECTfwz: Error: Duplicate entry for Tag.name
    at Memory._createSync (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\connectors\memory.js:259:17)
    at Memory.create (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\connectors\memory.js:270:8)
    at invokeConnectorMethod (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\dao.js:169:21)
    at C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\dao.js:472:11
    at doNotify (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at doNotify (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at doNotify (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at doNotify (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (C:\Users\hans\js\loopback\gentleman-blog\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
`

if i add an id field to Tag model this problem won't happen but i can't get posts by tag later 
the reason i removed id from tag and post is to be able to query them for related models.(since loopback doesn't support for querying related models)
what's wrong with my implementation and what's the ideal way to do it ?

**Comment by dhmlau** [comment]
@jannyHou, could you PTAL?
