### ISSUE TITLE
Unable to Install on Windows

### ISSUE THREAD

**Issue by xlxAciDxlx** [strongloop/loopback#3935]
# Description/Steps to reproduce
When I try to install the CLI, I get a _ton_ of errors.

- Run `npm i -g loopback-cli`
- Get tons of errors..?

# Link to reproduction sandbox
There's nothing to provide, I literally can't get it to install...

# Expected result
Expected result: CLI installs
Actual result: Tons of errors

```
C:\Users\AciD\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Users\AciD\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\AciD\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
..\src\ursaNative.cc(157): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Use
rs\AciD\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Use
rs\AciD\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(389): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules\
loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(389): error C2227: left of '->n' must point to class/struct/union/generic type [C:\Users\AciD\AppD
ata\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(390): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules\
loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(390): error C2227: left of '->e' must point to class/struct/union/generic type [C:\Users\AciD\AppD
ata\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(407): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules\
loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(407): error C2227: left of '->d' must point to class/struct/union/generic type [C:\Users\AciD\AppD
ata\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(536): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules\
loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(536): error C2227: left of '->e' must point to class/struct/union/generic type [C:\Users\AciD\AppD
ata\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(536): error C2660: 'bignumToBuffer': function does not take 1 arguments [C:\Users\AciD\AppData\Roa
ming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(552): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules\
loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(552): error C2227: left of '->d' must point to class/struct/union/generic type [C:\Users\AciD\AppD
ata\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(552): error C2660: 'bignumToBuffer': function does not take 1 arguments [C:\Users\AciD\AppData\Roa
ming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(567): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules\
loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(567): error C2227: left of '->n' must point to class/struct/union/generic type [C:\Users\AciD\AppD
ata\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(567): error C2660: 'bignumToBuffer': function does not take 1 arguments [C:\Users\AciD\AppData\Roa
ming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1218): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1218): error C2227: left of '->n' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1219): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1219): error C2227: left of '->e' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1220): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1220): error C2227: left of '->p' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1221): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1221): error C2227: left of '->q' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1222): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1222): error C2227: left of '->dmp1' must point to class/struct/union/generic type [C:\Users\AciD\
AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1223): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1223): error C2227: left of '->dmq1' must point to class/struct/union/generic type [C:\Users\AciD\
AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1224): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1224): error C2227: left of '->iqmp' must point to class/struct/union/generic type [C:\Users\AciD\
AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1225): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1225): error C2227: left of '->d' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1270): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1270): error C2227: left of '->n' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1271): error C2027: use of undefined type 'rsa_st' [C:\Users\AciD\AppData\Roaming\npm\node_modules
\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
  C:\Users\AciD\.node-gyp\10.2.1\include\node\openssl/evp.h(914): note: see declaration of 'rsa_st'
..\src\ursaNative.cc(1271): error C2227: left of '->e' must point to class/struct/union/generic type [C:\Users\AciD\App
Data\Roaming\npm\node_modules\loopback-cli\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\AciD\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AciD\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AciD\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\ursa
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\loopback-cli\node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

# Additional information
1st command: `Invalid or unexpected token`
2nd command: Empty response

**Comment by xlxAciDxlx** [comment]
Sorry if my description/steps don't help, I'm quite flabbergasted. Normally I can at least provide _some_ information by looking at the stacktrace, but this seems different from any response I've ever seen from Node.

**Comment by xlxAciDxlx** [comment]
Uhh okay, I guess this can be disregarded... Despite the plethora of errors, it does _appear_ that Loopback was successfully installed. I'll leave this open in case there's any advice that can be given to fix the errors during install.

**Comment by xlxAciDxlx** [comment]
Now I'm getting this when trying to run:
```
Error: Cannot find module 'babel-runtime/helpers/extends'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Projects\Loopback-Example\node_modules\swagger-client\dist\index.js:1:777)
```

On a completely fresh install.

**Comment by dhmlau** [comment]
@xlxAciDxlx, I recalled that you have to install something else if you're running on Windows.  See if this helps: https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies/39648550#39648550.

**Comment by xlxAciDxlx** [comment]
Unfortunately, the error persists. I almost want to say it's an incompatibility with either MS Build Tools, or a config setting _somewhere_ - the problem is figuring out where. The errors are terribly unhelpful.

**Comment by thurnbauermatthi** [comment]
I don't know why this makes such a big difference, but after a long research I tried 'npm i -g @loopback/cli' to install loopback cli and suddenly there were no more errors. So maybe this command solves your problem.

**Comment by AliMirlou** [comment]
@thurnbauermatthi That command installs the unreleased version 4 of loopback-cli which is much different from version 3 and is not for production use.

**Comment by dhmlau** [comment]
For LB3 CLI (i.e. `loopback-cli`), we've removed the requirement of `ursa` via this PR https://github.com/strongloop/strong-soap/pull/224.  Closing this as fixed.
