### ISSUE TITLE
The \"path\" argument must be of type string

### ISSUE THREAD

**Issue by cuzox** [strongloop/loopback#3942]
In account.js
```
Account.observe('after save', function (ctx, next) {
    if (ctx.isNewInstance) {
      var _account = ctx.instance
      var _container = Account.app.models.Container
      _container.createContainer({ name: _account.id }, next)
    } else {
        next()
    }
  });
```

I get
```
{
  "error": {
    "statusCode": 500,
    "name": "TypeError [ERR_INVALID_ARG_TYPE]",
    "message": "The \"path\" argument must be of type string",
    "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string\n    at assertPath (path.js:39:11)\n    at Object.join (path.js:1158:7)\n..."
  }
}
```

After attempting to create a container for the user after the user has been created

linux x64 9.11.1
├── loopback@3.20.0
├── loopback-boot@2.27.0
├── loopback-component-explorer@6.0.1
├── loopback-component-storage@3.4.0

**Comment by cuzox** [comment]
_account.id return a number, and I guess it doesn't like that
_accoutn.id.toString() worked
