### ISSUE TITLE
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/

### ISSUE THREAD

**Issue by diegoazh** [strongloop/loopback#3956]
I searched in Google but I didn't find any question or answer related to this console message.

# Description/Steps to reproduce
- Init a new project with loopback-cli
    - version 3.x
    - api-server
- Then `cd <your-project>` and run `node .`
- the console shows
```bash
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
```
- Access to [http://localhost:3000/explorer/](http://localhost:3000/explorer/)
- The console shows the following message:
```bash
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/dazh/Documentos/messageserver/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:174:3)
    at router (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/dazh/Documentos/messageserver/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:174:3)
    at router (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/dazh/Documentos/messageserver/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:174:3)
    at router (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/dazh/Documentos/messageserver/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:174:3)
    at router (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/dazh/Documentos/messageserver/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:174:3)
    at router (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15)
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/dazh/Documentos/messageserver/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15
    at next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:174:3)
    at router (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:317:13)
    at /home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/dazh/Documentos/messageserver/node_modules/express/lib/router/index.js:635:15)
```

I think this is a little bug, but I'm not really sure.
The steps to reproduce are discribed above.

# Link to reproduction sandbox
I think it is not necesary because this message is generated in a new and clean project.

# Expected result
```bash
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
```

# Additional information
**OS**: Ubuntu 18.04 LTS,
**NODE**: v8.11.3
**NPM**: 6.2.0
**Loopback-cli**: 4.2.0 (generator-loopback@5.8.1 loopback-workspace@4.3.0)
**Interesting fact**: In Mac OS system this behavior does not occur
**Note**: This message does not obstruct the normal loopback explorer functionality

**Comment by keith666666** [comment]
check the file:
server/component-config.json
```
{
  "loopback-explorer": {
    "mountPath": "/explorer"
  }
}
```
> [API Explorer](https://loopback.io/doc/en/lb3/LoopBack-components.html#api-explorer)

**Comment by dhmlau** [comment]
@diegoazh, sorry about the late reply.  Does the above comment from @keith666666 help?  If not, I can take a closer look.

**Comment by dhmlau** [comment]
Closing due to inactivity.
