### ISSUE TITLE
"Error: Cannot set headers after they are sent to the client" for remote method that calls container download

### ISSUE THREAD

**Issue by AliMirlou** [strongloop/loopback#3983]
I added a remote method to my Account model as prototype to first do authentication then if the account had permission, send a file to the client using "download" remote method from a container model.

# Steps to reproduce

1- Client creates an Account (e.g: "{"username": "string","email": "string@string.string","firstName": "string","lastName": "string","password": "string"}")
2- Logs in (e.g: "{"username":"string","password":"string"}")
3- Sends a GET request to "/api/Accounts/<User ID>/file?access_token=<Access Token>"

# Link to reproduction sandbox

https://github.com/AliMirlou/loopback-sandbox

# Expected result

File being sent to the client and continue

# Actual result

The file is sent but application crashes right after it with:

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (node_modules\express\lib\response.js:267:15)
    at Object.sendBodyJson [as sendBody] (node_modules\strong-remoting\lib\http-context.js:437:7)
    at HttpContext.done (node_modules\strong-remoting\lib\http-context.js:578:24)
    at node_modules\strong-remoting\lib\rest-adapter.js:539:11
    at node_modules\async\dist\async.js:3874:9
    at node_modules\async\dist\async.js:473:16
    at replenish (node_modules\async\dist\async.js:993:25)
    at iterateeCallback (node_modules\async\dist\async.js:983:17)
    at node_modules\async\dist\async.js:958:16
    at node_modules\async\dist\async.js:3871:13
    at interceptInvocationErrors (node_modules\strong-remoting\lib\remote-objects.js:724:22)
    at node_modules\loopback-phase\node_modules\async\dist\async.js:473:16
    at replenish (node_modules\loopback-phase\node_modules\async\dist\async.js:1006:25)

# Additional information

win32 x64 10.9.0

loopback@3.22.1
loopback-boot@2.27.1
loopback-component-explorer@6.2.0
loopback-component-storage@3.5.0

**Comment by skanygin** [comment]
Use https://github.com/AliMirlou/loopback-sandbox/blob/master/common/models/account.js#L11 as middleware. See: http://apidocs.loopback.io/loopback-component-storage/#storageservice-prototype-download

<img width="693" alt="download" src="https://user-images.githubusercontent.com/14076150/44919966-6b57ce80-ad47-11e8-92f6-cdedf7dd9c9c.png">

**Comment by AliMirlou** [comment]
@skanygin Can you help me defining it? The documentation of storage component has not said anything about in what level of middleware.json it should be registered or with what parameters. And I have trouble understanding how it's going to do what I want from it if as middleware because what I actually want is a little more complex than what I have written here.

**Comment by AliMirlou** [comment]
@jannyHou @virkt25 @dhmlau @bajtos Can anyone help? I couldn't get it to work...

**Comment by dhmlau** [comment]
@hacksparrow , could you please help? Thanks.

**Comment by hacksparrow** [comment]
@AliMirlou please remove `returns: {arg: 'result', type: 'object'}`, the underlying framework is smart enough to handle the downloading itself. Specifying `returns` confuses it.

**Comment by AliMirlou** [comment]
@hacksparrow Well that was a practical tip. Thank you very much.
Now another problem... I seem to be having a problem with upload remote method too. I am using it the same as the download one. It works well on small files but when it comes to files larger than a megabyte, the request is dropped before the file is uploaded completely. Setting or Unsetting "returns" doesn't make any difference in this matter (it only makes the response empty). Any idea?
