### ISSUE TITLE
Third party login via mobile app

### ISSUE THREAD

**Issue by jkunwar** [strongloop/loopback#4004]
I have a mobile app that uses google login.
How can i log in user in mobile app once i got the user information from google as in loopback web application. 

task i did are:
1. check userIdentity model if there is existing loopback user
2. if no user found, create a new user and create corresponding record in userIdentity model

after that i tried to login with email and password i got following error

TypeError: Cannot read property 'definition' of undefined
    at Object.ModelBaseClass.toObject (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/model.js:435:38)
    at Object.ModelBaseClass.toJSON (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/model.js:594:15)
    at JSON.stringify (<anonymous>)
    at sendJson (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/strong-error-handler/lib/send-json.js:9:22)
    at strongErrorHandler (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/strong-error-handler/lib/handler.js:55:5)
    at Layer.handle_error (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:315:13)
    at /Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:315:13)
    at /Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/jagdishkunwar/Documents/projects/epechaweb/node_modules/express/lib/router/layer.js:67:12)

**Comment by jkunwar** [comment]
https://stackoverflow.com/questions/30788998/loopback-passport-mobile-login?answertab=active#tab-top
