### ISSUE TITLE
Self HasManyThrough relation : Model is not defined

### ISSUE THREAD

**Issue by marem-bzh** [strongloop/loopback#4012]
Good evening !

I've been trying to set a self HasManyThrough relation, but the querying fails for some reason. I tried to find an answer in resolved issues, but I can't find what I'm doing wrong.

# Description/Steps to reproduce
An article can be composed of several other articles : 
- An article has many components 
- An article has many compounds

I managed to create the relation between models, and to create the relation between instances, but I get the following error on the endpoints GET /articles/[id]/components and GET /articles/[id]/compounds : 

<details><summary>Show the error</summary>

```
500 Relation "article" is not defined for composition model

Error: Relation "article" is not defined for composition model
    at processIncludeItem (D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\include.js:293:10)
    at D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\include.js:184:5
    at D:\Freelancing\erp\api\dev\node_modules\async\dist\async.js:3110:16
    at eachOfArrayLike (D:\Freelancing\erp\api\dev\node_modules\async\dist\async.js:1069:9)
    at eachOf (D:\Freelancing\erp\api\dev\node_modules\async\dist\async.js:1117:5)
    at Object.eachLimit (D:\Freelancing\erp\api\dev\node_modules\async\dist\async.js:3172:5)
    at Function.Inclusion.include (D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\include.js:183:9)
    at D:\Freelancing\erp\api\dev\node_modules\loopback-connector\lib\sql.js:1449:44
    at D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\observer.js:250:22
    at doNotify (D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at PostgreSQL.ObserverMixin._notifyBaseObservers (D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\observer.js:178:5)
    at PostgreSQL.ObserverMixin.notifyObserversOf (D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
    at cbForWork (D:\Freelancing\erp\api\dev\node_modules\loopback-datasource-juggler\lib\observer.js:240:14)
    at D:\Freelancing\erp\api\dev\node_modules\loopback-connector\lib\sql.js:643:9
    at Query. (D:\Freelancing\erp\api\dev\node_modules\loopback-connector-postgresql\lib\postgresql.js:152:7)
    at Query.handleReadyForQuery (D:\Freelancing\erp\api\dev\node_modules\pg\lib\query.js:126:10)
```

</details>

## Definitions

**article.json**
~~~~
  "relations": {
    "compound": {
      "type": "belongsTo",
      "model": "article",
      "foreignKey": "compoundId"
    },
    "component": {
      "type": "belongsTo",
      "model": "article",
      "foreignKey": "componentId"
    }
  }
~~~~

**composition.json**
~~~~
  "relations": {
    "components": {
      "type": "hasMany",
      "model": "article",
      "foreignKey": "compoundId",
      "through": "composition",
      "keythrough": "componentId"
    },
    "compounds": {
      "type": "hasMany",
      "model": "article",
      "foreignKey": "componentId",
      "through": "composition",
      "keythrough": "compoundId"
    }
  }
~~~~

# Additional information
win32 x64 8.9.4
+-- loopback@3.22.3
+-- loopback-boot@2.27.1
+-- loopback-component-explorer@6.3.0
+-- loopback-connector-postgresql@3.4.0

Thanks for your help !

**Comment by israelglar** [comment]
Hi, correct me if I'm wrong.
What you want is:

Article has many articles(components) through Composition:
Article -> Composition -> Article

Article has many articles(compound) through Composition
Article -> Composition -> Article

If so, you need something like:

**article.json**

```
"relations": {
  "compound": {
    "type": "hasMany",
    "model": "article",
    "through": "composition",
    "foreignKey": "compoundId"
  },
  "component": {
    "type": "hasMany",
    "model": "article",
    "through": "composition",
    "foreignKey": "componentId"
    }
  }
 ```

**composition.json**

```
"relations": {
    "compound": {
      "type": "belongsTo",
      "model": "article",
      "foreignKey": "compoundId"
    },
    "component": {
      "type": "belongsTo",
      "model": "article",
      "foreignKey": "componentId"
    }
  }
```

I can't test that right now, but it should be something like that. Or maybe switch the foreign key's names

**Comment by tootdev** [comment]
I have the same issue. My scenario is User can be a teacher or student of another user, so:
user->tution->user(teacher)
user->tution->user(student)

**User.json**

```
"relations": {
    "students": {
      "type": "hasMany",
      "model": "user",
      "foreignKey": "studentId",
      "through": "Tution"
    },
    "teachers": {
      "type": "hasMany",
      "model": "user",
      "foreignKey": "teacherId",
      "through": "Tution"
    }
}
```

**Tution.json**

```
"relations": {
    "teacher": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "teacherId"
    },
    "student": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "studentId"
    },
    "course": {
      "type": "belongsTo",
      "model": "Course",
      "foreignKey": ""
    }
  }
```

When checking endpoint say GET users/:id/students , if a record doesn't exist, it simply returns empty array, but if a record exists on Tution, it throws the error `Relation "user" is not defined for Tution model`
