### ISSUE TITLE
Operation hook parameter Ctx.options is empty

### ISSUE THREAD

**Issue by Enosinger** [strongloop/loopback#4024]
# Description/Steps to reproduce
Hi All,

in our application we have defined an operation hook "before save".
With it we intend to do some validations about the requesting user.

In order to access the requesting user´s id, we are trying to get his accessToken from the `options `object of the `context` parameter. This is done in accordance to the official loopback docs (
https://loopback.io/doc/en/lb3/Using-current-context.html#access-the-context-from-operation-hooks)

The below code has been reduced to the minimum things for debugging:
```
Progress.observe('before save', function verifyAccessToken(ctx, next) {
        console.log('Executing before save');
        if (!ctx) {
            next(new Error('No ctx was passed to verifyMyUserExists'));
        }
        else if (!ctx.options) {
            console.log('Ctx is:');
            next(new Error('No options in ctx was passed to verifyMyUserExists'));
        }
        else if (!ctx.options.accessToken) {
            console.log('Options is:');
            console.log(ctx.options);
            next(new Error('No accessToken options in ctx was passed to verifyMyUserExists'));
        }
        else {
            next();
        }
    });
```
As of this week - without changing a thing in the code - this validation does not work any longer.
Based on this I got to know that the ctx.options is an empty object of `{}` (See full error log below).
Because of this we are not able to access the accessToken of course,

We did some troubleshooting and were not able to find the root cause, why the ctx.options is empty.

1.  We are using the hook for standard operations on simple persisted models (NO custom methods. Just basic things.)
1. We ensured options are indeed injected (see code above and output below)
1. Take note, that we have embedded another model into the persisted model where the error occurs.
But to our knowledge this should not be an issue, as it worked before.

# Expected result

We would expect the operation hook´s parameter ctx to be populated with a full options object containing at least the accessToken of the requesting user.

Any thoughts on this? I am looking forward to your response and any ideas.

Best,
enosinger

# Additional information

The full error log for the operation hook is:
```
Executing before save
Options is:
{}
Nicht verarbeiteter Fehler für Anforderung POST /api/progresses/?access_token=<XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX>: Error: No accessToken options in ctx was passed to verifyMyUserExists
    at verifyAccessToken (C:\Users\erosinger3\workspace_FitChallenger\Backend\common\models\progress.js:34:18)
    at notifySingleObserver (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:160:22)
    at C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\async\dist\async.js:3096:16
    at replenish (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\async\dist\async.js:998:17)
    at C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\async\dist\async.js:1002:9
    at eachLimit$1 (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\async\dist\async.js:3182:24)
    at Object.<anonymous> (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\async\dist\async.js:1032:16)
    at doNotify (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:157:11)
    at doNotify (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at doNotify (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at doNotify (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (C:\Users\erosinger3\workspace_FitChallenger\Backend\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
```

Please excuse the German Error Messages. I do not know why the have been localized after I updated VS Code today ...

**Comment by bajtos** [comment]
Thank you @Enosinger for reporting the issue. I am afraid the information you have provided is not enough to allow us to reproduce (and debug) the issue locally. Could you please create a small application we can run to reproduce the issue? See https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

I am not aware of any (recent) changes that could explain the change in behavior you are observing. Do you happen to know what was the last version of `loopback` and `loopback-datasource-juggler` that was working correctly for you?

**Comment by lvao813** [comment]
I also encountered the same problem.
