### ISSUE TITLE
Issue with embedsOne relation with postgres connector and existing schemas

### ISSUE THREAD

**Issue by tsnork** [strongloop/loopback#4026]
**relation defined in model followUps as following:**

```
"accountLeadStatus": {
        "model": "AccountStatus",
        "type": "embedsOne",
        "property": "leadstatusFk"
      },
```

**property defined as following:**

```
"leadstatusFk": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "leadstatus_fk",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "NO"
      }
    },
```

**Output in API explorer MODEL:**

Abbreviated for redability

```
{
...
  "leadstatusFk": {
    "leadstatusId": 0,
    ...
  },
 ...
}
```

**Output of actual query/debug of connector:**

```
{
  "error": {
    "statusCode": 500,
    "name": "error",
    "message": "Spalte »leadstatusfk« existiert nicht",
    "length": 211,
    "severity": "FEHLER",
    "code": "42703",
    "hint": "Vielleicht wurde beabsichtigt, auf die Spalte »wiedervorlagen.leadstatus_fk« zu verweisen.",
    "position": "113",
    "file": "parse_relation.c",
    "line": "3194",
    "routine": "errorMissingColumn",
    "stack": "error: Spalte »leadstatusfk« existiert nicht\n    at Connection.parseE (C:\\SCFiles\\SC\\Code\\lb3-api-scope\\node_modules\\pg\\lib\\connection.js:554:11)\n    at Connection.parseMessage (C:\\SCFiles\\SC\\Code\\lb3-api-scope\\node_modules\\pg\\lib\\connection.js:379:19)\n    at Socket.<anonymous> (C:\\SCFiles\\SC\\Code\\lb3-api-scope\\node_modules\\pg\\lib\\connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)"
  }
}
```
debug.log attached
[debug.log](https://github.com/strongloop/loopback/files/2472203/debug.log)

**Additional information**

  node -e 'console.log(process.platform, process.arch, process.versions.node)'

`win32 x64 8.11.4`

  npm ls --prod --depth 0 | grep loopback

```
+-- loopback@3.23.0
+-- loopback-boot@2.27.1
+-- loopback-component-explorer@6.3.0
ERR!+-- loopback-connector-postgresql@3.4.0
npm ERR! missing: debug@3.2.5, required by loopback-swagger@5.7.03.0
npm ERR! missing: debug@3.2.5, required by loopback-connector-postgresql@3.4.0
npm ERR! missing: debug@3.2.5, required by loopback-connector@4.5.1
npm ERR! missing: debug@3.2.5, required by strong-error-handler@3.2.0
```

Sorry for not providing an example sandbox - if really needed I can provide one, but creating all models & postgres databases seemed out of scope for this issue. If you need it, I'll happily provide it.

Thanks for your help!

**Comment by tsnork** [comment]
Sorry to bug again, but I just restarted my demo project 

Same issue on

node -e 'console.log(process.platform, process.arch, process.versions.node)';
win32 x64 10.13.0

npm ls --prod --depth 0 | grep loopback
+-- loopback@3.24.0
+-- loopback-boot@2.27.1
+-- loopback-component-explorer@6.3.1
+-- loopback-connector-postgresql@3.5.0

Am I wrong assuming that changing the relation like this:
type from "belongsTo" to "embedsOne" and "foreignKey" to "property" should work for an auto-generated relation?

`"created_by_rel": {
        "model": "Employee",
        "type": "belongsTo",
        "foreignKey": "created_by"
},`

works, but

`"created_by_rel": {
        "model": "Employee",
        "type": "embedsOne",
        "property": "created_by"
 },`

does not, producing:

`error: Spalte »created_by« existiert nicht`, Column does not exist
