### ISSUE TITLE
Encountering **401 Authorization Required** while querying apis after implementing static roles. Loopback 3.x

### ISSUE THREAD

**Issue by debasmitadasgupta** [strongloop/loopback#4063]
I have a **app_user** model extended from User model and a **brand** model with following acls defined.

**app_user.json**
```
{
  "name": "app_user",
  "plural": "app_users",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "user_level": {
      "type": "string",
      "required": true,
      "default": "account_manager"
    },
    "title": {
      "type": "string",
      "required": true
    },
    "date_of_birth": {
      "type": "date",
      "required": true
    },
    "first_name": {
      "type": "string",
      "required": true
    },
    "last_name": {
      "type": "string",
      "required": true
    },
    "mobile_numaber": {
      "type": "string",
      "required": true
    },
    "address_line_1": {
      "type": "string"
    },
    "address_line_2": {
      "type": "string"
    },
    "province": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "postal_code": {
      "type": "string"
    },
    "emergency_contact_name": {
      "type": "string",
      "required": true
    },
    "emergency_contact_number": {
      "type": "string",
      "required": true
    },
    "emergency_contact_relationship": {
      "type": "string",
      "required": true
    },
    "created_ts": {
      "type": "date",
      "required": true
    },
    "updated_ts": {
      "type": "date",
      "required": true
    },
    "created_by": {
      "type": "string",
      "required": true
    },
    "updated_by": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "sb_access_token",
      "foreignKey": "user_id",
      "options": {
        "disableInclude": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "DENY"
    }
  ],
  "methods": {}
}

```

**brand.json**
```
{
  "name": "brand",
  "plural": "brands",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "brand_name": {
      "type": "string",
      "required": true
    },
    "agency_commission": {
      "type": "number"
    },
    "rebate": {
      "type": "number"
    },
    "insert_ts": {
      "type": "date",
      "required": true
    },
    "update_ts": {
      "type": "date",
      "required": true
    },
    "insert_user": {
      "type": "string",
      "required": true
    },
    "update_user": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "client": {
      "type": "belongsTo",
      "model": "client",
      "foreignKey": "client_id",
      "options": {
        "nestRemoting": true
      }
    }
  },
  "acls": [
    {   
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "super_admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "create"
    },
    {
     "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "replaceById"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "replaceOrCreate"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "updateAll"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "upsertWithWhere"
    },
    {
     "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "updateAttributes"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "account_manager",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "findById"
    }
    
  ],
  "methods": {}
}

```
Also added manual acls to map acls to models in database
 
manual-acls.js
```
var path = require('path');
var app = require(path.resolve(__dirname, '../server'));
var ACL = app.models.sb_acl;
ACL.create(
    [
        {
            "model": "app_user",
            "accessType": "*",
            "principalType": "ROLE",
            "principalId": "$everyone",
            "permission": "ALLOW"
        },
          {
            "model": "brand",
            "accessType": "*",
            "principalType": "ROLE",
            "principalId": "$everyone",
            "permission": "DENY"
          },
          {
            "model": "brand",
            "accessType": "*",
            "principalType": "ROLE",
            "principalId": "super_admin",
            "permission": "ALLOW"
          },
          {
            "model": "brand",
            "accessType": "READ",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "create"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "replaceById"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "replaceOrCreate"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "updateAll"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "upsertWithWhere"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "updateAttributes"
          },
          {
            "model": "brand",
            "accessType": "READ",
            "principalType": "ROLE",
            "principalId": "account_manager",
            "permission": "ALLOW"
          },
          {
            "model": "brand",
            "accessType": "EXECUTE",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW",
            "property": "findById"
          }
    ],
    function (err, acls,cb) {
        if (err) return cb(err);
        console.log(acls);

        // cb(null, true);
    });
```

Have a script to create a user and a static role and role mapping. 

script.js
```

module.exports = function(app) {
    var User = app.models.app_user;
    var Role = app.models.sb_role;
    var RoleMapping = app.models.sb_role_mapping;


    User.create([
        {
            "user_level": "admin",
            "title": "string",
            "date_of_birth": "2018-11-09T06:06:11.315Z",
            "first_name": "string",
            "last_name": "string",
            "mobile_numaber": "string",
            "address_line_1": "string",
            "address_line_2": "string",
            "province": "string",
            "city": "string",
            "country": "string",
            "postal_code": "string",
            "emergency_contact_name": "string",
            "emergency_contact_number": "string",
            "emergency_contact_relationship": "string",
            "created_ts": "2018-11-09T06:06:11.315Z",
            "updated_ts": "2018-11-09T06:06:11.315Z",
            "created_by": "string",
            "updated_by": "string",
            "realm": "string",
            "username": "John",
            "email": "john@doe.com",
            "emailVerified": true,
            "password": 'opensesame',
          }
      ], function(err, users) {
        if (err) throw err;
    
        console.log('Created users:', users)

    
        //create the admin role
        Role.create({
          name: 'admin'
        }, function(err, role) {
          if (err) throw err;
    
          console.log('Created role:', role);
    
          //make bob an admin
          role.principals.create({
            principalType: RoleMapping.USER,
            principalId: users[0].id
          }, function(err, principal) {
            if (err) throw err;
    
            console.log('Created principal:', principal);
          });
        });
      });
    };
```

Entries getting saved in the database properly. But giving Authorization required error on querying for apis.

Error on console looks like

```
SELECT `id`,`ttl`,`scopes`,`created`,`user_id` FROM `sb_access_token` WHERE `id`=? ORDER BY `id` LIMIT 1 [ 'mNJCddHALms2tbuTocAIRNN9UK2a90oeWLrv70Gf5dJOeprAaAZqMU1hDXDAMSOO' ]
[ RowDataPacket {
    id: 'mNJCddHALms2tbuTocAIRNN9UK2a90oeWLrv70Gf5dJOeprAaAZqMU1hDXDAMSOO',
    ttl: 1209600,
    scopes: null,
    created: 2018-11-09T06:28:52.000Z,
    user_id: 15 } ]
SELECT `model`,`property`,`accessType`,`permission`,`principalType`,`principalId`,`id` FROM `sb_acl` WHERE `model`=? AND `property` IN (?,?) AND `accessType` IN (?,?) ORDER BY `id` [ 'brand', 'findById', '*', 'READ', '*' ]
[ RowDataPacket {
    model: 'brand',
    property: '*',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'admin',
    id: 384 } ]
Unhandled error for request GET /api/brands/6?access_token=mNJCddHALms2tbuTocAIRNN9UK2a90oeWLrv70Gf5dJOeprAaAZqMU1hDXDAMSOO: Error: Authorization Required
    at D:\Simply Black\simplyblack\api\node_modules\loopback\lib\application.js:433:21
    at D:\Simply Black\simplyblack\api\node_modules\loopback\lib\model.js:359:7
    at D:\Simply Black\simplyblack\api\node_modules\loopback\common\models\acl.js:529:16
    at D:\Simply Black\simplyblack\api\node_modules\async\dist\async.js:3888:9
    at D:\Simply Black\simplyblack\api\node_modules\async\dist\async.js:473:16
    at iteratorCallback (D:\Simply Black\simplyblack\api\node_modules\async\dist\async.js:1064:13)
    at D:\Simply Black\simplyblack\api\node_modules\async\dist\async.js:969:16
    at D:\Simply Black\simplyblack\api\node_modules\async\dist\async.js:3885:13
    at D:\Simply Black\simplyblack\api\node_modules\loopback\common\models\acl.js:511:17
    at D:\Simply Black\simplyblack\api\node_modules\loopback\common\models\role.js:500:23
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

```

**Comment by soroushm** [comment]
@debasmitadasgupta are you using mangodb ?
