### ISSUE TITLE
Cannot find rest-explorer/templates

### ISSUE THREAD

**Issue by OysteinAmundsen** [strongloop/loopback#4072]
# Description/Steps to reproduce

Installing v1.2.0 of @loopback/cli in a completely new folder:

```
lb4 app
 * Default settings

cd server
yarn start
```
Output is:
```
yarn run v1.12.3
warning package.json: License should be a valid SPDX license expression
$ npm run build

> server@1.0.0 build .\server
> lb-tsc es2017 --outDir dist

$ node .
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '.\server\node_modules\@loopback\rest-explorer\templates\index.html.ejs'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.<anonymous> (.\server\node_modules\@loopback\rest-explorer\dist\src\rest-explorer.controller.js:26:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.\server\node_modules\@loopback\rest-explorer\dist\src\rest-explorer.component.js:23:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And as expected, `ls node_modules\@loopback\rest-explorer` shows no `templates` directory at all.

# Expected result

Expected a clean install and a freshly created app to run.

# Additional information

```
node --version && npm --version && yarn --version
v10.13.0
6.4.1
1.12.3

node -e 'console.log(process.platform, process.arch, process.versions.node)'
[eval]:1
'console.log(process.platform,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)
    at startup (internal/bootstrap/node.js:267:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

npm ls --prod --depth 0 | grep loopback
+-- @loopback/boot@1.0.5
+-- @loopback/context@1.1.0
+-- @loopback/core@1.1.0
+-- @loopback/openapi-v3@1.1.2
+-- @loopback/repository@1.0.5
+-- @loopback/rest@1.3.1
+-- @loopback/rest-explorer@1.1.0
`-- @loopback/service-proxy@1.0.2
```

**Comment by raymondfeng** [comment]
@OysteinAmundsen The package seems to be missing `templates` folder during npm publish. Will fix it soon.

**Comment by raymondfeng** [comment]
Please try `@loopback/cli@1.2.1`.

**Comment by OysteinAmundsen** [comment]
Yup. `"@loopback/rest-explorer": "^1.1.1"` did the trick. Thank you.
