### ISSUE TITLE
'lb model' throw TypeError at property name stage

### ISSUE THREAD

**Issue by thiras** [strongloop/loopback#4073]
# Description/Steps to reproduce

In clean ubuntu 18.04
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
reboot
nvm install --lts
npm install -g loopback-cli
lb
lb model
```
It break just after first property name defined. Error log;

```
Enter an empty property name when done.
? Property name: firstname
(node:9274) UnhandledPromiseRejectionWarning: TypeError: this.invoke is not a function
    at ModelGenerator.<anonymous> (/home/thiras/.nvm/versions/node/v10.13.0/lib/node_modules/loopback-cli/node_modules/generator-loopback/model/index.js:362:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# Expected result

Continue to the model creation

# Additional information

```
linux x64 10.13.0
xxx@1.0.0 /home/thiras/dev/node/loopback/xxx
├── loopback@3.24.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.3.1
```

**Comment by dennusb** [comment]
Same here, testing it on latest OSX : 

```
(node:21111) UnhandledPromiseRejectionWarning: TypeError: this.invoke is not a function
    at ModelGenerator.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/generator-loopback/model/index.js:362:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:21111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21111) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by AldieNightStar** [comment]
```
? Property name: name
(node:11240) UnhandledPromiseRejectionWarning: TypeError: this.invoke is not a function
    at ModelGenerator.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/generator-loopback/model/index.js:362:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This f* problem doesn't allow me to work on my project :(

**Comment by Joriks** [comment]
I had the same issue, but fixed uninstalling loopback-cli from node, then clean cache, updating nodejs to latest and installing again loopback.
i'm now usingnode v10.13.0
