### ISSUE TITLE
Error after fresh npm install

### ISSUE THREAD

**Issue by kranthitechie** [strongloop/loopback#4081]
I am getting this error since today I remove the node_modules and ran "npm install" again.
The error goes away once I copy node_modules folder from another loopback application.

Unhandled error for request POST /api/Affiliates: TypeError: Model._sanitizeData is not a function
    at Affiliate.<anonymous> (/mnt/e/ubuntu/Repos/affiliate-service/node_modules/loopback-datasource-juggler/lib/dao.js:379:25)
    at Affiliate.trigger (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
    at Affiliate.<anonymous> (/mnt/e/ubuntu/Repos/affiliate-service/node_modules/loopback-datasource-juggler/lib/dao.js:377:11)
    at Affiliate.trigger (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
    at create (/mnt/e/ubuntu/Repos/affiliate-service/node_modules/loopback-datasource-juggler/lib/dao.js:376:9)
    at /mnt/e/ubuntu/Repos/affiliate-service/node_modules/loopback-datasource-juggler/lib/dao.js:368:9
    at Affiliate.<anonymous> (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/validations.js:578:11)
    at Affiliate.next (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)
    at Affiliate.<anonymous> (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/validations.js:575:23)
    at Affiliate.trigger (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
    at Affiliate.Validatable.isValid (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/validations.js:541:8)
    at /mnt/e/ubuntu/Repos/affiliate-service/node_modules/loopback-datasource-juggler/lib/dao.js:366:9
    at doNotify (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/mnt/e/ubuntu/Repos/layback-mapsheet/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)

**Comment by soroushm** [comment]
@kranthitechie  try this
remove node_modules directory
remove package-lock.json file
$ npm cache clean --force
$ npm i
