### ISSUE TITLE
The server crashes when PUT a extended user model with a new or deleted id 

### ISSUE THREAD

**Issue by horstmannmat** [strongloop/loopback#4105]
# Description/Steps to reproduce
When I try to PUT extended model from User with new a id, or one that was previously deleted, the server crashes;

# Expected result

The server SHOULD NOT crash.

# Additional information
```
/app/node_modules/loopback/common/models/user.js:1361
        emailChanged = ctx.instance.email !== ctx.hookState.originalUserData[0].email;
                                                                                ^

TypeError: Cannot read property 'email' of undefined
    at /app/node_modules/loopback/common/models/user.js:1361:81
    at /app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:2117:9
    at /app/node_modules/async/dist/async.js:1140:9
    at /app/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/app/node_modules/async/dist/async.js:1057:9)
    at eachOf (/app/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/app/node_modules/async/dist/async.js:1133:5)
    at Object.map (/app/node_modules/async/dist/async.js:1122:16)
    at allCb (/app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:2031:13)
    at /app/node_modules/loopback-connector/lib/sql.js:1452:7
    at /app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:250:22
    at doNotify (/app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at PostgreSQL.ObserverMixin._notifyBaseObservers (/app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at PostgreSQL.ObserverMixin.notifyObserversOf (/app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at cbForWork (/app/node_modules/loopback/node_modules/loopback-datasource-juggler/lib/observer.js:240:14)
    at /app/node_modules/loopback-connector/lib/sql.js:643:9
    at Query.<anonymous> (/app/node_modules/loopback-connector-postgresql/lib/postgresql.js:152:7)
    at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:191:19)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:124:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

```

**Comment by horstmannmat** [comment]
I did it on a extended model, but I think that it should crash on User model too.

**Comment by BrunoMeyer** [comment]
Im working with him (@horstmannmat ), and we think that maybe there is an problem on the  loopback-datasource-juggler project when the field isNewInstance of instances is updated.

After reproduce the error, i debugged  `common/models/user.js` file and check the line 1340 where ctx.isNewInstance is returning `false` when we PUT with an specific id.
After a simple exploration, the only file that i found that change this attribute is the [persistence-hooks.suite.js](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/persistence-hooks.suite.js) on loopback-datasource-juggler. But i cannot find any reasons until now.

**Comment by horstmannmat** [comment]
We decided, even if the problem be at loopback-datasource-juggler, that the array must be checked if it is null before using, and so on fixing the problem, the expected result turn to be like others models
