### ISSUE TITLE
Error: "items" property must be present if "type" is an array at jsonToSchemaObject

### ISSUE THREAD

**Issue by aabou** [strongloop/loopback#4109]
# Description/Steps to reproduce
@loopback/cli version: 1.4.0
nodejs : v8.11.2

1. lb4 myapp
2. lb4 openapi http://petstore.swagger.io/v2/swagger.json
3. npm start

> petstore@1.0.0 prestart C:\Users\MYPC\workspace\petstore
> npm run build

> petstore@1.0.0 build C:\Users\MYPC\workspace\petstore
> lb-tsc es2017 --outDir dist

> petstore@1.0.0 start C:\Users\MYPC\workspace\petstore
> node .

Cannot start the application. Error: "items" property must be present if "type" is an array
    at jsonToSchemaObject (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\openapi-v3\dist\src\json-to-schema.js:28:27)
    at result.properties._.mapValues.item (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\openapi-v3\dist\src\json-to-schema.js:42:74)
    at C:\Users\MYPC\workspace\petstore\node_modules\lodash\lodash.js:13402:38
    at C:\Users\MYPC\workspace\petstore\node_modules\lodash\lodash.js:4911:15
    at baseForOwn (C:\Users\MYPC\workspace\petstore\node_modules\lodash\lodash.js:2996:24)
    at Function.mapValues (C:\Users\MYPC\workspace\petstore\node_modules\lodash\lodash.js:13401:7)
    at Object.jsonToSchemaObject (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\openapi-v3\dist\src\json-to-schema.js:42:39)
    at generateOpenAPISchema (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\openapi-v3\dist\src\controller-spec.js:184:44)
    at resolveControllerSpec (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\openapi-v3\dist\src\controller-spec.js:130:17)
    at Object.getControllerSpec (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\openapi-v3\dist\src\controller-spec.js:207:16)
    at RestServer._setupHandlerIfNeeded (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\rest\dist\src\rest.server.js:195:42)
    at RestServer.start (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\rest\dist\src\rest.server.js:537:14)
    at _forEachServer.s (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\core\dist\src\application.js:127:42)
    at Promise.all.bindings.map (C:\Users\MYPC\workspace\petstore\node_modules\@loopback\core\dist\src\application.js:149:26)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! petstore@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the petstore@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MYPC\AppData\Roaming\npm-cache\_logs\2019-01-09T13_40_42_873Z-debug.log

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by tylkomat** [comment]
Look at the models to find properties that have array values they have to be [decorated](https://loopback.io/doc/en/lb4/Model.html#array-property-decorator) with `@property.array(TYPE, {name: ...})`. The generator does not generate them properly.

**Comment by aabou** [comment]
Thanks @tylkomat,
So it will be corrected in the future?

**Comment by Tyagi0502** [comment]
Same issue occurring for some time now. Fixed it last time by replacing Class name in a specific field definition with 'object'. But, it started happening again and cannot fix it now by any means.
