### ISSUE TITLE
Windows - lb v3 cli@v5.0.0 - OpenSSL v1.0.x libeay.lib is required for strong-ursa module but is missing in v OpenSSL v1.1.x

### ISSUE THREAD

**Issue by methodbox** [strongloop/loopback#4117]
Installing LB v3 results in a compiling error for the dependency ```strong-ursa```. This has been forked by ```strongloop-forks``` here:  https://github.com/strongloop-forks/ursa which was, per commit comments, updated ~8 mo ago to support OpenSSL v1.1.0, but this has not, apparently, been backported into LB v3 as this error still occurs:

```powershell
C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa>if not defined npm_config_node_gyp (node "C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
c:\users\xxxxxx\appdata\roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa\src\ursanative.cc(484): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\xxxxxx\AppData\Roamin
g\npm\node_modules\loopback-cli\node_modules\strong-ursa\build\ursaNative.vcxproj]
c:\users\xxxxxx\appdata\roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa\src\ursanative.cc(504): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\xxxxxx\AppData\Roamin
g\npm\node_modules\loopback-cli\node_modules\strong-ursa\build\ursaNative.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-ursa@0.10.1 (node_modules\loopback-cli\node_modules\strong-ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-ursa@0.10.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ loopback-cli@5.0.0
updated 1 package in 23.938s
```

This appears to be due to the fact that the file ```C:\OpenSSL-Win64\lib\libeay32.lib``` was renamed to ssleay32.lib in the 1.1.x version of OpenSSL and that the node module ```loopback-cli``` has not been updated with your fork of ```strong-ursa``` to support the latest version.

This dependency is not outlined on the Loopback site.

Either backport it or update the docs, please.

# Description/Steps to reproduce

Attempt to install loopback with ```npm i -g loopback-cli``` in Windows 10/2016 with a version of OpenSSL installed >= @1.1.x.

# Link to reproduction sandbox
You can produce this using Powershell in Windows.

# Expected result
The forked version of strong-ursa would have been integrated to support this. It's either not a dependency or has been ported into LB v4.

# Additional information

Grep doesn't work of course, because this Windows, but here you go:

```powershell
PS C:\Users\xxxxxx\code\loopback>  node -e 'console.log(process.platform, process.arch, process.versions.node)'
win32 x64 8.10.0
PS C:\Users\xxxxxx\code\loopback>   npm ls --prod --depth 0 | grep loopback
grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:29
+   npm ls --prod --depth 0 | grep loopback
+                             ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by methodbox** [comment]
As a solution installed OpenSSL 1.0.2q from here which worked:

https://slproweb.com/products/Win32OpenSSL.html
