### ISSUE TITLE
Verification User Register Error User Not Found

### ISSUE THREAD

**Issue by trungdh** [strongloop/loopback#4204]
I'm facing an error about verification user after register. I got Error : 
```
Error
404 User not found: 5cdce19135f71a429681864a
code: USER_NOT_FOUND
Error: User not found: 5cdce19135f71a429681864a
    at /home/project/dev/my_server/node_modules/loopback/common/models/user.js:909:19
    at  /home/project/dev/my_server//node_modules/loopback-datasource-juggler/lib/dao.js:1781:62
    at  /home/project/dev/my_server//node_modules/loopback-datasource-juggler/lib/dao.js:1717:9
    at  /home/project/dev/my_server/r/node_modules/async/dist/async.js:1140:9
    at  /home/project/dev/my_server//node_modules/async/dist/async.js:473:16
    at eachOfArrayLike ( /home/project/dev/my_server/node_modules/async/dist/async.js:1057:9)
    at eachOf ( /home/project/dev/my_server/node_modules/async/dist/async.js:1117:5)
    at _asyncMap ( /home/project/dev/my_server/node_modules/async/dist/async.js:1133:5)
    at Object.map ( /home/project/dev/my_server/node_modules/async/dist/async.js:1122:16)
    at allCb ( /home/project/dev/my_server/node_modules/loopback-datasource-juggler/lib/dao.js:1628:13)
    at  /home/project/dev/my_server/node_modules/loopback-connector-mongodb/lib/mongodb.js:1373:9
    at result ( /home/project/dev/my_server/node_modules/mongodb/lib/utils.js:410:17)
    at executeCallback ( /home/project/dev/my_server/node_modules/mongodb/lib/utils.js:402:9)
    at handleCallback ( /home/project/dev/my_server/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close ( /home/project/dev/my_server/node_modules/mongodb/lib/operations/cursor_ops.js:224:62)
    at handleCallback ( /home/project/dev/my_server/node_modules/mongodb/lib/utils.js:128:55)
```

I've checked in my mongo database. This user already existed with that id. I extended built-in User model and here is my code : 
**Users.json**
```json
{
  "name": "Users",
  "plural": "users",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "restrictResetPasswordTokenScope": true,
  "emailVerificationRequired": true,
  "excludeBaseProperties": [
    "realm"
  ],
  "hidden": [
    "password"
  ],
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "email": {
      "type": "string",
      "required": true
    },
    "password": {
      "type": "string",
      "required": true
    },
    "image_profile": {
      "type": "string"
    },
    "gender": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "user_rank": {
      "type": "number",
      "required": true,
      "default": 0
    },
    "is_third_party": {
      "type": "boolean",
      "required": true,
      "default": false
    },
    "is_active": {
      "type": "boolean",
      "required": true,
      "default": true
    },
    "created": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    },
    "modified": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    }
  },
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "AccessTokens",
      "foreignKey": "userId",
      "option": {
        "disableInclude": true
      }
    }
  },
  "acls": [],
  "methods": {}
}
```

**Users.js**
```js
'use strict';
const Constant = require('../../server/utils/constants');
var path = require('path');
module.exports = function(Users) {

    Users.afterRemote('create',(ctx,user,next)=>{
        var options = {
            host : Constant.serverURL,
            type : 'email',
            to : user.email,
            from : 'no-reply@mydomain.com',
            subject: 'Thanks for registering...',
            template: path.resolve(__dirname, '../../server/views/verify.ejs'),
            text : 'Please activate your account by clicking on this link or copying and pasting it in a new browser window:\n\t{href}',
            redirect: `/api/users/verified?uid=${user.id}`,
            user: user,
            protocol: 'http',
            host : 'localhost',
            port : 6001
        }

        user.verify(options,(err,success)=>{
            if(err){
                Users.deleteById(user.id);
                return next(err);
            }
            console.log('sent verify email to use register ' + success);
        })
        next();
    })

    Users.afterRemote('prototype.verify', (ctx, user, next) => {
        ctx.res.render('response', {
            title: 'A Link to reverify your identity has been sent to your email successfully',
            content: 'Please check your email and click on the verification link before loggin in',
            redirectTo: '/',
            redirectToLinkText: 'Login'
        });
    })

    //handle verify click on email
    Users.verified = (req,res,uid,next)=>{
        console.log('user verified');
        //Mapping customer role for user after register
        Users.app.models.Role.findOne({where : { name :'customer'}})
        .then(role=>{
            return Users.app.models.RoleMapping.create({
                principalType: Users.app.models.RoleMapping.USER,
                principalId: user.id,
                roleId: role.id
            }).then(mapping=>{
                return mapping;
            })
        }).then(mapping=>{
            console.log(`user has registered with role mapping ${mapping}`);
            res.render('response', {
                title: 'Verify successed, account be actived',
                content: 'You can use account to login on xper system',
                redirectTo: `http://localhost:6001`,
                redirectToLinkText: 'Log in'
            });
        }).catch(err=>{
            console.log('mapping user role error', err);
            res.render('response', {
                title: 'Verify error, account not be actived',
                content: 'Error while creating your digital wallet'
            });
        })
    }

    Users.remoteMethod('verified',{
        accepts: [{ arg: 'req', type: 'Object', http: { source: 'req' } },
        { arg: 'res', type: 'Object', http: { source: 'res' } },
        { arg: 'uid', type: 'string', http: { source: 'query' } },
        ],
        returns: { arg: 'result', type: 'Object', root: true },
        http: { path: '/verified', verb: 'get' },
        description: 'user verify page'
    })
};
```

And here is verify URL which I got in my email:

```
http://localhost:6001/api/users/confirm?uid=5cdce19135f71a429681864a&redirect=%2Fapi%2Fusers%2Fverified%3Fuid%3D5cdce19135f71a429681864a&token=f1cceb588ae5ee7cc2a056b55cba2b34198e622bdf4d3aeb73436766f2063cb11bea1e4cf40c90988bc60a1499b9a90369898880f958c68ddbe140147faf4456
```

I have no idea why got this error. Please help. Thanks

**Comment by luxigo** [comment]
I had to set "public" to false for the base Users model in model-config.json so that User.findById works eventually.
