### ISSUE TITLE
Custom connector inside project

### ISSUE THREAD

**Issue by ajouve** [strongloop/loopback#4233]
# Description/Steps to reproduce

I am using loopback 3.25.1

Create the following file in connectors/rabbitmq.js

```
const Connector = require('loopback-connector').Connector;

/**
 * Initialize the  connector against the given data source
 *
 * @param {DataSource} dataSource The loopback-datasource-juggler dataSource
 * @param {Function} [callback] The callback function
 */
exports.initialize = function initializeDataSource(dataSource, callback) {
  dataSource.connector = new RabbitMQ(dataSource.settings);
};

function RabbitMQ(settings) {
  // Call the super constructor with name and settings
  Connector.call(this, 'rabbitmq', settings);
  //...
}

RabbitMQ.prototype.connect = function (cb) {
  // ...
};

RabbitMQ.prototype.disconnect = function (cb) {
  // ...
};
```

# Expected result

Should create a connector

# Additional information

Starting my project I have the following error message

```
 WARNING: LoopBack connector "rabbitmq" is not installed as any of the following modules:

  ./connectors/rabbitmq
 loopback-connector-rabbitmq
 rabbitmq

 To fix, run:

     npm install rabbitmq --save

 /usr/src/app/node_modules/loopback/lib/application.js:280
     throw err;
     ^

 Error: Cannot create data source "rabbitmq":
 WARNING: LoopBack connector "rabbitmq" is not installed as any of the following modules:

  ./connectors/rabbitmq
 loopback-connector-rabbitmq
 rabbitmq

 To fix, run:

     npm install rabbitmq --save

     at DataSource.setup (/usr/src/app/node_modules/loopback-datasource-juggler/lib/datasource.js:448:26)
     at new DataSource (/usr/src/app/node_modules/loopback-datasource-juggler/lib/datasource.js:138:8)
     at Registry.createDataSource (/usr/src/app/node_modules/loopback/lib/registry.js:364:12)
     at dataSourcesFromConfig (/usr/src/app/node_modules/loopback/lib/application.js:570:19)
     at Function.app.dataSource (/usr/src/app/node_modules/loopback/lib/application.js:269:14)
     at /usr/src/app/node_modules/loopback-boot/lib/executor.js:191:9
     at /usr/src/app/node_modules/loopback-boot/lib/executor.js:282:5
     at Array.forEach (<anonymous>)
     at forEachKeyedObject (/usr/src/app/node_modules/loopback-boot/lib/executor.js:281:20)
     at setupDataSources (/usr/src/app/node_modules/loopback-boot/lib/executor.js:181:3)
     at execute (/usr/src/app/node_modules/loopback-boot/lib/executor.js:39:3)
     at bootLoopBackApp (/usr/src/app/node_modules/loopback-boot/index.js:154:3)
     at Object.<anonymous> (/usr/src/app/server/server.js:63:1)
     at Module._compile (internal/modules/cjs/loader.js:776:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
     at Module.load (internal/modules/cjs/loader.js:653:32)
 Emitted 'error' event at:
     at DataSource.setup (/usr/src/app/node_modules/loopback-datasource-juggler/lib/datasource.js:448:12)
     at new DataSource (/usr/src/app/node_modules/loopback-datasource-juggler/lib/datasource.js:138:8)
     [... lines matching original stack trace ...]
     at Module.load (internal/modules/cjs/loader.js:653:32)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! service-rest@1.0.0 fixtures: `node bin/fixtures/index.js`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the service-rest@1.0.0 fixtures script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2019-07-23T09_31_48_754Z-debug.log
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! service-rest@1.0.0 launch: `npm run fixtures && npm start`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the service-rest@1.0.0 launch script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2019-07-23T09_31_48_808Z-debug.log
```

I have my file in `./connectors/rabbitmq`, I tried the following paths and I always have the same issue 

`connectors/rabbitmq.js`
`connectors/rabbitmq/index.js`
`server/connectors/rabbitmq.js`
`server/connectors/rabbitmq/index.js`

I also tried to add 

`app.connector('rabbitmq', require('../connectors/rabbitmq'))` just after `var app = module.exports = loopback();` in `server/server.js` but I have the same issue

**Comment by ajouve** [comment]
up
