### ISSUE TITLE
loopback remote connector does not support relations

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback#429]
I was playing with browserify, because i wanted to generate api for my app, but relations does not seem to work.

**Comment by Mowso** [comment]
I think I'm experiencing the same issue. I'm following this [doc](https://docs.strongloop.com/display/public/LB/Authentication%2C+authorization%2C+and+permissions) in an API with a [container](https://docs.strongloop.com/display/public/LB/Storage+component) and I have an error when I add relations to my container model.
```
{
  "name": "Container",
  "base": "PersistedModel",
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
Here's my container.json and here's the error :
```
TypeError: Cannot call method 'call' of undefined
    at EventEmitter.<anonymous> (/home/mowso/Documents/loopback-examples/test/node_modules/loopback-datasource-juggler/lib/datasource.js:434:37)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DataSource.setupDataAccess (/home/mowso/Documents/loopback-examples/test/node_modules/loopback-datasource-juggler/lib/datasource.js:540:14)
    at DataSource.attach (/home/mowso/Documents/loopback-examples/test/node_modules/loopback-datasource-juggler/lib/datasource.js:752:8)
    at Function.ModelClass.attachTo (/home/mowso/Documents/loopback-examples/test/node_modules/loopback-datasource-juggler/lib/model-builder.js:336:16)
    at Registry.configureModel (/home/mowso/Documents/loopback-examples/test/node_modules/loopback/lib/registry.js:238:15)
    at configureModel (/home/mowso/Documents/loopback-examples/test/node_modules/loopback/lib/application.js:441:16)
    at EventEmitter.app.model (/home/mowso/Documents/loopback-examples/test/node_modules/loopback/lib/application.js:133:5)
    at /home/mowso/Documents/loopback-examples/test/node_modules/loopback-boot/lib/executor.js:190:9

```
Any ideas :grin: ?

**Comment by sneakersgames** [comment]
I got the same issue as @Mowso here. Created an S3 container and relationships on a Model throw the same error.

**Comment by regevbr** [comment]
The answer is that when implementing your own DataAccessObject you need to mixin into it the Original dao and apply changes to it.

e.g.
```node
const mixin = require('loopback-datasource-juggler').ModelBaseClass.mixin;
  connector.DataAccessObject = function () {
  };
  mixin.apply(connector.DataAccessObject, [dataSource.constructor.DataAccessObject]);
```

**Comment by husnulhamidiah** [comment]
@regevbr can you give a complete example how to solve this problem. I got same problem as @Mowso here.

**Comment by regevbr** [comment]
I created a rewrite of the stroage component that works with relations and acl - [loopback-component-flatstorage](https://github.com/regevbr/loopback-component-flatstorage)
You can check out the code there and see how I solved the issue when you create you own DataAccessObject

**Comment by mihir83in** [comment]
I have the same issue with the same stacktrace when creating two different models Contacts and Cities which are from two different soap based data sources.
