### ISSUE TITLE
In a registration process, error makes server down and I get "Error: Illegal argument types: object, string"

### ISSUE THREAD

**Issue by Acaspita** [strongloop/loopback#431]
In a registration process, I execute the following lines:
```javascript
$scope.registration = {
                "user" : $scope.registrationForm.display_name,
                "password" : $scope.registrationForm.password,
                "email" : $scope.registrationForm.email
            };
            $scope.user = User.save($scope.registration,
```
This makes the server down, and I get:
```
Error: Illegal argument types: object, string                                                                                                                     
    at Object.bcrypt.hashSync (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:1028:19)   
    at ModelConstructor.UserModel.setter.password (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback\lib\models\user.js:441:29)  
    at ModelConstructor.Object.defineProperty.set [as password] (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-jug
gler\lib\model-builder.js:378:43)                                                                                                                                 
    at ModelConstructor.ModelBaseClass._initProperties (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\
model.js:128:17)                                                                                                                                                  
    at ModelConstructor.ModelBaseClass (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\model.js:40:8)  
    at ModelConstructor (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\model-builder.js:159:22)       
    at ModelConstructor (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\model-builder.js:159:22)       
    at new ModelConstructor (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\model-builder.js:159:22)   
    at Function.DataAccessObject.create (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\dao.js:145:11) 
    at Function.f [as create] (C:\Users\Acaspita\Documents\Stratap\CrunchBase.Mining\server\node_modules\loopback-datasource-juggler\lib\jutil.js:100:15)
```
Is this somewhat critical? I know I'm sending objects instead of values, but..., is this some kind of vulnerability?

**Comment by bajtos** [comment]
We already added try/catch around invocation of remote method (like `User.create`) in https://github.com/strongloop/strong-remoting/pull/119, I believe that should have fixed the original problem of crashing.

> How about check the request data against schema in strong-remoting? The RemoteMethod contains Argument descriptions, which contains enough information to do this.

I am not totally opposed to this idea, but it may require a bit more of effort. Please open a new issue if you think it's still relevant.
