### ISSUE TITLE
lb export-api-def throws loopbackApplication.get is not a function

### ISSUE THREAD

**Issue by garrett-gottlieb** [strongloop/loopback#4331]
## Steps to reproduce

`lb export-api-def`

## Current Behavior

```
TypeError: loopbackApplication.get is not a function
    at createSwaggerObject (/Users/gsquare567/.config/yarn/global/node_modules/loopback-api-definition/node_modules/loopback-swagger/lib/specgen/swagger-spec-generator.js:31:35)
    at Object.getApiDef (/Users/gsquare567/.config/yarn/global/node_modules/loopback-api-definition/lib/get-api-def.js:23:23)
    at constructor.generate (/Users/gsquare567/.config/yarn/global/node_modules/generator-loopback/export-api-def/index.js:39:31)
    at Object.<anonymous> (/Users/gsquare567/.config/yarn/global/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/gsquare567/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/gsquare567/.config/yarn/global/node_modules/run-async/index.js:24:19
    at /Users/gsquare567/.config/yarn/global/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

## Expected Behavior

Output the API def

## Additional information

NOTE: I had to use ` yarn list --prod --depth 0 | grep loopback` because I'm using yarn workspace
```
darwin x64 12.16.3
├─ loopback-boot@3.3.1
├─ loopback-component-explorer@6.5.0
├─ loopback-connector-postgresql@3.8.1
├─ loopback-connector-remote@3.4.1
├─ loopback-connector@4.10.0
├─ loopback-datasource-juggler@3.35.0
├─ loopback-datatype-geopoint@1.0.0
├─ loopback-filters@1.0.0
├─ loopback-phase@3.3.0
├─ loopback-swagger@5.8.0
├─ loopback@3.27.0
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Thank you for reporting the issue. I don't see any obvious cause of the problem. Can you please create a small app we can use to reproduce it?

See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs

_Note: Failure to provide a sandbox application for reproduction purposes will result in the issue being closed._
