### ISSUE TITLE
Where should I define models in code?

### ISSUE THREAD

**Issue by eabruzzese** [strongloop/loopback#476]
I'm trying to define a polymorphic relationship. This doesn't seem to be supported using the JSON format, so I'm trying to do it in code. Logically, I was trying to put it in a .js file next to my .json file for the model. However, this doesn't work:

```javascript
module.exports = function (Installer) {

  Installer.belongsTo('installable', { polymorphic: true }); // Errors

  Installer.validatesPresenceOf('name');

  app.model(Installer);

}
```
When run, the above code produces the following error:

```
/path/to/project/common/models/installer.js:7
  Installer.belongsTo('installable', { polymorphic: true })
            ^
TypeError: Object function ModelConstructor(data, options) {
      if (!(this instanceof ModelConstructor)) {
        return new ModelConstructor(data, options);
      }
      if (ModelClass.settings.unresolved) {
        throw new Error('Model ' + ModelClass.modelName + ' is not defined.');
      }
      ModelBaseClass.apply(this, arguments);
    } has no method 'belongsTo'
    at module.exports (/path/to/project/common/models/installer.js:7:13)
    at /path/to/project/node_modules/loopback-boot/lib/executor.js:159:11
    at Array.forEach (native)
    at defineModels (/path/to/project/node_modules/loopback-boot/lib/executor.js:141:23)
    at setupModels (/path/to/project/node_modules/loopback-boot/lib/executor.js:130:3)
    at execute (/path/to/project/node_modules/loopback-boot/lib/executor.js:25:3)
    at bootLoopBackApp (/path/to/project/node_modules/loopback-boot/index.js:79:3)
    at Object.<anonymous> (/path/to/project/worker/server.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Am I trying to do this in the wrong place?

Thanks,
Eric

**Comment by superkhau** [comment]
@bajtos @raymondfeng @fabien Has the issue been resolved? Can I close it?

**Comment by bajtos** [comment]
Since there was activity since Aug last year, I think it's safe to close this issue. We can always reopen later if there is any new information added.
