### ISSUE TITLE
user.verify doesn't save verificationToken

### ISSUE THREAD

**Issue by ltjin** [strongloop/loopback#553]
when i use user.verify method to send verify email,create a verificationToken can't to saved

Trace: Property not found: User.create
    at MySQL.Connector.id (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-connector-mysql/node_modules/loopback-connector/lib/connector.js:108:13)
    at /Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-connector-mysql/lib/mysql.js:226:29
    at Array.forEach (native)
    at MySQL.updateOrCreate.MySQL.save (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-connector-mysql/lib/mysql.js:225:21)
    at ModelConstructor.<anonymous> (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:962:25)
    at ModelConstructor.trigger (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/hooks.js:56:12)
    at ModelConstructor.<anonymous> (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:960:12)
    at ModelConstructor.trigger (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/hooks.js:56:12)
    at save (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:959:10)
    at /Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:946:7

TypeError: Cannot read property 'id' of undefined
    at MySQL.Connector.id (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-connector-mysql/node_modules/loopback-connector/lib/connector.js:110:11)
    at /Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-connector-mysql/lib/mysql.js:226:29
    at Array.forEach (native)
    at MySQL.updateOrCreate.MySQL.save (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-connector-mysql/lib/mysql.js:225:21)
    at ModelConstructor.<anonymous> (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:962:25)
    at ModelConstructor.trigger (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/hooks.js:56:12)
    at ModelConstructor.<anonymous> (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:960:12)
    at ModelConstructor.trigger (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/hooks.js:56:12)
    at save (/Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:959:10)
    at /Users/kland/Documents/PROJECTS/VOICI/server/voici/node_modules/loopback-datasource-juggler/lib/dao.js:946:7

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by richardpringle** [comment]
@superkhau, safe to close?

**Comment by superkhau** [comment]
Sure. @ltjin It you are still having issues, please ping again and we will reopen the issue and please provide a sample repo so we can reproduce it on our end.
