### ISSUE TITLE
raiseUrlNotFoundError

### ISSUE THREAD

**Issue by adamski** [strongloop/loopback#573]
Getting raiseUrlNotFoundError when trying to access freshly created loopback instance, however explorer works ok.

**Comment by Banda17** [comment]
Unhandled error for request POST /explorer/: Error: Cannot POST /explorer/
    at raiseUrlNotFoundError (/home/bb/Desktop/test/css_web_server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:317:13)
    at /home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/bb/Desktop/test/css_web_server/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:317:13)
    at /home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:796:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
Unhandled error for request GET /cordova.js: Error: Cannot GET /cordova.js
    at raiseUrlNotFoundError (/home/bb/Desktop/test/css_web_server/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:317:13)
    at /home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/bb/Desktop/test/css_web_server/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/bb/Desktop/test/css_web_server/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/home/bb/Desktop/test/css_web_server/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/bb/Desktop/test/css_web_server/node_modules/send/index.js:421:12)
    at onstat (/home/bb/Desktop/test/css_web_server/node_modules/send/index.js:727:26)
    at FSReqWrap.oncomplete (fs.js:152:21)
this is the error ? how to fix this ?
