### ISSUE TITLE
Application cannot call 'findById' in AccessToken

### ISSUE THREAD

**Issue by medokin** [strongloop/loopback#756]
Application cannot find 'findById' in AccessToken.

Related disscusion: https://groups.google.com/forum/#!msg/loopbackjs/FpREfreuDoo/zVy_z2MbSTwJ

Steps to reproduce:
1. Create new project
2. Start
3. Create user
4. Login user
5. Request user list or just try to log out

```
Error: Cannot call AccessToken.findById(). The findById method has not been setup. The   PersistedModel has not been correctly attached to a DataSource!
    at throwNotAttached (C:\dev\loopback-api\node_modules\loopback\lib\persisted-model.js:55:9)
    at Function.find [as findById] (C:\dev\loopback-api\node_modules\loopback\lib\persisted-model.js:135:3)
    at Function.AccessToken.findForRequest (C:\dev\loopback-api\node_modules\loopback\common\models\access-token.js:94:12)
    at C:\dev\loopback-api\node_modules\loopback\lib\middleware\token.js:53:16
    at C:\dev\loopback-api\node_modules\loopback\lib\middleware\rest.js:46:7
    at Layer.handle [as handle_request] (C:\dev\loopback-api\node_modules\loopback\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\dev\loopback-api\node_modules\loopback\node_modules\express\lib\router\index.js:270:13)
    at C:\dev\loopback-api\node_modules\loopback\node_modules\express\lib\router\index.js:237:9
    at Function.proto.process_params (C:\dev\loopback-api\node_modules\loopback\node_modules\express\lib\router\index.js:312:12)
    at C:\dev\loopback-api\node_modules\loopback\node_modules\express\lib\router\index.js:228:12

```

![image](https://cloud.githubusercontent.com/assets/456683/4934713/683377b6-65a4-11e4-909a-5122cc81a2ec.png)

**Comment by yagobski** [comment]
I have same error with loopback 3.0

`Unhandled error for request GET /api/Albums/3?access_token=mJIE9mwBpcuSrAii3zuDxfYAJHnDGBSXRghm3a5HHa9g9vLZHh02eGglQUlz13on: Error: Cannot call AccessToken.findById(). The findById method has not been setup. The PersistedModel has not been correctly attached to a DataSource!
`

**Comment by thatbeardo** [comment]
Facing this same issue on Windows 10. @yagobski, Did you find anything ?

**Comment by ndjathe-master** [comment]
Facing the same issue on Mac OS Sierra 10.12.6. Please Help!

**Comment by jersonjohn** [comment]
Same Issue in mac
