### ISSUE TITLE
Cannot find module 'loopback-phase' 

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#784]
$ slc loopback
Error loading module "loopback":
 { [Error: Cannot find module 'loopback-phase'] code: 'MODULE_NOT_FOUND' }

Looks like we need to update the package.json with loopback-phase as dependency. 
Blocking

**Comment by mike-aungsan** [comment]
I am seeing this error again.

$ npm -v
2.15.1
$ node -v
v4.4.3

Error: Cannot find module 'loopback-phase'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/loopback/lib/server-app.js:4:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/loopback/lib/loopback.js:6:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/loopback/index.js:5:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)



  "dependencies": {

    "compression": "1.6.0",
    "cors": "2.7.1",

    "loopback": "<=2.25.0",
    "loopback-boot": "<=2.14.0",
    "loopback-component-explorer": "2.1.1",
    "loopback-datasource-juggler": "<=2.44.0",
    "serve-favicon": "2.3.0",

    "async": "1.5.2",
    "lodash": "4.0.0",

    "mongodb": "2.1.4",
    "connect-mongo": "1.1.0",

    "body-parser": "1.14.2",

    "express-flash": "0.0.2",
    "express-session": "1.13.0",

    "cookie-parser": "1.4.1",
    "connect-ensure-login": "0.1.1",

    "passport-ldapauth": "0.5.0",

    "loopback-connector-mongodb": "1.13.3",
    "loopback-component-passport": "<=1.6.0",
    "loopback-component-storage": "1.6.1",
    "loopback-connector-rest": "1.10.1",

    "ldapauth-fork": "2.5.0",
    
    "validator": "4.5.0",
    "bluebird": "3.1.1 ",
    "fs-extra-promise": "0.3.1",
    "multer": "1.1.0",
    "mime": "1.3.4",
    "bunyan": "1.5.1",
    "bunyan-syslog": "0.3.1",
    "request": "2.69.0",
    "cron": "1.1.0",
    "node-schedule": "1.0.0",

    "moment": "2.11.2",
    "response-time": "2.3.1",
    "exceljs": "latest"

  }
