### ISSUE TITLE
Problem after have run the command slc loopback:relation

### ISSUE THREAD

**Issue by nickleus73** [strongloop/loopback#900]
Hi,

I don't know if is it a bug, but I have this error after have run the command slc loopback:relation on a custom model (Member model based on User model), when I run the server with this command line : slc run.

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/var/www/html'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/bin/sl-run.js:40:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at /usr/local/lib/node_modules/strongloop/lib/command.js:25:23
    at CommandLoader.run (/usr/local/lib/node_modules/strongloop/lib/loader.js:121:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/bin/slc:10:4)
```

I tried to add a relation from my Member model to the accessToken model. 

The Member model is like this :

```
{
  "name": "Member",
  "base": "User",
  "idInjection": true,
  "properties": {
    "firstname": {
      "type": "string",
      "required": true
    },
    "lastname": {
      "type": "string",
      "required": true
    },
    "phone": {
      "type": "number"
    },
    "last_login": {
      "type": "date"
    },
    "deleted": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "AccessToken",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": []
}
```

Can you help me on this subject.

Thank you.

PS : I work on VM vagrant and I'm sorry for my approximate english :)

**Comment by loay** [comment]
@nickleus73 
Is this issue still persisting? Thanks

**Comment by raymondfeng** [comment]
I am out of the office until 01/04/2016.

Happy holidays!


Note: This is an automated response to your message  "Re: [loopback]
Problem after have run the command slc loopback:relation (#900)" sent on
12/21/15 2:47:22 PM.

This is the only notification you will receive while this person is away.

**Comment by loay** [comment]
Hello, 
Closing due to inactivity. If you are still running into problems, feel free to leave a comment and I will reopen the issue.
