### ISSUE TITLE
How to config passport in `middleware.json`?

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback#954]
I try to use passport in `middleware.json`, as follow:

```json
  "auth": {
    "passport#authenticate": {
      "paths": ["/login"],
      "params": ["local", { "session": true }]
    }
  }
```
But got this:
>
/Developer/Projects/WebStormProjects/joypet-server/node_modules/passport/lib/authenticator.js:167
  return this._framework.authenticate(this, strategy, options, callback);
                         ^
TypeError: Cannot call method 'authenticate' of undefined
    at Authenticator.authenticate (/Developer/Projects/WebStormProjects/joypet-server/node_modules/passport/lib/authenticator.js:167:26)
    at EventEmitter.proto.middlewareFromConfig (/Developer/Projects/WebStormProjects/joypet-server/node_modules/loopback/lib/server-app.js:67:25)

**Comment by bajtos** [comment]
Fixed by #92.
