### ISSUE TITLE
invalid value for argument 'filter' of type 'object': {\"where\": {\"name\":\"Rpto. K\\hn (masaya)\"}}

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/loopback#965]
Url:

http://localhost:3000/api/locations/findOne?filter=%7B%22where%22%3A%20%7B%22name%22%3A%22Rpto.%20K%5Chn%20(masaya)%22%7D%7D

## Filter

    {"where": {"name":"Rpto. K\hn (masaya)"}}

## Response

    {
      "error": {
        "name": "Error",
        "status": 400,
        "message": "invalid value for argument 'filter' of type 'object': {\"where\": {\"name\":\"Rpto. K\\hn (masaya)\"}}",
        "statusCode": 400,
        "stack": "Error: invalid value for argument 'filter' of type 'object': {\"where\": {\"name\":\"Rpto. K\\hn (masaya)\"}}\n    at badArgumentError (/Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:246:13)\n    at SharedMethod.invoke (/Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:209:21)\n    at HttpContext.invoke (/Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:262:12)\n    at /Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:501:9\n    at execStack (/Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:354:7)\n    at /Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/lib/application.js:318:13\n    at /Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/lib/model.js:295:5\n    at /Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/common/models/acl.js:433:23\n    at /Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/async/lib/async.js:254:17\n    at async.each (/Users/paulomcnally/develop/github/mcnallydev/telecobranza/node_modules/loopback/node_modules/async/lib/async.js:121:20)"
      }
    }

**Comment by superkhau** [comment]
@paulomcnally  Can you provide the code and steps to reproduce at https://github.com/strongloop.com/loopback-sandbox via a pull request?

**Comment by paulomcnally** [comment]
https://github.com/strongloop.com/loopback-sandbox => 404

**Comment by paulomcnally** [comment]
Sorry: https://github.com/strongloop/loopback-sandbox.

I will work on This

**Comment by raymondfeng** [comment]
https://github.com/strongloop/loopback-sandbox <https://github.com/strongloop/loopback-sandbox>

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by superkhau** [comment]
@paulomcnally Sorry I put an extra .com in the link. ;P It's fixed now! ;)

**Comment by loay** [comment]
@paulomcnally 
Is that issue still persisting?
Thanks

**Comment by raymondfeng** [comment]
I am out of the office until 01/04/2016.

Happy holidays!


Note: This is an automated response to your message  "Re: [loopback]
invalid value for argument 'filter' of type 'object': {\"where\": {\"name
\":\"Rpto. K\\hn (masaya)\"}} (#965)" sent on 12/21/15 2:44:45 PM.

This is the only notification you will receive while this person is away.

**Comment by paulomcnally** [comment]
Sorry. I close project. Thanks
